/** FUNCION: f_cgg_res_aeropuerto_select
* FUNCION QUE SELECCIONA LOS REGISTROS DE AEREOPUERTO PARA CARGAR EN UN STORE
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC 
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return refcursor
*DROP FUNCTION f_cgg_res_aeropuerto_select(character varying, integer, integer, character varying, character varying, text);
*/
CREATE OR REPLACE FUNCTION SII.f_cgg_res_aeropuerto_select(in_user_name character varying, in_start_index integer, in_limit integer, in_sort_field_name character varying, in_direction character varying, in_find_text text)
  RETURNS SETOF refcursor AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT
		AER.CARPT_CODIGO, 
		AER.CCTN_CODIGO,
		CAN.CCTN_NOMBRE AS CANTON,
		AER.CARPT_NOMBRE, 
		AER.CARPT_TIPO_AEREOPUERTO, 
		AER.CARPT_ESTADO, 
		AER.CARPT_FECHA_INSERT, 
		AER.CARPT_USUARIO_INSERT, 
		AER.CARPT_FECHA_UPDATE, 
		AER.CARPT_USUARIO_UPDATE
	FROM SII.CGG_RES_AEROPUERTO AER 
	LEFT JOIN SII.CGG_CANTON CAN ON(CAN.CCTN_CODIGO=AER.CCTN_CODIGO)
	WHERE CARPT_ESTADO = TRUE AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',COALESCE(CARPT_NOMBRE, '''')||'' ''||COALESCE(CARPT_TIPO_AEREOPUERTO, 0)||'' ''||COALESCE(CARPT_ESTADO, FALSE)||'' ''||COALESCE(CARPT_FECHA_INSERT, CURRENT_TIMESTAMP)||'' ''||COALESCE(CARPT_USUARIO_INSERT, '''')||'' ''||COALESCE(CARPT_FECHA_UPDATE, CURRENT_TIMESTAMP)||'' ''||COALESCE(CARPT_USUARIO_UPDATE, '''')) = 1
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100
  ROWS 1000;
