/**
* FUNCION: f_cgg_tct_movilidad_interna_select_documento_identific
* SELECCIONA LA INFORMACION DE MOVILIDA INTERNA DEPENDIENDO DEL NUMERO DE DOCUMENTO IDENTIFICATIVO DE LA PERSONA
* @param in_crper_numero_identificacion NUMERO DE DOCUMENTO IDENTIFICATIVO
* @return refcursor
*/
CREATE OR REPLACE FUNCTION f_cgg_tct_movilidad_interna_select_documento_identific(in_crper_numero_identificacion character varying)
  RETURNS SETOF refcursor AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
SELECT 		
		MV.CRMOV_CODIGO,				
		PR.CRPER_CODIGO,
		PR.CRDID_CODIGO,
		RG.CTREG_CODIGO,
		RG.CTREG_CODIGO_BARRAS,
		(SELECT CRDID_DESCRIPCION FROM  CGG_RES_DOCUMENTO_IDENTIFICACIO DI WHERE DI.CRDID_CODIGO = PR.CRDID_CODIGO) CRPER_TIPO_DOCUMENTO,
		PR.CRPER_NUM_DOC_IDENTIFIC,
		PR.CRPER_NUMERO_RESIDENCIA,
		PR.CRPER_NOMBRES,
		PR.CRPER_APELLIDO_PATERNO,
		PR.CRPER_GENERO,
		PR.CRPER_FECHA_NACIMIENTO,
		PR.CGNCN_CODIGO,		
		(SELECT CGNCN_NACIONALIDAD FROM  CGG_NACIONALIDAD NC WHERE NC.CGNCN_CODIGO = PR.CGNCN_CODIGO) CRPER_NACIONALIDAD,							
		MAX(MV.CRMOV_FECHA_VIAJE) CRMOV_FECHA_VIAJE,
		
		(SELECT CGCNF_CONFIGURACION
FROM CGG_CONFIGURACION C
WHERE CGCNF_VALOR_CADENA = (SELECT ST.CRTST_CODIGO FROM CGG_RES_TIPO_SOLICITUD_TRAMITE ST
INNER JOIN CGG_RES_RESIDENCIA RS ON (RS.CRTST_CODIGO = ST.CRTST_CODIGO)
 WHERE RS.CRRSD_VIGENTE = TRUE AND RS.CRPER_CODIGO=PR.CRPER_CODIGO)OR CGCNF_VALOR_CADENA = (SELECT ST.CGG_CRTST_CODIGO FROM CGG_RES_TIPO_SOLICITUD_TRAMITE ST
INNER JOIN CGG_RES_RESIDENCIA RS ON (RS.CRTST_CODIGO = ST.CRTST_CODIGO)
 WHERE RS.CRRSD_VIGENTE = TRUE AND RS.CRPER_CODIGO=PR.CRPER_CODIGO))TIPO_RESIDENCIA
		
	FROM SII.CGG_RES_MOVILIDAD MV
	INNER JOIN SII.CGG_TCT_REGISTRO RG ON(RG.CTREG_CODIGO=MV.CTREG_CODIGO)					
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = MV.CRPER_CODIGO)	
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON (RS.CRPER_CODIGO = PR.CRPER_CODIGO)	
	WHERE CRMOV_ESTADO = TRUE 	
	AND (RS.CRRSD_VIGENTE = TRUE AND MV.CRMOV_TIPO_OPERACION=0	
	AND PR.CRPER_NUMERO_RESIDENCIA = IN_CRPER_NUMERO_IDENTIFICACION
	OR PR.CRPER_NUM_DOC_IDENTIFIC =IN_CRPER_NUMERO_IDENTIFICACION
	OR RG.CTREG_CODIGO_BARRAS=IN_CRPER_NUMERO_IDENTIFICACION)
	GROUP BY MV.CRMOV_CODIGO,MV.CGG_CARPT_CODIGO,MV.CRMOV_TIPO_OPERACION, 				
		PR.CRPER_CODIGO,
		PR.CRDID_CODIGO,
		RG.CTREG_CODIGO,
		RG.CTREG_CODIGO_BARRAS,
		PR.CRPER_NUM_DOC_IDENTIFIC,
		PR.CRPER_NUMERO_RESIDENCIA,
		PR.CRPER_NOMBRES,
		PR.CRPER_APELLIDO_PATERNO,
		PR.CRPER_GENERO,
		PR.CRPER_FECHA_NACIMIENTO,
		PR.CGNCN_CODIGO,MV.CRMOV_FECHA_VIAJE
		ORDER BY MV.CRMOV_FECHA_VIAJE DESC LIMIT 1;		
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100
  ROWS 1000;
ALTER FUNCTION f_cgg_tct_movilidad_interna_select_documento_identific(character varying) OWNER TO sii;


