/**FUNCTION: F_CGG_RES_PERSONA_PERFIL_PROF_COUNT
* CONTABILIZA N REGISTROS DE LA TABLA SII.CGG_GEM_PERFIL_PROF.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param  IN_CRTST_CODIGO CRITERIO DE BUSQUEDA PARA RESIDENTES 
* @return TMP_ROWS
*/

CREATE OR REPLACE FUNCTION F_CGG_RES_PERSONA_PERFIL_PROF_COUNT(IN_FIND_TEXT TEXT,IN_CRTST_CODIGO CHARACTER VARYING)
  RETURNS INTEGER AS
$BODY$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM CGG_GEM_PERFIL_PROF PPR
	LEFT JOIN CGG_ESPECIALIDAD CGESP ON CGESP.CGESP_CODIGO = PPR.CGESP_CODIGO
	LEFT  JOIN CGG_TITULO_PROFESIONAL CGTPR ON CGTPR.CGTPR_CODIGO = PPR.CGTPR_CODIGO
	LEFT  JOIN CGG_INSTITUCION_EDUCATIVA CGIED ON  CGIED.CGIED_CODIGO = PPR.CGIED_CODIGO
	LEFT JOIN CGG_MODALIDAD_CURSO CGMDC ON CGMDC.CGMDC_CODIGO = PPR.CGMDC_CODIGO
	LEFT  JOIN CGG_NIVEL_ESTUDIO CGNES ON CGNES.CGNES_CODIGO = PPR.CGNES_CODIGO
	INNER JOIN SII.CGG_RES_PERSONA PER ON (PER.CRPER_CODIGO=PPR.CRPER_CODIGO)
	WHERE 
	SII.F_CHECK_PERSONA(CRPER_CODIGO, IN_CRTST_CODIGO) AND 
	PPR.CGPPR_ESTADO = TRUE AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	CASE WHEN PER.CRPER_CODIGO IS NULL THEN '''' ELSE PER.CRPER_CODIGO END ||' '||
	CASE WHEN PER.CRPER_NOMBRES IS NULL THEN '''' ELSE PER.CRPER_NOMBRES END ||' '||
	CASE WHEN PER.CRPER_APELLIDO_PATERNO IS NULL THEN '''' ELSE PER.CRPER_APELLIDO_PATERNO END ||' '||
	CASE WHEN PER.CRPER_APELLIDO_MATERNO IS NULL THEN '''' ELSE PER.CRPER_APELLIDO_MATERNO END ||' '||
	CASE WHEN PER.CRPER_NUM_DOC_IDENTIFIC IS NULL THEN '''' ELSE PER.CRPER_NUM_DOC_IDENTIFIC END ||' '||
	CASE WHEN PER.CRPER_FECHA_NACIMIENTO IS NULL THEN CURRENT_TIMESTAMP ELSE PER.CRPER_FECHA_NACIMIENTO END ||' '||
	CASE WHEN PER.CRPER_LUGAR_NACIMIENTO IS NULL THEN '''' ELSE PER.CRPER_LUGAR_NACIMIENTO END ||' '||
	CASE WHEN PER.CRPER_GENERO IS NULL THEN 0 ELSE PER.CRPER_GENERO END ||' '||
	CASE WHEN PER.CRPER_NUMERO_RESIDENCIA IS NULL THEN '''' ELSE PER.CRPER_NUMERO_RESIDENCIA END ||' '||
	CASE WHEN PER.CRPER_TIPO_PERSONA IS NULL THEN 0 ELSE PER.CRPER_TIPO_PERSONA END ||' '||
	CASE WHEN PER.CRPER_TIPO IS NULL THEN 0 ELSE PER.CRPER_TIPO END ||' '||
	CASE WHEN PER.CRPER_ESTADO IS NULL THEN FALSE ELSE PER.CRPER_ESTADO END ||' '||CASE WHEN PER.CRPER_FECHA_INSERT IS NULL THEN CURRENT_TIMESTAMP ELSE PER.CRPER_FECHA_INSERT END ||' '||
	CASE WHEN PER.CRPER_USUARIO_INSERT IS NULL THEN '''' ELSE PER.CRPER_USUARIO_INSERT END ||' '||
	CASE WHEN PER.CRPER_FECHA_UPDATE IS NULL THEN CURRENT_TIMESTAMP ELSE PER.CRPER_FECHA_UPDATE END ||' '||
	CASE WHEN PER.CRPER_USUARIO_UPDATE IS NULL THEN '''' ELSE PER.CRPER_USUARIO_UPDATE END ) = 1;
	RETURN TMP_ROWS;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;
ALTER FUNCTION F_CGG_RES_PERSONA_PERFIL_PROF_COUNT(TEXT,CHARACTER VARYING) OWNER TO SII;
