/**
* FUNCION f_cgg_dhu_curso_historial
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_DHU_CURSO.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return refcursor
*/
CREATE OR REPLACE FUNCTION f_cgg_dhu_curso_historial(in_user_name character varying, in_start_index integer, in_limit integer, in_sort_field_name character varying, in_direction character varying, in_find_text text)
  RETURNS SETOF refcursor AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT
		CU.CDCUR_CODIGO, 
		CU.CDTCR_CODIGO, 
		TC.CDTCR_NOMBRE,
		CU.CCTN_CODIGO, 
		CN.CCTN_NOMBRE, 
		ISL.CISLA_CODIGO,
		ISL.CISLA_NOMBRE,
		CU.CSCTP_CODIGO, 
		SP.CSCTP_NOMBRE,
		CU.CDITR_CODIGO,
        ITR.CDITR_NOMBRE,		
		CU.CRPER_CODIGO, 
		(SELECT PER.CRPER_NOMBRES||'' ''||PER.CRPER_APELLIDO_PATERNO||'' ''||PER.CRPER_APELLIDO_MATERNO FROM SII.CGG_RES_PERSONA PER WHERE PER.CRPER_CODIGO=CU.CRPER_CODIGO)AS CRPER_INSTRUCTOR,
		CU.CDCUR_DESCRIPCION, 
		CU.CDCUR_FECHA_PREVISTA_INICIO,
		CU.CDCUR_FECHA_INICIO, 
		CU.CDCUR_FECHA_CULMINACION, 
		CU.CDCUR_FECHA_PREVISTA_CULMINACION, 
		CU.CDCUR_HORARIO, 
		CU.CDCUR_HORARIO1,
		CU.CDCUR_NUMERO_HORAS_PEDAGOGICAS, 
		CU.CDCUR_NUMERO_HORAS, 
		CU.CDCUR_NUMERO_MODULOS, 
		CU.CDCUR_CONTENIDO, 
		CU.CDCUR_INSTITUCION, 
		CU.CDCUR_ESTABLECIMIENTO, 
		CU.CDCUR_COSTO, 
		CU.CDCUR_PORCENTAJE_FINANCIADO, 
		CU.CDCUR_OBSERVACION, 
		CU.CDCUR_VALORACION, 
		CU.CDCUR_ESTADO_CURSO, 
		CU.CDCUR_ESTADO, 
		CU.CDCUR_FECHA_INSERT, 
		CU.CDCUR_USUARIO_INSERT, 
		CU.CDCUR_FECHA_UPDATE, 
		CU.CDCUR_USUARIO_UPDATE
	FROM SII.CGG_DHU_CURSO CU
	INNER JOIN SII.CGG_CANTON CN ON (CN.CCTN_CODIGO=CU.CCTN_CODIGO)
	INNER JOIN SII.CGG_ISLA ISL ON(ISL.CCTN_CODIGO=ISL.CCTN_CODIGO)
	INNER JOIN SII.CGG_DHU_TIPO_CURSO TC ON(TC.CDTCR_CODIGO=CU.CDTCR_CODIGO)
	INNER JOIN SII.CGG_SECTOR_PRODUCTIVO SP ON(SP.CSCTP_CODIGO=CU.CSCTP_CODIGO)
	INNER JOIN SII.CGG_DHU_INSTITUCION_RESPONSABLE ITR ON(ITR.CDITR_CODIGO=CU.CDITR_CODIGO)
	INNER JOIN SII.CGG_RES_PERSONA PER ON(PER.CRPER_CODIGO=CU.CRPER_CODIGO)
	WHERE CDCUR_ESTADO = TRUE AND (CU.CDCUR_ESTADO_CURSO=1 OR CU.CDCUR_ESTADO_CURSO=2 OR CU.CDCUR_ESTADO_CURSO=3 OR CU.CDCUR_ESTADO_CURSO=4 ) AND  SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	COALESCE(TC.CDTCR_NOMBRE,'''')||'' ''||
	COALESCE(CN.CCTN_NOMBRE,'''')||'' ''||
	COALESCE(TC.CDTCR_NOMBRE,'''')||'' ''||
	COALESCE(SP.CSCTP_NOMBRE,'''')||'' ''||
	COALESCE(ITR.CDITR_NOMBRE,'''')||'' ''||
	COALESCE(CU.CDCUR_DESCRIPCION, '''')||'' ''||
	COALESCE(CU.CDCUR_FECHA_PREVISTA_INICIO,CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CU.CDCUR_FECHA_INICIO, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CU.CDCUR_FECHA_CULMINACION, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CU.CDCUR_FECHA_PREVISTA_CULMINACION,CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CU.CDCUR_HORARIO, '''')||'' ''||
	COALESCE(CU.CDCUR_HORARIO, '''')||'' ''||
	COALESCE(CU.CDCUR_NUMERO_HORAS_PEDAGOGICAS, 0)||'' ''||
	COALESCE(CU.CDCUR_NUMERO_HORAS, 0)||'' ''||
	COALESCE(CU.CDCUR_NUMERO_MODULOS, 0)||'' ''||
	COALESCE(CU.CDCUR_CONTENIDO, '''')||'' ''||
	COALESCE(CU.CDCUR_INSTITUCION, '''')||'' ''||
	COALESCE(CU.CDCUR_ESTABLECIMIENTO, '''')||'' ''||
	COALESCE(CU.CDCUR_COSTO, 0)||'' ''||
	COALESCE(CU.CDCUR_PORCENTAJE_FINANCIADO, 0)||'' ''||
	COALESCE(CU.CDCUR_OBSERVACION, '''')||'' ''||
	COALESCE(CU.CDCUR_VALORACION, 0)||'' ''||
	COALESCE(CU.CDCUR_ESTADO_CURSO, 0)||'' ''||
	COALESCE(CU.CDCUR_ESTADO, FALSE)||'' ''||
	COALESCE(CU.CDCUR_FECHA_INSERT, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CU.CDCUR_USUARIO_INSERT, '''')||'' ''||
	COALESCE(CU.CDCUR_FECHA_UPDATE, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CU.CDCUR_USUARIO_UPDATE, '''')) = 1
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100
  ROWS 1000;