/**
* FUNCION SII.F_CGG_DHU_CATEGORIA_PREGUNTA_PREGUNTA_RESPUESTA
* SELECCIONA TODOS LOS REGISTRO DE LA TABLA SII.CGG_DHU_PREGUNTA_RESPUESTA QUE ESTAN
* RELACIONADOS CON LA TABLA SII.CGG_DHU_CATEGORIA.
* @param IN_CDCAT_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE LA CATEGORIA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_DHU_CATEGORIA_PREGUNTA_PREGUNTA_RESPUESTA(
IN IN_CDCAT_CODIGO SII.CGG_DHU_PREGUNTA.CDCAT_CODIGO%TYPE
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT
		PR.CDPRG_CODIGO, 
		PR.CDCAT_CODIGO, 
		PR.CDPRG_DESCRIPCION, 
		PR.CDPRG_CUANTIFICABLE		
	FROM SII.CGG_DHU_PREGUNTA PR 
	INNER JOIN CGG_DHU_CATEGORIA CT ON (CT.CDCAT_CODIGO = PR.CDCAT_CODIGO)	
	LEFT JOIN CGG_DHU_PREGUNTA_RESPUESTA PRRS ON (PRRS.CDPRG_CODIGO = PR.CDPRG_CODIGO)
	WHERE CDPRG_ESTADO = TRUE AND 
		PR.CDCAT_CODIGO = IN_CDCAT_CODIGO;
	RETURN NEXT TMP_REF;
	END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;
	
	
/**
* FUNCION SII.F_CGG_DHU_RESPUESTA_PREGUNTA_RESPUESTA
* SELECCIONA TODOS LOS REGISTRO DE LA TABLA SII.CGG_DHU_PREGUNTA_RESPUESTA QUE ESTAN
* RELACIONADOS CON LA TABLA SII.CGG_DHU_RESPUESTA.
* @param IN_CDCAT_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE LA CATEGORIA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_DHU_RESPUESTA_PREGUNTA_RESPUESTA(
IN IN_CDPRG_CODIGO SII.CGG_DHU_PREGUNTA.CDPRG_CODIGO%TYPE
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT
		RS.CDRES_CODIGO, 
		RS.CDRES_DESCRIPCION, 		
		PRRS.CDPRS_VALORACION
	FROM SII.CGG_DHU_RESPUESTA RS	
	LEFT JOIN CGG_DHU_PREGUNTA_RESPUESTA PRRS ON (PRRS.CDRES_CODIGO = RS.CDRES_CODIGO AND PRRS.CDPRG_CODIGO = IN_CDPRG_CODIGO)
	WHERE RS.CDRES_ESTADO = TRUE ;
		
	RETURN NEXT TMP_REF;
	END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;


