/**
* FUNCION f_cgg_dhu_seguimiento_academico_estado_update
* ACTUALIZA UN REGISTRO EN LA TABLA SII.CGG_DHU_SEGUIMIENTO_ACADEMICO.
* @param in_cdacd_codigo IDENTIFICATIVO UNICO DE REGISTRO SEGUIMIENTO ACADEMICO
* @param IN_CDACD_ESTADO_APROBACION IDENTIFICATIVO UNICO DE REGISTRO 
0 - REGISTRADO
1 - REPROBADO
2 - POR APROBAR
3 - APROBADO
4 - CERTIFICADO
5 - OTROS
* @param IN_CDACD_USUARIO_UPDATE USUARIO QUE REALIZO LA ACTUALIZACION DE LA INFORMACION
* @return VOID
*/
CREATE OR REPLACE FUNCTION f_cgg_dhu_seguimiento_academico_estado_update(in_cdacd_codigo character varying, in_cdacd_estado_aprobacion smallint, in_cdacd_usuario_update character varying)
  RETURNS void AS
$BODY$
BEGIN
	UPDATE SII.CGG_DHU_SEGUIMIENTO_ACADEMICO SET		
		CDACD_ESTADO_APROBACION= IN_CDACD_ESTADO_APROBACION, 		
		CDACD_FECHA_UPDATE = CURRENT_TIMESTAMP, 
		CDACD_USUARIO_UPDATE = IN_CDACD_USUARIO_UPDATE
	WHERE
		CDACD_CODIGO = IN_CDACD_CODIGO;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100;