/**
* FUNCION SII.F_CGG_RES_PERSONA_EXPULSION_DESCRIPCION_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_MIEMBRO_COMITE.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC 
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_PERSONA_EXPULSION_DESCRIPCION_SELECT(
IN IN_USER_NAME VARCHAR,
IN IN_START_INDEX INT,
IN IN_LIMIT INT,
IN IN_SORT_FIELD_NAME VARCHAR,
IN IN_DIRECTION VARCHAR,
IN IN_FIND_TEXT TEXT
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT	
		PR.CRPER_CODIGO, 		 
		PR.CRDID_CODIGO, 
		(SELECT CRDID_DESCRIPCION FROM CGG_RES_DOCUMENTO_IDENTIFICACIO DI WHERE DI.CRDID_CODIGO= PR.CRDID_CODIGO) DOCUMENTO, 		
		PR.CPRR_CODIGO, 
		(SELECT CPRR_NOMBRE FROM CGG_PARROQUIA PA WHERE PA.CPRR_CODIGO= PR.CPRR_CODIGO) PARROQUIA, 
		PR.CCTN_CODIGO, 		
		(SELECT CCTN_NOMBRE FROM CGG_CANTON CT WHERE CT.CCTN_CODIGO= PR.CCTN_CODIGO) CANTON, 
		PR.CRPER_NOMBRES, 
		(SELECT PS.CRPER_APELLIDO_PATERNO||'' ''|| PS.CRPER_APELLIDO_MATERNO FROM SII.CGG_RES_PERSONA PS WHERE PS.CRPER_CODIGO = PR.CRPER_CODIGO) APELLIDO,
		PR.CRPER_NUM_DOC_IDENTIFIC, 
		PR.CRPER_FECHA_NACIMIENTO, 		
		PR.CRPER_GENERO,		
		FROM CGG_RES_PERSONA PR		
	INNER JOIN SII.CGG_RES_MOVILIDAD MV ON (MV.CRPER_CODIGO = PR.CRPER_CODIGO)	
	WHERE PR.CRPER_ESTADO = TRUE AND MV.CRMOV_ESTADO = TRUE AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	COALESCE(CRPER_NOMBRES, '''')||'' ''||	
	COALESCE(CRPER_NUM_DOC_IDENTIFIC, '''')||'' ''||
	COALESCE(CRPER_FECHA_NACIMIENTO, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRPER_GENERO, 0)) = 1
	AND  CRMOV_TIPO_SALIDA= ''1''
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_MIEMBRO_COMITE_DESCRIPCION_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_RES_MIEMBRO_COMITE.
* @param IN_CRCOM_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE COMITE
* @return INT
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_PERSONA_EXPULSION_DESCRIPCION_COUNT(
IN IN_CRCOM_CODIGO CHARACTER VARYING
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
		FROM CGG_RES_PERSONA PR		
	INNER JOIN SII.CGG_RES_MOVILIDAD MV ON (MV.CRPER_CODIGO = PR.CRPER_CODIGO)	
	WHERE PR.CRPER_ESTADO AND MV.CRMOV_ESTADO
	AND  CRMOV_TIPO_SALIDA= '1';
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_MIEMBRO_COMITE_DESCRIPCION_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_RES_MIEMBRO_COMITE.
* QUE CUMPLEN CON EL CRITERIO DE BUSQUEDA.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param IN_CRCOM_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE COMITE
* @return TOTAL DE REGISTROS
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_PERSONA_EXPULSION_DESCRIPCION_COUNT(
IN IN_FIND_TEXT TEXT,
IN IN_CRCOM_CODIGO CHARACTER VARYING
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS	
		FROM CGG_RES_PERSONA PR		
	INNER JOIN SII.CGG_RES_MOVILIDAD MV ON (MV.CRPER_CODIGO = PR.CRPER_CODIGO)	
	WHERE PR.CRPER_ESTADO = TRUE AND MV.CRMOV_ESTADO = TRUE AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	COALESCE(CRPER_NOMBRES, '''')||' '||	
	COALESCE(CRPER_NUM_DOC_IDENTIFIC, '''')||' '||
	COALESCE(CRPER_FECHA_NACIMIENTO, CURRENT_TIMESTAMP)||' '||
	COALESCE(CRPER_GENERO, 0)) = 1	
	AND CRMOV_TIPO_SALIDA= '1';
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;

