
/**
* FUNCION F_CGG_DHU_SADJUNTO_BECA
* SELECCIONA UN REGISTROS DE LA TABLA SII.CGG_DHU_SADJUNTO. 
* @param IN_CDADC_CODIGO CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/

CREATE OR REPLACE FUNCTION F_CGG_DHU_SADJUNTO_BECA(IN_CDACD_CODIGO CHARACTER VARYING)
  RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT
		CDSAD_CODIGO, 
		CDACD_CODIGO, 
		CDSAD_FECHA_REGISTRO, 
		CDSAD_NOMBRE_ADJUNTO, 
		--CDSAD_ADJUNTO, 
		CDSAD_OBSERVACION, 
		CDSAD_ESTADO, 
		CDSAD_FECHA_INSERT, 
		CDSAD_USUARIO_INSERT, 
		CDSAD_FECHA_UPDATE, 
		CDSAD_USUARIO_UPDATE
	FROM SII.CGG_DHU_SADJUNTO
	WHERE CDSAD_ESTADO = TRUE AND CDBCR_CODIGO IS NULL AND 
		CDACD_CODIGO = IN_CDACD_CODIGO;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100
  ROWS 1000;