/**
*SELECCION UNA PERSONA POR SU NUMERO DE DOCUMENTO.
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_PERSONA_CAPACITACION(
	IN IN_CRPER_NUM_DOC_IDENTIFIC VARCHAR	
)
  RETURNS TEXT AS
$BODY$
DECLARE
	TMP_NOMBRES TEXT;
BEGIN
	
	TMP_NOMBRES:='';
	SELECT CRPER_NOMBRES||' '||CRPER_APELLIDO_PATERNO||COALESCE(CRPER_APELLIDO_MATERNO,' ') INTO TMP_NOMBRES CRPER_NOMBRE_COMPLETO 
	FROM SII.CGG_RES_PERSONA 
	WHERE CRPER_NUM_DOC_IDENTIFIC = IN_CRPER_NUM_DOC_IDENTIFIC;
	
	RETURN TMP_NOMBRES;
		
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100
  ROWS 1000;
