/**FUNCTION: f_cgg_res_notificacion_no_residencia_select(TEXT)
* CONTABILIZA N REGISTROS DE LA TABLA SII.CGG_RES_PERSONA SOLO RESIDENTES PERMANENTES.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TMP_ROWS
*/
CREATE OR REPLACE FUNCTION f_cgg_res_notificacion_no_residencia_select(in_find_text text)
  RETURNS integer AS
$BODY$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_RES_MOVILIDAD MV						
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = MV.CRPER_CODIGO)	
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON (RS.CRPER_CODIGO = PR.CRPER_CODIGO)	
	LEFT JOIN SII.CGG_RES_DOCUMENTO_IDENTIFICACIO DI ON(DI.CRDID_CODIGO=PR.CRDID_CODIGO)
	LEFT JOIN CGG_NACIONALIDAD NC ON (NC.CGNCN_CODIGO = PR.CGNCN_CODIGO)
	LEFT JOIN CGG_RES_AEROPUERTO AR ON (AR.CARPT_CODIGO = MV.CGG_CARPT_CODIGO)
	WHERE CRMOV_ESTADO = TRUE AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	CASE WHEN PR.CRPER_CODIGO IS NULL THEN '''' ELSE PR.CRPER_CODIGO END ||' '||
	CASE WHEN PR.CRDID_CODIGO IS NULL THEN '''' ELSE PR.CRDID_CODIGO END ||' '||
	CASE WHEN DI.CRDID_DESCRIPCION IS NULL THEN '''' ELSE DI.CRDID_DESCRIPCION END ||''||
	CASE WHEN PR.CRPER_NUM_DOC_IDENTIFIC IS NULL THEN '''' ELSE PR.CRPER_NUM_DOC_IDENTIFIC END ||' '||
	CASE WHEN PR.CRPER_NUMERO_RESIDENCIA IS NULL THEN '''' ELSE PR.CRPER_NUMERO_RESIDENCIA END ||' '||
	CASE WHEN PR.CRPER_NOMBRES IS NULL THEN '''' ELSE PR.CRPER_NOMBRES END ||' '||
	CASE WHEN PR.CRPER_APELLIDO_PATERNO IS NULL THEN '''' ELSE PR.CRPER_APELLIDO_PATERNO END ||' '||
	CASE WHEN PR.CRPER_GENERO IS NULL THEN 0 ELSE PR.CRPER_GENERO END ||' '||
	CASE WHEN PR.CGNCN_CODIGO IS NULL THEN '''' ELSE PR.CGNCN_CODIGO END ||' '||
	CASE WHEN NC.CGNCN_NACIONALIDAD IS NULL THEN '''' ELSE NC.CGNCN_NACIONALIDAD END ||' '||
	CASE WHEN MV.CRMOV_FECHA_VIAJE IS NULL THEN CURRENT_TIMESTAMP ELSE MV.CRMOV_FECHA_VIAJE END ||' '||
	CASE WHEN MV.CRMOV_TIPO_OPERACION IS NULL THEN 0 ELSE MV.CRMOV_TIPO_OPERACION END ) = 1
	AND RS.CRRSD_VIGENTE = TRUE
	AND RS.CRTST_CODIGO IN 
(WITH RECURSIVE TIPO(CRTST_CODIGO, CGG_CRTST_CODIGO, CRTST_DESCRIPCION)AS(
	SELECT CRTST_CODIGO, CGG_CRTST_CODIGO, CRTST_DESCRIPCION FROM CGG_RES_TIPO_SOLICITUD_TRAMITE WHERE (CRTST_CODIGO = (SELECT CGCNF_VALOR_CADENA
FROM CGG_CONFIGURACION
WHERE CGCNF_CODIGO = '05') OR CRTST_CODIGO = (SELECT CGCNF_VALOR_CADENA
FROM CGG_CONFIGURACION
WHERE CGCNF_CODIGO = '06'))  AND CRTPT_CODIGO = 'CRTPT1'
	UNION SELECT TST.CRTST_CODIGO, TST.CGG_CRTST_CODIGO, TP.CRTST_DESCRIPCION FROM CGG_RES_TIPO_SOLICITUD_TRAMITE TST, TIPO TP
	WHERE TST.CGG_CRTST_CODIGO = TP.CRTST_CODIGO
) SELECT CRTST_CODIGO  FROM TIPO)
AND MV.CRMOV_FECHA_VIAJE= (SELECT MVL.CRMOV_FECHA_VIAJE FROM CGG_RES_MOVILIDAD MVL INNER JOIN CGG_RES_PERSONA PRS ON (MVL.CRPER_CODIGO = PRS.CRPER_CODIGO) WHERE PRS.CRPER_CODIGO= PR.CRPER_CODIGO ORDER BY MV.CRMOV_FECHA_VIAJE DESC LIMIT 1 ); 	
	RETURN TMP_ROWS;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100;
ALTER FUNCTION f_cgg_res_notificacion_no_residencia_select(text) OWNER TO sii;
