/**
* FUNCION F_CGG_RES_MOVILIDAD_INTERNA_SELECT_DATOS
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_MOVILIDAD_INTERNA.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_MOVILIDAD_INTERNA_SELECT_DATOS(IN_USER_NAME CHARACTER VARYING, 
IN_START_INDEX INTEGER,
IN_LIMIT INTEGER, 
IN_SORT_FIELD_NAME CHARACTER VARYING,
IN_DIRECTION CHARACTER VARYING,
IN_FIND_TEXT TEXT)
  RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT
		MVI.CRMVI_CODIGO, 
		MVI.CRMLE_CODIGO, 
		(SELECT CRMLE_NOMBRE FROM SII.CGG_RES_MUELLE MLE WHERE MLE.CRMLE_CODIGO=MVI.CRMLE_CODIGO) CRMLE_NOMBRE,
		MVI.CGG_CRMLE_CODIGO, 
		(SELECT MLE.CRMLE_NOMBRE FROM SII.CGG_RES_MUELLE MLE WHERE MLE.CRMLE_CODIGO=MVI.CGG_CRMLE_CODIGO) CGG_CRMLE_NOMBRE,
		MVI.CREMB_CODIGO, 
		(SELECT EMB.CREMB_NOMBRE FROM SII.CGG_RES_EMBARCACION EMB WHERE EMB.CREMB_CODIGO=MVI.CREMB_CODIGO) CREMB_NOMBRE,
		MVI.CRPER_CODIGO, 
		(PER.CRPER_NOMBRES||'' ''||PER.CRPER_APELLIDO_PATERNO||'' ''||PER.CRPER_APELLIDO_MATERNO) CRPER_NOMBRE,
		PER.CRPER_NUM_DOC_IDENTIFIC,
		PER.CRPER_NUMERO_RESIDENCIA,
		CRMOV_CODIGO, 
		MVI.CARPT_CODIGO, 
		(SELECT AER.CARPT_NOMBRE FROM SII.CGG_RES_AEROPUERTO AER WHERE AER.CARPT_CODIGO=MVI.CARPT_CODIGO) CARPT_NOMBRE,
		MVI.CGG_CARPT_CODIGO,
		(SELECT AER.CARPT_NOMBRE FROM SII.CGG_RES_AEROPUERTO AER WHERE AER.CARPT_CODIGO=MVI.CGG_CARPT_CODIGO) CARPT_NOMBRE_DESTINO,
		MVI.CRALN_CODIGO, 
		(SELECT ALN.CRALN_NOMBRE FROM SII.CGG_RES_AEROLINEA ALN WHERE ALN.CRALN_CODIGO=MVI.CRALN_CODIGO) CRALN_NOMBRE,
		MVI.CRALN_DESCRIPCION_VUELO, 
		MVI.CRMVI_FECHA_VIAJE, 
		MVI.CRMVI_TIPO_OPERACION, 
		MVI.CRMVI_OBSERVACION, 
		MVI.CRMVI_ESTADO, 
		MVI.CRMVI_FECHA_INSERT, 
		MVI.CRMVI_USUARIO_INSERT, 
		MVI.CRMVI_FECHA_UPDATE, 
		MVI.CRMVI_USUARIO_UPDATE
	FROM SII.CGG_RES_MOVILIDAD_INTERNA MVI
	INNER JOIN SII.CGG_RES_PERSONA PER ON(PER.CRPER_CODIGO=MVI.CRPER_CODIGO)
	WHERE MVI.CRMVI_ESTADO = TRUE AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	COALESCE(PER.CRPER_NOMBRES,'''')||'' ''||
	COALESCE(PER.CRPER_APELLIDO_PATERNO,'''')||'' ''||
	COALESCE(PER.CRPER_APELLIDO_MATERNO,'''')||'' ''||
	COALESCE(PER.CRPER_NUM_DOC_IDENTIFIC,'''')||'' ''||
	COALESCE(PER.CRPER_NUMERO_RESIDENCIA,'''')||'' ''||
	COALESCE(CRALN_DESCRIPCION_VUELO, '''')||'' ''||
	COALESCE(CRMVI_FECHA_VIAJE, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRMVI_TIPO_OPERACION, 0)||'' ''||
	COALESCE(CRMVI_OBSERVACION, '''')||'' ''||
	COALESCE(CRMVI_ESTADO, FALSE)||'' ''||
	COALESCE(CRMVI_FECHA_INSERT, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRMVI_USUARIO_INSERT, '''')||'' ''||
	COALESCE(CRMVI_FECHA_UPDATE, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRMVI_USUARIO_UPDATE, '''')) = 1
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100
  ROWS 1000;

/**
* FUNCION F_CGG_TCT_MOVILIDAD_INTERNA_SELECT_DOCUMENTO_IDENTIFIC_GENERAL
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_MOVILIDAD_INTERNA.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param IN_CRPER_NUMERO_IDENTIFICACION NUMERO DE DOCUMENTO IDENTIFICATIVO DE LA PERSONA
* @return REFCURSOR
*/

CREATE OR REPLACE FUNCTION SII.F_CGG_TCT_MOVILIDAD_INTERNA_SELECT_DOCUMENTO_IDENTIFIC_GENERAL(
IN IN_USER_NAME CHARACTER VARYING, 
IN IN_START_INDEX INTEGER, 
IN IN_LIMIT INTEGER, 
IN IN_SORT_FIELD_NAME CHARACTER VARYING, 
IN IN_DIRECTION CHARACTER VARYING, 
IN IN_FIND_TEXT TEXT,
IN IN_CRPER_NUMERO_IDENTIFICACION VARCHAR
)RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT
		MV.CRMOV_CODIGO,
		PR.CRPER_CODIGO,
		PR.CRDID_CODIGO,
		MV.CRMOV_TIPO_OPERACION,
		(SELECT CRDID_DESCRIPCION FROM SII.CGG_RES_DOCUMENTO_IDENTIFICACIO DI WHERE DI.CRDID_CODIGO = PR.CRDID_CODIGO) CRPER_TIPO_DOCUMENTO,
		PR.CRPER_NUM_DOC_IDENTIFIC,
		PR.CRPER_NUMERO_RESIDENCIA,
		PR.CRPER_NOMBRES,
		PR.CRPER_APELLIDO_PATERNO,
		PR.CRPER_APELLIDO_MATERNO,
		PR.CRPER_GENERO,
		PR.CRPER_FECHA_NACIMIENTO,
		PR.CGNCN_CODIGO,		
		(SELECT CGNCN_NACIONALIDAD FROM SII.CGG_NACIONALIDAD NC WHERE NC.CGNCN_CODIGO = PR.CGNCN_CODIGO) CRPER_NACIONALIDAD,
		(SELECT MAX(MV.CRMOV_FECHA_VIAJE) FROM SII.CGG_RES_MOVILIDAD MV WHERE MV.CRPER_CODIGO=PR.CRPER_CODIGO )AS CRMOV_FECHA_VIAJE ,
		(SELECT DISTINCT MV.CRMOV_TIPO_OPERACION FROM SII.CGG_RES_MOVILIDAD MV WHERE MV.CRPER_CODIGO=PR.CRPER_CODIGO
		AND MV.CRMOV_FECHA_VIAJE = (SELECT  MAX(MV.CRMOV_FECHA_VIAJE) FROM SII.CGG_RES_MOVILIDAD MV
		WHERE MV.CRPER_CODIGO=PR.CRPER_CODIGO) ) AS TIPO_OP,						
		(SELECT MAX(MVI.CRMVI_FECHA_VIAJE) FROM SII.CGG_RES_MOVILIDAD_INTERNA MVI WHERE MVI.CRPER_CODIGO=PR.CRPER_CODIGO )AS CRMVI_FECHA_VIAJE ,
		(SELECT CGCNF_CONFIGURACION
			FROM CGG_CONFIGURACION C
			WHERE CGCNF_VALOR_CADENA = (SELECT ST.CRTST_CODIGO FROM CGG_RES_TIPO_SOLICITUD_TRAMITE ST
			INNER JOIN CGG_RES_RESIDENCIA RS ON (RS.CRTST_CODIGO = ST.CRTST_CODIGO)
			 WHERE RS.CRRSD_VIGENTE = TRUE AND RS.CRPER_CODIGO=PR.CRPER_CODIGO)OR CGCNF_VALOR_CADENA = (SELECT ST.CGG_CRTST_CODIGO FROM CGG_RES_TIPO_SOLICITUD_TRAMITE ST
			INNER JOIN CGG_RES_RESIDENCIA RS ON (RS.CRTST_CODIGO = ST.CRTST_CODIGO)
			 WHERE RS.CRRSD_VIGENTE = TRUE AND RS.CRPER_CODIGO=PR.CRPER_CODIGO))TIPO_RESIDENCIA,
		MVI.CRMVI_TIPO_OPERACION
		
	FROM SII.CGG_RES_MOVILIDAD MV
	INNER JOIN SII.CGG_TCT_REGISTRO RG ON(RG.CTREG_CODIGO=MV.CTREG_CODIGO)					
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = MV.CRPER_CODIGO)	
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON RS.CRPER_CODIGO = PR.CRPER_CODIGO AND RS.CRRSD_VIGENTE AND RS.CRRSD_ESTADO AND RS.CRTST_CODIGO IN 
		(WITH RECURSIVE TIPO(CRTST_CODIGO, CGG_CRTST_CODIGO, CRTST_DESCRIPCION)AS(
			SELECT CRTST_CODIGO, CGG_CRTST_CODIGO, CRTST_DESCRIPCION FROM CGG_RES_TIPO_SOLICITUD_TRAMITE WHERE (CRTST_CODIGO = (SELECT CGCNF_VALOR_CADENA
			FROM CGG_CONFIGURACION
			WHERE CGCNF_CODIGO = ''05'') OR CRTST_CODIGO = (SELECT CGCNF_VALOR_CADENA
			FROM CGG_CONFIGURACION
			WHERE CGCNF_CODIGO = ''06'')) 
			UNION SELECT TST.CRTST_CODIGO, TST.CGG_CRTST_CODIGO, TP.CRTST_DESCRIPCION FROM CGG_RES_TIPO_SOLICITUD_TRAMITE TST, TIPO TP
			WHERE TST.CGG_CRTST_CODIGO = TP.CRTST_CODIGO
		) SELECT CRTST_CODIGO  FROM TIPO)	
	LEFT JOIN SII.CGG_RES_MOVILIDAD MVS ON MVS.CTREG_CODIGO = RG.CTREG_CODIGO AND MVS.CRMOV_TIPO_OPERACION = 1 AND MVS.CRMOV_ESTADO AND MVS.CRPER_CODIGO = PR.CRPER_CODIGO
	LEFT JOIN SII.CGG_RES_MOVILIDAD_INTERNA MVI ON (MVI.CRPER_CODIGO = PR.CRPER_CODIGO AND MVI.CRMVI_TIPO_OPERACION=0)	
	WHERE MV.CRMOV_ESTADO AND (LENGTH('||QUOTE_LITERAL(IN_FIND_TEXT)||') = 0 OR SII.F_STRING_IN('||QUOTE_LITERAL(IN_FIND_TEXT)||',
		COALESCE(PR.CRPER_NOMBRES,'''')||'' ''||
		COALESCE(PR.CRPER_APELLIDO_PATERNO,'''')||'' ''||
		COALESCE(PR.CRPER_APELLIDO_MATERNO,'''')
		) = 1) AND
		MV.CRMOV_TIPO_OPERACION = 0 AND 
		MVS.CRMOV_CODIGO IS NULL AND
		MV.CRPER_CODIGO=PR.CRPER_CODIGO AND
		(LENGTH('||QUOTE_LITERAL(IN_CRPER_NUMERO_IDENTIFICACION)||') = 0 OR PR.CRPER_NUM_DOC_IDENTIFIC = '||QUOTE_LITERAL(IN_CRPER_NUMERO_IDENTIFICACION)||')
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
	RETURN NEXT TMP_REF;
END
$BODY$
LANGUAGE 'PLPGSQL' VOLATILE COST 100 ROWS 1000;

/** FUNCTION: F_CGG_TCT_MOVILIDAD_INTERNA_SELECT_DOCUMENTO_IDENTIFIC_GENERAL_COUNT
* CONTABILIZA N REGISTROS DE LA TABLA SII.CGG_MOVILIDAD_INTERNA.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param IN_CRPER_NUMERO_IDENTIFICACION NUMERO DE DOCUMENTO IDENTIFICATIVO DE LA PERSONA
* @return TMP_ROWS
*/

CREATE OR REPLACE FUNCTION SII.F_CGG_TCT_MOVILIDAD_INTERNA_SELECT_DOCUMENTO_IDENTIFIC_GENERAL_COUNT(
IN IN_FIND_TEXT TEXT,
IN IN_CRPER_NUMERO_IDENTIFICACION VARCHAR
)RETURNS INTEGER AS
$BODY$
DECLARE
TMP_ROWS INT;
BEGIN
	SELECT COUNT(MVS.CRMOV_CODIGO) INTO TMP_ROWS
	FROM SII.CGG_RES_MOVILIDAD MV
	INNER JOIN SII.CGG_TCT_REGISTRO RG ON(RG.CTREG_CODIGO=MV.CTREG_CODIGO)					
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = MV.CRPER_CODIGO)	
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON RS.CRPER_CODIGO = PR.CRPER_CODIGO AND RS.CRRSD_VIGENTE AND RS.CRRSD_ESTADO AND RS.CRTST_CODIGO IN 
		(WITH RECURSIVE TIPO(CRTST_CODIGO, CGG_CRTST_CODIGO, CRTST_DESCRIPCION)AS(
			SELECT CRTST_CODIGO, CGG_CRTST_CODIGO, CRTST_DESCRIPCION FROM CGG_RES_TIPO_SOLICITUD_TRAMITE WHERE (CRTST_CODIGO = (SELECT CGCNF_VALOR_CADENA
			FROM CGG_CONFIGURACION
			WHERE CGCNF_CODIGO = '05') OR CRTST_CODIGO = (SELECT CGCNF_VALOR_CADENA
			FROM CGG_CONFIGURACION
			WHERE CGCNF_CODIGO = '06')) 
			UNION SELECT TST.CRTST_CODIGO, TST.CGG_CRTST_CODIGO, TP.CRTST_DESCRIPCION FROM CGG_RES_TIPO_SOLICITUD_TRAMITE TST, TIPO TP
			WHERE TST.CGG_CRTST_CODIGO = TP.CRTST_CODIGO
		) SELECT CRTST_CODIGO  FROM TIPO)	
	LEFT JOIN SII.CGG_RES_MOVILIDAD MVS ON MVS.CTREG_CODIGO = RG.CTREG_CODIGO AND MVS.CRMOV_TIPO_OPERACION = 1 AND MVS.CRMOV_ESTADO AND MVS.CRPER_CODIGO = PR.CRPER_CODIGO
	LEFT JOIN SII.CGG_RES_MOVILIDAD_INTERNA MVI ON (MVI.CRPER_CODIGO = PR.CRPER_CODIGO AND MVI.CRMVI_TIPO_OPERACION=0)	
	WHERE MV.CRMOV_ESTADO AND (LENGTH(IN_FIND_TEXT) = 0 OR SII.F_STRING_IN(IN_FIND_TEXT,
		COALESCE(PR.CRPER_NOMBRES,'')||' '||
		COALESCE(PR.CRPER_APELLIDO_PATERNO,'')||' '||
		COALESCE(PR.CRPER_APELLIDO_MATERNO,'')
		) = 1) AND
		MV.CRMOV_TIPO_OPERACION = 0 AND 
		MVS.CRMOV_CODIGO IS NULL AND
		MV.CRPER_CODIGO=PR.CRPER_CODIGO AND
		(LENGTH(IN_CRPER_NUMERO_IDENTIFICACION) = 0 OR PR.CRPER_NUM_DOC_IDENTIFIC = IN_CRPER_NUMERO_IDENTIFICACION);
	RETURN TMP_ROWS;
END
$BODY$
LANGUAGE 'PLPGSQL' VOLATILE COST 100;
/**
* FUNCION F_CGG_TCT_MOVILIDAD_INTERNA_INGRESO
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_MOVILIDAD_INTERNA QUE INGRESARON ENTRE ISLAS.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC 
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA.
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_TCT_MOVILIDAD_INTERNA_INGRESO(
IN IN_USER_NAME CHARACTER VARYING, 
IN IN_START_INDEX INTEGER, 
IN IN_LIMIT INTEGER, 
IN IN_SORT_FIELD_NAME CHARACTER VARYING, 
IN IN_DIRECTION CHARACTER VARYING, 
IN IN_FIND_TEXT TEXT
)RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT 
		DISTINCT MVI.CRMVI_CODIGO,
		PR.CRPER_CODIGO,
	        PR.CRDID_CODIGO,
		(SELECT CRDID_DESCRIPCION FROM  CGG_RES_DOCUMENTO_IDENTIFICACIO DI WHERE DI.CRDID_CODIGO = PR.CRDID_CODIGO) CRPER_TIPO_DOCUMENTO,
		PR.CRPER_NUM_DOC_IDENTIFIC,
		PR.CRPER_NUMERO_RESIDENCIA,
		PR.CRPER_NOMBRES,
		PR.CRPER_APELLIDO_PATERNO,
		PR.CRPER_APELLIDO_MATERNO,
		PR.CRPER_GENERO,
		PR.CRPER_FECHA_NACIMIENTO,
		PR.CGNCN_CODIGO,		
		(SELECT CGNCN_NACIONALIDAD FROM  CGG_NACIONALIDAD NC WHERE NC.CGNCN_CODIGO = PR.CGNCN_CODIGO) CRPER_NACIONALIDAD,							
		(SELECT MAX(MV.CRMOV_FECHA_VIAJE) FROM SII.CGG_RES_MOVILIDAD MV WHERE MV.CRPER_CODIGO=PR.CRPER_CODIGO )AS CRMOV_FECHA_VIAJE ,
		(SELECT DISTINCT MV.CRMOV_TIPO_OPERACION FROM SII.CGG_RES_MOVILIDAD MV WHERE MV.CRPER_CODIGO=PR.CRPER_CODIGO
		AND MV.CRMOV_FECHA_VIAJE = (SELECT  MAX(MV.CRMOV_FECHA_VIAJE) FROM SII.CGG_RES_MOVILIDAD MV
		WHERE MV.CRPER_CODIGO=PR.CRPER_CODIGO) ) AS TIPO_OP,
		(SELECT MAX(MVI.CRMVI_FECHA_VIAJE) FROM SII.CGG_RES_MOVILIDAD_INTERNA MVI WHERE MVI.CRPER_CODIGO=PR.CRPER_CODIGO )AS CRMVI_FECHA_VIAJE ,
		MVI.CRMVI_TIPO_OPERACION,
		(SELECT CGCNF_CONFIGURACION
		FROM CGG_CONFIGURACION C
		WHERE CGCNF_VALOR_CADENA = (SELECT ST.CRTST_CODIGO FROM CGG_RES_TIPO_SOLICITUD_TRAMITE ST
		INNER JOIN CGG_RES_RESIDENCIA RS ON (RS.CRTST_CODIGO = ST.CRTST_CODIGO)
		 WHERE RS.CRRSD_VIGENTE = TRUE AND RS.CRPER_CODIGO=PR.CRPER_CODIGO)OR CGCNF_VALOR_CADENA = (SELECT ST.CGG_CRTST_CODIGO FROM CGG_RES_TIPO_SOLICITUD_TRAMITE ST
		INNER JOIN CGG_RES_RESIDENCIA RS ON (RS.CRTST_CODIGO = ST.CRTST_CODIGO)
		 WHERE RS.CRRSD_VIGENTE = TRUE AND RS.CRPER_CODIGO=PR.CRPER_CODIGO))TIPO_RESIDENCIA,
		MVI.CRMLE_CODIGO, 
		(SELECT CRMLE_NOMBRE FROM SII.CGG_RES_MUELLE MLE WHERE MLE.CRMLE_CODIGO=MVI.CRMLE_CODIGO) CRMLE_NOMBRE,
		MVI.CGG_CRMLE_CODIGO, 
		(SELECT MLE.CRMLE_NOMBRE FROM SII.CGG_RES_MUELLE MLE WHERE MLE.CRMLE_CODIGO=MVI.CGG_CRMLE_CODIGO) CGG_CRMLE_NOMBRE,
		MVI.CREMB_CODIGO, 
		(SELECT EMB.CREMB_NOMBRE FROM SII.CGG_RES_EMBARCACION EMB WHERE EMB.CREMB_CODIGO=MVI.CREMB_CODIGO) CREMB_NOMBRE,
		MVI.CARPT_CODIGO, 
		(SELECT AER.CARPT_NOMBRE FROM SII.CGG_RES_AEROPUERTO AER WHERE AER.CARPT_CODIGO=MVI.CARPT_CODIGO) CARPT_NOMBRE,
		MVI.CGG_CARPT_CODIGO,
		(SELECT AER.CARPT_NOMBRE FROM SII.CGG_RES_AEROPUERTO AER WHERE AER.CARPT_CODIGO=MVI.CGG_CARPT_CODIGO) CARPT_NOMBRE_DESTINO,
		MVI.CRALN_CODIGO, 
		(SELECT ALN.CRALN_NOMBRE FROM SII.CGG_RES_AEROLINEA ALN WHERE ALN.CRALN_CODIGO=MVI.CRALN_CODIGO) CRALN_NOMBRE,
		MVI.CRALN_DESCRIPCION_VUELO
	FROM SII.CGG_RES_MOVILIDAD_INTERNA MVI
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = MVI.CRPER_CODIGO)
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON (RS.CRPER_CODIGO = PR.CRPER_CODIGO)
	INNER JOIN  SII.CGG_RES_MOVILIDAD MV ON (MV.CRPER_CODIGO = PR.CRPER_CODIGO)
	INNER JOIN SII.CGG_TCT_REGISTRO RG ON(RG.CTREG_CODIGO=MV.CTREG_CODIGO)	
	WHERE  CRMVI_ESTADO=TRUE AND RS.CRRSD_VIGENTE = TRUE AND MVI.CRMVI_TIPO_OPERACION = 0 AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	COALESCE(PR.CRPER_NUM_DOC_IDENTIFIC,'''')||'' ''||
	COALESCE(PR.CRPER_NUMERO_RESIDENCIA,'''')||'' ''||
	COALESCE(PR.CRPER_NOMBRES,'''')||'' ''||
	COALESCE(PR.CRPER_APELLIDO_PATERNO,'''')||'' ''||
	COALESCE(PR.CRPER_APELLIDO_MATERNO,'''')||'' ''||
	COALESCE(CRALN_DESCRIPCION_VUELO, '''')||'' ''||
	COALESCE(CRMVI_FECHA_VIAJE, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRMVI_TIPO_OPERACION, 0)||'' ''||
	COALESCE(CRMVI_OBSERVACION, '''')||'' ''||
	COALESCE(CRMVI_ESTADO, FALSE)) = 1
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
		RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100
  ROWS 1000;

/** FUNCTION: F_CGG_TCT_MOVILIDAD_INTERNA_INGRESO_COUNT
* CONTABILIZA N REGISTROS DE LA TABLA SII.CGG_RES_MOVILIDAD_INTERNA
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TMP_ROWS
*/


CREATE OR REPLACE FUNCTION SII.F_CGG_TCT_MOVILIDAD_INTERNA_INGRESO_COUNT(IN_FIND_TEXT TEXT)
  RETURNS INTEGER AS
$BODY$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_RES_MOVILIDAD_INTERNA MVI
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = MVI.CRPER_CODIGO)
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON (RS.CRPER_CODIGO = PR.CRPER_CODIGO)
	INNER JOIN  SII.CGG_RES_MOVILIDAD MV ON (MV.CRPER_CODIGO = PR.CRPER_CODIGO)
	INNER JOIN SII.CGG_TCT_REGISTRO RG ON(RG.CTREG_CODIGO=MV.CTREG_CODIGO)	
	WHERE  CRMVI_ESTADO=TRUE AND RS.CRRSD_VIGENTE = TRUE AND MVI.CRMVI_TIPO_OPERACION = 0 AND (LENGTH(IN_FIND_TEXT) = 0 OR SII.F_STRING_IN(IN_FIND_TEXT,
	COALESCE(PR.CRPER_NUM_DOC_IDENTIFIC,'''')||' '||
	COALESCE(PR.CRPER_NUMERO_RESIDENCIA,'''')||' '||
	COALESCE(PR.CRPER_NOMBRES,'''')||' '||
	COALESCE(PR.CRPER_APELLIDO_PATERNO,'''')||' '||
	COALESCE(PR.CRPER_APELLIDO_MATERNO,'''')||' '||
	COALESCE(CRALN_DESCRIPCION_VUELO, '''')||' '||
	COALESCE(CRMVI_FECHA_VIAJE, CURRENT_TIMESTAMP)||' '||
	COALESCE(CRMVI_TIPO_OPERACION, 0)||' '||
	COALESCE(CRMVI_OBSERVACION, '''')||' '||
	COALESCE(CRMVI_ESTADO, FALSE)) = 1);
	RETURN TMP_ROWS;
END
$BODY$
LANGUAGE 'PLPGSQL' VOLATILE COST 100;


/** FUNCTION:SII.F_CGG_TCT_REGISTRO_HOSPEDAJE_INTERNO
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_TCT_REGISTRO_ACTIVIDAD_INTERNA.
* @param INCRMVI_CODIGO CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_TCT_REGISTRO_HOSPEDAJE_INTERNO(
IN IN_CRMVI_CODIGO character varying
)RETURNS SETOF refcursor AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT
		TH.CTTHJ_CODIGO, 
		TH.CTTHJ_NOMBRE		
	FROM SII.CGG_TCT_TIPO_HOSPEDAJE TH
	INNER JOIN SII.CGG_TCT_MOVILIDAD_INT_HOSPEDAJE MIH ON (MIH.CTTHJ_CODIGO = TH.CTTHJ_CODIGO)
	INNER JOIN SII.CGG_RES_MOVILIDAD_INTERNA MVI ON (MVI.CRMVI_CODIGO = MIH.CRMVI_CODIGO)
	WHERE CTTHJ_ESTADO AND 
		MVI.CRMVI_CODIGO = IN_CRMVI_CODIGO;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100
  ROWS 1000;

/**FUNCTION: F_CGG_TCT_REGISTRO_ACTIVIDAD_INTERNA
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_TCT_REGISTRO_ACTIVIDAD_INTERNA.
* @param INCRMVI_CODIGO CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_TCT_REGISTRO_ACTIVIDAD_INTERNA(INCRMVI_CODIGO CHARACTER VARYING)
  RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT
		MIA.CTACT_CODIGO, 
		AC.CTACT_NOMBRE		
	FROM SII.CGG_TCT_MOVILIDAD_INT_ACTIVIDAD MIA
	INNER JOIN SII.CGG_TCT_ACTIVIDAD AC ON (MIA.CTACT_CODIGO = AC.CTACT_CODIGO)
	INNER JOIN SII.CGG_RES_MOVILIDAD_INTERNA MVI ON (MVI.CRMVI_CODIGO = MIA.CRMVI_CODIGO)	
	WHERE CTACT_ESTADO = TRUE 	
	AND MVI.CRMVI_CODIGO = INCRMVI_CODIGO;
	
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100
  ROWS 1000;

