/**
*FUNCTION: F_CGG_DHU_BECA_SEGUIMIENTO_ACADEMICO_SELECT_COUNT(TEXT)
* CONTABILIZA N REGISTROS DE LA TABLA SII.CGG_DHU_SEGUIMIENTO_ACADEMICO.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TMP_ROWS
*/
-- DROP FUNCTION F_CGG_DHU_BECA_SEGUIMIENTO_ACADEMICO_SELECT_COUNT(TEXT);

CREATE OR REPLACE FUNCTION F_CGG_DHU_BECA_SEGUIMIENTO_ACADEMICO_SELECT_COUNT(IN_FIND_TEXT TEXT)
  RETURNS INTEGER AS
$BODY$
DECLARE
	TMP_ROWS INT2;
BEGIN
	
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_DHU_BECA
	INNER JOIN SII.CGG_RES_PERSONA PER ON (PER.CRPER_CODIGO=BEC.CRPER_CODIGO)
	WHERE BEC.CDBEC_ESTADO = TRUE AND CDBEC_ESTADO_APROBACION=1 AND SII.F_STRING_IN(IN_FIND_TEXT,
	COALESCE(CDBEC_FUNCIONARIO, '''')||' '||
	COALESCE(CDBEC_TOTAL_CICLOS, 0)||' '||
	COALESCE(CDBEC_ESTADO_APROBACION, 0)||' '||
	COALESCE(CDBEC_ESTADO, FALSE)||' '||
	COALESCE(CDBEC_FECHA_INSERT, CURRENT_TIMESTAMP)||' '||
	COALESCE(CDBEC_USUARIO_INSERT, '''')||' '||
	COALESCE(CDBEC_FECHA_UPDATE, CURRENT_TIMESTAMP)||' '||
	COALESCE(CDBEC_USUARIO_UPDATE, '''')) = 1;
	RETURN TMP_ROWS;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;
ALTER FUNCTION F_CGG_DHU_BECA_SEGUIMIENTO_ACADEMICO_SELECT_COUNT(TEXT) OWNER TO SII;
