
/** FUNCION F_CGG_TCT_MOVILIDAD_INTERNA_SELECT_DOCUMENTO_IDENTIFIC_INGRESO
* SELECCIONA UN REGISTRO DE INGRESO ENTRE ISLAS DE UNA PERSONA DE ACUERDO AL PARAMETRO DE BUSQUEDA NUMERO DE DOCUMENTO.
* @param IN_CRPER_NUMERO_IDENTIFICACION NUMERO DE DOCUMENTO IDENTIFICATIVO DE PERSONA
* @return REFCURSOR
*/

CREATE OR REPLACE FUNCTION F_CGG_TCT_MOVILIDAD_INTERNA_SELECT_DOCUMENTO_IDENTIFIC_INGRESO(IN_CRPER_NUMERO_IDENTIFICACION CHARACTER VARYING)
  RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
SELECT 		
	       MVI.CRMVI_CODIGO AS CODIGO_INGRESO,
		
		MV.CRMOV_CODIGO,				
		PR.CRPER_CODIGO,
		PR.CRDID_CODIGO,
		RG.CTREG_CODIGO,
		RG.CTREG_CODIGO_BARRAS,
		(SELECT CRDID_DESCRIPCION FROM  CGG_RES_DOCUMENTO_IDENTIFICACIO DI WHERE DI.CRDID_CODIGO = PR.CRDID_CODIGO) CRPER_TIPO_DOCUMENTO,
		PR.CRPER_NUM_DOC_IDENTIFIC,
		PR.CRPER_NUMERO_RESIDENCIA,
		PR.CRPER_NOMBRES,
		PR.CRPER_APELLIDO_PATERNO,
		PR.CRPER_GENERO,
		PR.CRPER_FECHA_NACIMIENTO,
		PR.CGNCN_CODIGO,		
		(SELECT CGNCN_NACIONALIDAD FROM  CGG_NACIONALIDAD NC WHERE NC.CGNCN_CODIGO = PR.CGNCN_CODIGO) CRPER_NACIONALIDAD,							
		MAX(MV.CRMOV_FECHA_VIAJE) CRMOV_FECHA_VIAJE,
		MAX(MVI.CRMVI_FECHA_VIAJE) CRMIV_FECHA_VIAJE,
		MVI.CRMVI_TIPO_OPERACION,
		
		(SELECT CGCNF_CONFIGURACION
FROM CGG_CONFIGURACION C
WHERE CGCNF_VALOR_CADENA = (SELECT ST.CRTST_CODIGO FROM CGG_RES_TIPO_SOLICITUD_TRAMITE ST
INNER JOIN CGG_RES_RESIDENCIA RS ON (RS.CRTST_CODIGO = ST.CRTST_CODIGO)
 WHERE RS.CRRSD_VIGENTE = TRUE AND RS.CRPER_CODIGO=PR.CRPER_CODIGO)OR CGCNF_VALOR_CADENA = (SELECT ST.CGG_CRTST_CODIGO FROM CGG_RES_TIPO_SOLICITUD_TRAMITE ST
INNER JOIN CGG_RES_RESIDENCIA RS ON (RS.CRTST_CODIGO = ST.CRTST_CODIGO)
 WHERE RS.CRRSD_VIGENTE = TRUE AND RS.CRPER_CODIGO=PR.CRPER_CODIGO))TIPO_RESIDENCIA,
 MVI.CRMLE_CODIGO, 
		(SELECT CRMLE_NOMBRE FROM SII.CGG_RES_MUELLE MLE WHERE MLE.CRMLE_CODIGO=MVI.CRMLE_CODIGO) CRMLE_NOMBRE,
		MVI.CGG_CRMLE_CODIGO, 
		(SELECT MLE.CRMLE_NOMBRE FROM SII.CGG_RES_MUELLE MLE WHERE MLE.CRMLE_CODIGO=MVI.CGG_CRMLE_CODIGO) CGG_CRMLE_NOMBRE,
		MVI.CREMB_CODIGO, 
		(SELECT EMB.CREMB_NOMBRE FROM SII.CGG_RES_EMBARCACION EMB WHERE EMB.CREMB_CODIGO=MVI.CREMB_CODIGO) CREMB_NOMBRE,
		MVI.CARPT_CODIGO, 
		(SELECT AER.CARPT_NOMBRE FROM SII.CGG_RES_AEROPUERTO AER WHERE AER.CARPT_CODIGO=MVI.CARPT_CODIGO) CARPT_NOMBRE,
		MVI.CGG_CARPT_CODIGO,
		(SELECT AER.CARPT_NOMBRE FROM SII.CGG_RES_AEROPUERTO AER WHERE AER.CARPT_CODIGO=MVI.CGG_CARPT_CODIGO) CARPT_NOMBRE_DESTINO,
		MVI.CRALN_CODIGO, 
		(SELECT ALN.CRALN_NOMBRE FROM SII.CGG_RES_AEROLINEA ALN WHERE ALN.CRALN_CODIGO=MVI.CRALN_CODIGO) CRALN_NOMBRE,
		MVI.CRALN_DESCRIPCION_VUELO
		
	FROM SII.CGG_RES_MOVILIDAD MV
	
	INNER JOIN SII.CGG_TCT_REGISTRO RG ON(RG.CTREG_CODIGO=MV.CTREG_CODIGO)					
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = MV.CRPER_CODIGO)	
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON (RS.CRPER_CODIGO = PR.CRPER_CODIGO)
    LEFT JOIN SII.CGG_RES_MOVILIDAD_INTERNA MVI ON (MVI.CRPER_CODIGO = PR.CRPER_CODIGO)	
	WHERE CRMOV_ESTADO = TRUE 	
	AND (RS.CRRSD_VIGENTE = TRUE AND MV.CRMOV_TIPO_OPERACION=0 AND MVI.CRMVI_TIPO_OPERACION=2
	
	AND PR.CRPER_NUMERO_RESIDENCIA = IN_CRPER_NUMERO_IDENTIFICACION
	OR PR.CRPER_NUM_DOC_IDENTIFIC =IN_CRPER_NUMERO_IDENTIFICACION
	OR RG.CTREG_CODIGO_BARRAS=IN_CRPER_NUMERO_IDENTIFICACION)
	GROUP BY MV.CRMOV_CODIGO,MV.CGG_CARPT_CODIGO,MV.CRMOV_TIPO_OPERACION, 				
		PR.CRPER_CODIGO,
		PR.CRDID_CODIGO,
		RG.CTREG_CODIGO,
		RG.CTREG_CODIGO_BARRAS,
		PR.CRPER_NUM_DOC_IDENTIFIC,
		PR.CRPER_NUMERO_RESIDENCIA,
		PR.CRPER_NOMBRES,
		PR.CRPER_APELLIDO_PATERNO,
		PR.CRPER_GENERO,
		PR.CRPER_FECHA_NACIMIENTO,
		PR.CGNCN_CODIGO,MV.CRMOV_FECHA_VIAJE,MVI.CRMVI_TIPO_OPERACION,
		MVI.CRMVI_CODIGO, 
		MVI.CRMLE_CODIGO,MVI.CGG_CRMLE_CODIGO,MVI.CRALN_DESCRIPCION_VUELO,MVI.CARPT_CODIGO,MVI.CREMB_CODIGO,MVI.CGG_CARPT_CODIGO,
		MVI.CRALN_CODIGO
		ORDER BY MV.CRMOV_FECHA_VIAJE DESC LIMIT 1;


	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100
  ROWS 1000;
ALTER FUNCTION F_CGG_TCT_MOVILIDAD_INTERNA_SELECT_DOCUMENTO_IDENTIFIC_INGRESO(CHARACTER VARYING) OWNER TO SII;
