/**
* FUNCION SII.F_CGG_RES_RESOLUCION_UPDATE_ADJUNTOS
* ACTUALIZA UN REGISTRO EN LA TABLA sii.CGG_RES_RESOLUCION.
* @param IN_CRRES_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE RESOLUCIONES
* @param IN_CRSSC_CODIGO IDENTIFICATIVO UNICO DE REGIsTRO DE SESION
* @param IN_CRRES_NUMERO_RESOLUCION NUMERO IDENTIFICATIVO DE LA RESOLUCION
* @param IN_CRRES_TIPO TIPO DE RESOLUCION
0 - NORMATIVA
1 - APROBACION
* @param IN_CRRES_OBSERVACIONES OBSERVACIONES CONSIDERADAS PARA LA RESOLUCION
* @param IN_CRRES_EXTRACTO_RESOLUCION RESUMEN DEL CONTENIDO DE LA RESOLUCION
* @param IN_CRRES_VOTOS_APROBACION NUMERO DE VOTOS A FAVOR DE LA RESOLUCION
* @param IN_CRRES_VOTOS_NEGACION NUMERO DE VOTOS EN CONTRA DE LA RESOLUCION
* @param IN_CRRES_VOTOS_ABSTENCION NUMERO DE VOTOS DE ABSTENCION
* @param IN_CRRES_FECHA_EMISION FECHA DE EMISION DE RESULTADO DE LA RESOLUCION
* @param IN_CRRES_FECHA_EJECUCION FECHA DE EJECUCION O LLEVADA A LA PRACTICA
* @param IN_CRRES_FECHA_ANULACION FECHA DE ANULACION O PERDIDA DE LA VIGENCIA
* @param IN_CRRES_RESOLUCION_REEMPLAZA RESOLUCION POR LA QUE PUDO SER REEMPLAZA LA ACTUAL
* @param IN_CRRES_NOMBRE_ADJUNTO_RESOL NOMBRE DEL DOCUMENTO ADJUNTO
* @param IN_CRRES_ADJUNTO_RESOLUCION ARCHIVO DIGITAL ANEXO A LA RESOLUCION
* @param IN_CRRES_DESCRIPCION_ADJUNTO DESCRIPCION DE LOS DOCUMENTOS ADJUNTOS
* @param IN_CRRES_FECHA_APELACION FECHA DE APELACION A LA RESOLUCION
* @param IN_CRRES_EXTRACTO_APELACION EXTRACTO DE LA APELACION
* @param IN_CRRES_NUMERO_APELACION NUMERO DE DOCUMENTO DE APELACION
* @param IN_CRRES_NOMBRE_ADJUNTO_APELAC NOMBRE DEL DOCUMENTO ADJUNTO
* @param IN_CRRES_ADJUNTO_APELACION ARCHIVO ADJUNTO A LA APELACION
* @param IN_CRRES_ESTADO_RESOLUCION ESTADO DE LA RESOLUCION:
0 - ESPERANDO VOTACION
1 - APROBADA
2 - NEGADA
3 - EJECUTADA
4 - ANULADA
* @param IN_CRRES_ESTADO ESTADO DEL REGISTRO
* @param IN_CRRES_USUARIO_UPDATE USUARIO QUE REALIZO LA ACTUALIZACION DE LA INFORMACION
* @return VOID
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_RESOLUCION_UPDATE_ADJUNTOS(
IN IN_CRRES_CODIGO SII.CGG_RES_RESOLUCION.CRRES_CODIGO%TYPE, 
IN IN_CRSSC_CODIGO SII.CGG_RES_RESOLUCION.CRSSC_CODIGO%TYPE, 
IN IN_CRRES_NUMERO_RESOLUCION SII.CGG_RES_RESOLUCION.CRRES_NUMERO_RESOLUCION%TYPE, 
IN IN_CRRES_TIPO SII.CGG_RES_RESOLUCION.CRRES_TIPO%TYPE, 
IN IN_CRRES_OBSERVACIONES SII.CGG_RES_RESOLUCION.CRRES_OBSERVACIONES%TYPE, 
IN IN_CRRES_EXTRACTO_RESOLUCION SII.CGG_RES_RESOLUCION.CRRES_EXTRACTO_RESOLUCION%TYPE, 
IN IN_CRRES_VOTOS_APROBACION SII.CGG_RES_RESOLUCION.CRRES_VOTOS_APROBACION%TYPE, 
IN IN_CRRES_VOTOS_NEGACION SII.CGG_RES_RESOLUCION.CRRES_VOTOS_NEGACION%TYPE, 
IN IN_CRRES_VOTOS_ABSTENCION SII.CGG_RES_RESOLUCION.CRRES_VOTOS_ABSTENCION%TYPE, 
IN IN_CRRES_FECHA_EMISION SII.CGG_RES_RESOLUCION.CRRES_FECHA_EMISION%TYPE, 
IN IN_CRRES_FECHA_EJECUCION SII.CGG_RES_RESOLUCION.CRRES_FECHA_EJECUCION%TYPE, 
IN IN_CRRES_FECHA_ANULACION SII.CGG_RES_RESOLUCION.CRRES_FECHA_ANULACION%TYPE, 
IN IN_CRRES_FECHA_CONFIRMACION SII.CGG_RES_RESOLUCION.CRRES_FECHA_CONFIRMACION%TYPE, 
IN IN_CRRES_RESOLUCION_REEMPLAZA SII.CGG_RES_RESOLUCION.CRRES_RESOLUCION_REEMPLAZA%TYPE, 
IN IN_CRRES_NOMBRE_ADJUNTO_RESOL SII.CGG_RES_RESOLUCION.CRRES_NOMBRE_ADJUNTO_RESOL%TYPE, 
IN IN_CRRES_ADJUNTO_RESOLUCION SII.CGG_RES_RESOLUCION.CRRES_ADJUNTO_RESOLUCION%TYPE, 
IN IN_CRRES_DESCRIPCION_ADJUNTO SII.CGG_RES_RESOLUCION.CRRES_DESCRIPCION_ADJUNTO%TYPE, 
IN IN_CRRES_FECHA_APELACION SII.CGG_RES_RESOLUCION.CRRES_FECHA_APELACION%TYPE, 
IN IN_CRRES_EXTRACTO_APELACION SII.CGG_RES_RESOLUCION.CRRES_EXTRACTO_APELACION%TYPE, 
IN IN_CRRES_NUMERO_APELACION SII.CGG_RES_RESOLUCION.CRRES_NUMERO_APELACION%TYPE, 
IN IN_CRRES_NOMBRE_ADJUNTO_APELAC SII.CGG_RES_RESOLUCION.CRRES_NOMBRE_ADJUNTO_APELAC%TYPE, 
IN IN_CRRES_ADJUNTO_APELACION SII.CGG_RES_RESOLUCION.CRRES_ADJUNTO_APELACION%TYPE, 
IN IN_CRRES_ESTADO_RESOLUCION SII.CGG_RES_RESOLUCION.CRRES_ESTADO_RESOLUCION%TYPE, 
IN IN_CRRES_ESTADO SII.CGG_RES_RESOLUCION.CRRES_ESTADO%TYPE, 
IN IN_CRRES_USUARIO_UPDATE SII.CGG_RES_RESOLUCION.CRRES_USUARIO_UPDATE%TYPE
)RETURNS VOID AS
$$
DECLARE
TMP_RECORD_TRM RECORD;
BEGIN
	UPDATE SII.CGG_RES_RESOLUCION SET
		CRSSC_CODIGO = IN_CRSSC_CODIGO, 
		CRRES_NUMERO_RESOLUCION = IN_CRRES_NUMERO_RESOLUCION, 
		CRRES_TIPO = IN_CRRES_TIPO, 
		CRRES_OBSERVACIONES = IN_CRRES_OBSERVACIONES, 
		CRRES_EXTRACTO_RESOLUCION = IN_CRRES_EXTRACTO_RESOLUCION, 
		CRRES_VOTOS_APROBACION = IN_CRRES_VOTOS_APROBACION, 
		CRRES_VOTOS_NEGACION = IN_CRRES_VOTOS_NEGACION, 
		CRRES_VOTOS_ABSTENCION = IN_CRRES_VOTOS_ABSTENCION, 
		CRRES_FECHA_EMISION = IN_CRRES_FECHA_EMISION, 
		CRRES_FECHA_EJECUCION = IN_CRRES_FECHA_EJECUCION, 
		CRRES_FECHA_ANULACION = IN_CRRES_FECHA_ANULACION, 
		CRRES_FECHA_CONFIRMACION = IN_CRRES_FECHA_CONFIRMACION,
		CRRES_RESOLUCION_REEMPLAZA = IN_CRRES_RESOLUCION_REEMPLAZA, 		
		CRRES_DESCRIPCION_ADJUNTO = IN_CRRES_DESCRIPCION_ADJUNTO, 
		CRRES_FECHA_APELACION = IN_CRRES_FECHA_APELACION, 
		CRRES_EXTRACTO_APELACION = IN_CRRES_EXTRACTO_APELACION, 
		CRRES_NUMERO_APELACION = IN_CRRES_NUMERO_APELACION, 		
		CRRES_ESTADO_RESOLUCION = IN_CRRES_ESTADO_RESOLUCION, 
		CRRES_ESTADO = IN_CRRES_ESTADO, 
		CRRES_FECHA_UPDATE = CURRENT_TIMESTAMP, 
		CRRES_USUARIO_UPDATE = IN_CRRES_USUARIO_UPDATE
	WHERE
		CRRES_CODIGO = IN_CRRES_CODIGO;
		
	IF (LENGTH (IN_CRRES_ADJUNTO_RESOLUCION) >0) THEN	
	UPDATE SII.CGG_RES_RESOLUCION SET
		CRRES_NOMBRE_ADJUNTO_RESOL = IN_CRRES_NOMBRE_ADJUNTO_RESOL, 
		CRRES_ADJUNTO_RESOLUCION = IN_CRRES_ADJUNTO_RESOLUCION	
	WHERE
		CRRES_CODIGO = IN_CRRES_CODIGO;	
	END IF;
	
	IF (LENGTH (IN_CRRES_ADJUNTO_APELACION) >0) THEN		
	UPDATE SII.CGG_RES_RESOLUCION SET		
		CRRES_NOMBRE_ADJUNTO_APELAC = IN_CRRES_NOMBRE_ADJUNTO_APELAC, 
		CRRES_ADJUNTO_APELACION = IN_CRRES_ADJUNTO_APELACION	
	WHERE
		CRRES_CODIGO = IN_CRRES_CODIGO;	
	END IF;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;