/**
* FUNCION SII.F_CGG_JUR_TRAMITE_JURIDICO_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_JUR_CRITERIO Y CGG_JUR_SEGUIMIENTO_CRITERIO.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_JUR_TRAMITE_JURIDICO_SELECT(
IN IN_USER_NAME VARCHAR,
IN IN_START_INDEX INT,
IN IN_LIMIT INT,
IN IN_SORT_FIELD_NAME VARCHAR,
IN IN_DIRECTION VARCHAR,
IN IN_FIND_TEXT TEXT
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT 
	SG.CRSEG_CODIGO,
	SG.CRSEG_NUMERO,
	SG.CRSEG_DESCRIPCION,
	TR.CRTRA_CODIGO,
	TR.CRTRA_NUMERO,
	TR.CRTRA_ANIO,
	TR.CRTST_CODIGO,
	TST.CRTST_DESCRIPCION,
	TR.CRPER_CODIGO,
	(PRS.CRPER_NOMBRES ||'' ''||PRS.CRPER_APELLIDO_PATERNO||'' ''||PRS.CRPER_APELLIDO_MATERNO) AUSPICIANTE,
	TR.CGG_CRPER_CODIGO,	
	(PER.CRPER_NOMBRES ||'' ''||PER.CRPER_APELLIDO_PATERNO||'' ''||PER.CRPER_APELLIDO_MATERNO) BENEFICIARIO,	
	SG.CGG_CRSEG_CODIGO,
	FS.CRFAS_NOMBRE,
	SG.CRSEG_ESTADO_ATENCION,
	SG.CRSEG_TIPO_RESPUESTA,
	SG.CRSEG_FECHA_RECEPCION,
	SG.CRSEG_FECHA_REVISION,
	SG.CRSEG_FECHA_DESPACHO,
	SG.CRSEG_ESTADO_HIJO,
	TR.CRTRA_FECHA_RECEPCION,	
	SC.CJSGC_CODIGO,
	SC.CJCRI_CODIGO,
	SC.CJSGC_JUSTIFICACION	
	FROM CGG_RES_SEGUIMIENTO SG
	INNER JOIN CGG_RES_TRAMITE TR ON (SG.CRTRA_CODIGO = TR.CRTRA_CODIGO)
	INNER JOIN CGG_RES_PERSONA PRS ON (PRS.CRPER_CODIGO = TR.CRPER_CODIGO)	
	INNER JOIN CGG_RES_PERSONA PER ON (PER.CRPER_CODIGO = TR.CGG_CRPER_CODIGO)	
	INNER JOIN CGG_JUR_SEGUIMIENTO_CRITERIO SC ON (SC.CRSEG_CODIGO = SG.CRSEG_CODIGO)	
	INNER JOIN CGG_JUR_CRITERIO JC ON (JC.CJCRI_CODIGO = SC.CJCRI_CODIGO)
	INNER JOIN CGG_RES_FASE FS ON (FS.CRFAS_CODIGO= JC.CRFAS_CODIGO)
	INNER JOIN CGG_RES_TIPO_SOLICITUD_TRAMITE TST ON(TST.CRTST_CODIGO = TR.CRTST_CODIGO)	
	WHERE CRSEG_ESTADO = TRUE 
	AND  SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	COALESCE(PRS.CRPER_NOMBRES,'''') ||'' ''||
	COALESCE(PRS.CRPER_APELLIDO_PATERNO,'''')||'' ''||
	COALESCE(PRS.CRPER_APELLIDO_MATERNO,'''')||'' ''||
	COALESCE(PER.CRPER_NOMBRES,'''') ||'' ''||
	COALESCE(PER.CRPER_APELLIDO_PATERNO,'''')||'' ''||
	COALESCE(PER.CRPER_APELLIDO_MATERNO,'''')||'' ''||
	COALESCE(TR.CRTRA_NUMERO, 0)||'' ''||
	COALESCE(CRSEG_NUMERO, 0)||'' ''||
	COALESCE(CRSEG_DESCRIPCION, '''')||'' ''||
	COALESCE(TST.CRTST_DESCRIPCION,'''')||'' ''||	
	COALESCE(CRTRA_ANIO, 0)||'' ''||
	COALESCE(CRFAS_NOMBRE, '''')||'' ''||
	COALESCE(CRSEG_ESTADO_ATENCION, 0)||'' ''||
	COALESCE(CRSEG_TIPO_RESPUESTA, 0)||'' ''||
	COALESCE(CRSEG_FECHA_RECEPCION, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRSEG_FECHA_REVISION, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRSEG_FECHA_DESPACHO, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRSEG_ESTADO_HIJO, 0)||'' ''||
	COALESCE(CRTRA_FECHA_RECEPCION, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CJSGC_JUSTIFICACION, '''')) = 1
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;


/**
* FUNCION SII.F_CGG_JUR_TRAMITE_JURIDICO_COUNT
* CONTABILIZA N REGISTROS DE LA TABLA SII.CGG_JUR_CRITERIO Y CGG_JUR_SEGUIMIENTO_CRITERIO.
* @return INT
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_JUR_TRAMITE_JURIDICO_COUNT(
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM CGG_RES_SEGUIMIENTO SG
	INNER JOIN CGG_RES_TRAMITE TR ON (SG.CRTRA_CODIGO = TR.CRTRA_CODIGO)
	INNER JOIN CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = TR.CRPER_CODIGO)	
	INNER JOIN CGG_JUR_SEGUIMIENTO_CRITERIO SC ON (SC.CRSEG_CODIGO = SG.CRSEG_CODIGO)	
	INNER JOIN CGG_JUR_CRITERIO JC ON (JC.CJCRI_CODIGO = SC.CJCRI_CODIGO)
	INNER JOIN CGG_RES_FASE FS ON (FS.CRFAS_CODIGO= JC.CRFAS_CODIGO)	
	WHERE CRSEG_ESTADO = TRUE ;
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_JUR_TRAMITE_JURIDICO_COUNT
* CONTABILIZA N REGISTROS DE LA TABLA SII.CGG_JUR_CRITERIO Y CGG_JUR_SEGUIMIENTO_CRITERIO.
* QUE CUMPLEN CON EL CRITERIO DE BUSQUEDA.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TOTAL DE REGISTROS
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_JUR_TRAMITE_JURIDICO_COUNT(
IN IN_FIND_TEXT TEXT
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_DHU_TIPO_BECA
	WHERE CRSEG_ESTADO = TRUE 
	AND SII.F_STRING_IN(IN_FIND_TEXT,
	COALESCE(CRSEG_NUMERO, 0)||' '||
	COALESCE(CRSEG_DESCRIPCION, '''')||' '||	
	COALESCE(CRTRA_ANIO, 0)||' '||
	COALESCE(CRFAS_NOMBRE, '''')||' '||
	COALESCE(CRSEG_ESTADO_ATENCION, 0)||' '||
	COALESCE(CRSEG_TIPO_RESPUESTA, 0)||' '||
	COALESCE(CRSEG_FECHA_RECEPCION, CURRENT_TIMESTAMP)||' '||
	COALESCE(CRSEG_FECHA_REVISION, CURRENT_TIMESTAMP)||' '||
	COALESCE(CRSEG_FECHA_DESPACHO, CURRENT_TIMESTAMP)||' '||
	COALESCE(CRSEG_ESTADO_HIJO, 0)||' '||
	COALESCE(CRTRA_FECHA_RECEPCION, CURRENT_TIMESTAMP)||' '||
	COALESCE(CJSGC_JUSTIFICACION, ' ')) = 1;
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;
