/**
* FUNCION F_CGG_GENERA_NUM_INFORME_TESTIGO
* GENERA EL NUMERO DE INFORME DE PAREJA.
* @return CHARACTER VARYING
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_GENERA_NUM_INFORME_PAREJA()
  RETURNS CHARACTER VARYING AS
$BODY$
DECLARE
	TMP_SECUENCIA CHARACTER VARYING;
	TMP_ANIO CHARACTER VARYING;
	TMP_ACRONIMO CHARACTER VARYING;	
BEGIN
	SELECT COUNT(CRINF_NUMERO_DOCUMENTO)+1 INTO TMP_SECUENCIA
	FROM SII.CGG_RES_INFORME_PAREJA
	WHERE EXTRACT(YEAR FROM CRINF_FECHA_INSERT) = EXTRACT(YEAR FROM CURRENT_TIMESTAMP);
	
	SELECT CGCNF_VALOR_CADENA INTO TMP_ACRONIMO
	FROM SII.CGG_CONFIGURACION WHERE CGCNF_CODIGO = 'CONF1';
	
	SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP) INTO TMP_ANIO;
	
	RETURN  TMP_ACRONIMO||'-'||TMP_ANIO||'-'||LPAD(TMP_SECUENCIA,4,'0');
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;