/**
* FUNCION SII.F_CGG_MOVILIDAD_INGRESO_PAG_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_MOVILIDAD.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC 
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param IN_IDENTIFICACION IDENTIFICACION
* @param IN_MOVIMIENTO IDENTIFICATIVO DE TIPO DE MOVIMIENTO
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_MOVILIDAD_INGRESO_PAG_SELECT(
IN IN_USER_NAME VARCHAR(50),
IN IN_START_INDEX INT,
IN IN_LIMIT INT,
IN IN_SORT_FIELD_NAME VARCHAR,
IN IN_DIRECTION VARCHAR,
IN IN_FIND_TEXT TEXT,
IN IN_IDENTIFICACION VARCHAR,
IN IN_MOVIMIENTO INT
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
	TMP_RSD VARCHAR;
BEGIN
	TMP_RSD = 'AND RS.CRRSD_VIGENTE';
	
	IF (IN_MOVIMIENTO != -1) THEN
		TMP_RSD = 'AND RS.CRRSD_CODIGO = MV.CRRSD_CODIGO ';
	END IF;
	
	OPEN TMP_REF FOR EXECUTE
	'WITH TCT_REG AS (SELECT
		MV.CRMOV_CODIGO,
		RG.CTREG_CODIGO, 		
		RG.CTGTR_CODIGO	,	
		PR.CRPER_CODIGO,		
		PR.CRDID_CODIGO,
		RG.CTREG_CODIGO_BARRAS,
		RG.CRALN_CODIGO, 
		(SELECT CRALN_NOMBRE FROM  CGG_RES_AEROLINEA AL WHERE AL.CRALN_CODIGO = RG.CRALN_CODIGO) AEROLINEA,		
		RG.CARPT_CODIGO, 
		(SELECT CARPT_NOMBRE FROM  CGG_RES_AEROPUERTO AR WHERE AR.CARPT_CODIGO = RG.CARPT_CODIGO) AEROPUER_ORIGEN,
		RG.CGG_CARPT_CODIGO, 
		CASE WHEN MV.CRMOV_TIPO_OPERACION = 0 THEN ARPS.CARPT_NOMBRE ELSE (SELECT CARPT_NOMBRE FROM SII.CGG_RES_AEROPUERTO AR WHERE AR.CARPT_CODIGO = RG.CGG_CARPT_CODIGO) END AEROPUER_DESTINO,
		RG.CTREG_FECHA_INGRESO, 		
		RG.CTREG_FECHA_SALIDA, 				
		(SELECT CRDID_DESCRIPCION FROM SII.CGG_RES_DOCUMENTO_IDENTIFICACIO DI WHERE DI.CRDID_CODIGO = PR.CRDID_CODIGO) DOCUMENTO,
		PR.CRPER_NUM_DOC_IDENTIFIC,
		PR.CRPER_NOMBRES,
		PR.CRPER_APELLIDO_PATERNO,
		PR.CRPER_APELLIDO_MATERNO,
		PR.CRPER_GENERO,
		PR.CRPER_FECHA_NACIMIENTO,
		PR.CPAIS_CODIGO,
		PR.CGG_CPAIS_CODIGO,
		(SELECT CPAIS_NOMBRE FROM SII.CGG_PAIS PS WHERE PS.CPAIS_CODIGO = PR.CGG_CPAIS_CODIGO) PAIS_RESIDENCIA,
		PR.CGNCN_CODIGO,
		(SELECT CGNCN_NACIONALIDAD FROM SII.CGG_NACIONALIDAD NC WHERE NC.CGNCN_CODIGO = PR.CGNCN_CODIGO) NACIONALIDAD,
		TRM.CRTRA_CODIGO,
		TRM.CRTRA_NUMERO,
		RS.CRRSD_CODIGO,
		COALESCE(TST.CRTST_DESCRIPCION,''Turista'') TIPO_RESIDENCIA,	
		RG.CTREG_ESTADO_REGISTRO,
		RG.CTREG_OBSERVACION,
		MV.CRMOV_FECHA_VIAJE
	FROM SII.CGG_RES_PERSONA PR
	INNER JOIN SII.CGG_TCT_REGISTRO RG ON RG.CRPER_CODIGO = PR.CRPER_CODIGO AND RG.CTREG_ESTADO_REGISTRO IN (1,4) AND NOT RG.CTREG_COMPLETO 
	LEFT JOIN SII.CGG_RES_MOVILIDAD MV ON MV.CTREG_CODIGO = RG.CTREG_CODIGO
	LEFT JOIN SII.CGG_RES_RESIDENCIA RS ON RS.CRPER_CODIGO = PR.CRPER_CODIGO AND RS.CRRSD_ESTADO '||TMP_RSD||' AND
		(RS.CRTST_CODIGO IN (WITH RECURSIVE TIPO(CRTST_CODIGO, CGG_CRTST_CODIGO, CRTST_DESCRIPCION)AS(
			SELECT CRTST_CODIGO, CGG_CRTST_CODIGO, CRTST_DESCRIPCION FROM CGG_RES_TIPO_SOLICITUD_TRAMITE WHERE CRTST_CODIGO = (SELECT CGCNF_VALOR_CADENA
			FROM CGG_CONFIGURACION
			WHERE CGCNF_CODIGO = ''05'') OR CRTST_CODIGO = (SELECT CGCNF_VALOR_CADENA
			FROM CGG_CONFIGURACION
			WHERE CGCNF_CODIGO = ''06'')
			UNION SELECT TST.CRTST_CODIGO, TST.CGG_CRTST_CODIGO, TP.CRTST_DESCRIPCION FROM CGG_RES_TIPO_SOLICITUD_TRAMITE TST, TIPO TP
			WHERE TST.CGG_CRTST_CODIGO = TP.CRTST_CODIGO
		) SELECT CRTST_CODIGO  FROM TIPO)) AND
		('||IN_MOVIMIENTO||' != -1 OR RS.CRRSD_FECHA_INICIO::DATE = CURRENT_DATE)
	LEFT JOIN SII.CGG_RES_TIPO_SOLICITUD_TRAMITE TST ON TST.CRTST_CODIGO = RS.CRTST_CODIGO
	LEFT JOIN SII.CGG_RES_AEROPUERTO ARPI ON ARPI.CARPT_CODIGO = MV.CARPT_CODIGO
	LEFT JOIN SII.CGG_RES_AEROPUERTO ARPS ON ARPS.CARPT_CODIGO = MV.CGG_CARPT_CODIGO
	LEFT JOIN SII.CGG_RES_TRAMITE TRM ON TRM.CRTRA_CODIGO = RS.CRTRA_CODIGO
	WHERE CTREG_ESTADO AND (LENGTH('||QUOTE_LITERAL(IN_FIND_TEXT)||') = 0 OR SII.F_STRING_IN('''||IN_FIND_TEXT||''',
		COALESCE(RG.CTREG_CODIGO_BARRAS,'''')||'' ''||
		COALESCE(RG.CTREG_FECHA_INGRESO,CURRENT_TIMESTAMP)||'' ''||
		COALESCE(RG.CTREG_FECHA_SALIDA,CURRENT_TIMESTAMP)||'' ''||	
		COALESCE(PR.CRPER_NUM_DOC_IDENTIFIC,'''')||'' ''||
		COALESCE(PR.CRPER_NOMBRES,'''')||'' ''||
		COALESCE(PR.CRPER_APELLIDO_PATERNO,'''')||'' ''||
		COALESCE(PR.CRPER_APELLIDO_PATERNO,'''')) = 1 ) AND 
	(LENGTH('||QUOTE_LITERAL(IN_IDENTIFICACION)||') = 0 OR RG.CTREG_CODIGO_BARRAS = '||QUOTE_LITERAL(IN_IDENTIFICACION)||' OR PR.CRPER_NUM_DOC_IDENTIFIC = '||QUOTE_LITERAL(IN_IDENTIFICACION)||'))
	SELECT * FROM TCT_REG WHERE ('||IN_MOVIMIENTO||' = 0 AND CRMOV_CODIGO IS NOT NULL OR '||IN_MOVIMIENTO||' = -1 AND CRMOV_CODIGO IS NULL)
	 LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	--ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_MOVILIDAD_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_RES_MOVILIDAD
* QUE CUMPLEN CON EL CRITERIO DE BUSQUEDA.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param IN_IDENTIFICACION IDENTIFICACION
* @param IN_MOVIMIENTO IDENTIFICATIVO DE TIPO DE MOVIMIENTO
* @return TOTAL DE REGISTROS
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_MOVILIDAD_INGRESO_PAG_COUNT(
IN IN_FIND_TEXT TEXT,
IN IN_IDENTIFICACION VARCHAR,
IN IN_MOVIMIENTO INT
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_RES_PERSONA PR			
	INNER JOIN SII.CGG_TCT_REGISTRO RG ON RG.CRPER_CODIGO = PR.CRPER_CODIGO AND RG.CTREG_ESTADO_REGISTRO IN (1,4) AND NOT RG.CTREG_COMPLETO 
	LEFT JOIN SII.CGG_RES_MOVILIDAD MV ON MV.CTREG_CODIGO = RG.CTREG_CODIGO AND MV.CRMOV_ESTADO
	LEFT JOIN SII.CGG_RES_RESIDENCIA RS ON RS.CRPER_CODIGO = PR.CRPER_CODIGO AND RS.CRRSD_ESTADO AND RS.CRRSD_VIGENTE AND
		(RS.CRTST_CODIGO IN (WITH RECURSIVE TIPO(CRTST_CODIGO, CGG_CRTST_CODIGO, CRTST_DESCRIPCION)AS(
			SELECT CRTST_CODIGO, CGG_CRTST_CODIGO, CRTST_DESCRIPCION FROM CGG_RES_TIPO_SOLICITUD_TRAMITE WHERE CRTST_CODIGO = (SELECT CGCNF_VALOR_CADENA
			FROM CGG_CONFIGURACION
			WHERE CGCNF_CODIGO = '05') OR CRTST_CODIGO = (SELECT CGCNF_VALOR_CADENA
			FROM CGG_CONFIGURACION
			WHERE CGCNF_CODIGO = '06')
			UNION SELECT TST.CRTST_CODIGO, TST.CGG_CRTST_CODIGO, TP.CRTST_DESCRIPCION FROM CGG_RES_TIPO_SOLICITUD_TRAMITE TST, TIPO TP
			WHERE TST.CGG_CRTST_CODIGO = TP.CRTST_CODIGO
		) SELECT CRTST_CODIGO  FROM TIPO)) AND
		(IN_MOVIMIENTO != -1 OR RS.CRRSD_FECHA_INICIO::DATE = CURRENT_DATE)
	WHERE CTREG_ESTADO AND (IN_FIND_TEXT IS NULL OR LENGTH(IN_FIND_TEXT) = 0 OR SII.F_STRING_IN(IN_FIND_TEXT,
		COALESCE(RG.CTREG_CODIGO_BARRAS,'')||' '||
		COALESCE(RG.CTREG_FECHA_INGRESO,CURRENT_TIMESTAMP)||' '||
		COALESCE(RG.CTREG_FECHA_SALIDA,CURRENT_TIMESTAMP)||' '||	
		COALESCE(PR.CRPER_NUM_DOC_IDENTIFIC,'')||' '||
		COALESCE(PR.CRPER_NOMBRES,'')||' '||
		COALESCE(PR.CRPER_APELLIDO_PATERNO,'')||' '||
		COALESCE(PR.CRPER_APELLIDO_MATERNO,'')||' '||
		COALESCE(PR.CRPER_FECHA_NACIMIENTO,CURRENT_TIMESTAMP)) = 1) AND 
		(IN_IDENTIFICACION IS NULL OR LENGTH(IN_IDENTIFICACION) = 0 OR RG.CTREG_CODIGO_BARRAS = IN_IDENTIFICACION OR PR.CRPER_NUM_DOC_IDENTIFIC = IN_IDENTIFICACION);
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;


