/**
* FUNCION SII.F_CGG_RES_SESION_COMITE_APROBADO_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_SESION_COMITE QUE ESTEN EL ESTADO DE LA CONVOCATORIA DE APROBADO.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_SESION_COMITE_APROBADO_SELECT(
IN IN_USER_NAME VARCHAR,
IN IN_START_INDEX INT,
IN IN_LIMIT INT,
IN IN_SORT_FIELD_NAME VARCHAR,
IN IN_DIRECTION VARCHAR,
IN IN_FIND_TEXT TEXT
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT
		SC.CRSSC_CODIGO, 
		SC.CISLA_CODIGO, 
		(SELECT CISLA_NOMBRE FROM SII.CGG_ISLA WHERE CISLA_CODIGO = SC.CISLA_CODIGO) ISLA,
		SC.CRCOM_CODIGO, 
		(SELECT CRCOM_NOMBRE FROM SII.CGG_RES_COMITE WHERE CRCOM_CODIGO = SC.CRCOM_CODIGO) COMITE,
		SC.CRSSC_FECHA_REUNION, 
		SC.CRSSC_FECHA_FINALIZACION, 
		SC.CRSSC_NUMERO_SESION, 
		SC.CRSSC_EXTRACTO, 
		SC.CRSSC_OBSERVACION, 
		SC.CRSSC_FECHA_CONVOCATORIA, 
		SC.CRSSC_MOTIVO_CONVOCATORIA, 
		SC.CRSSC_DESCRIPCION_ADJUNTO, 
		SC.CRSSC_NOMBRE_ADJUNTO, 
		NULL,	
		SC.CRSSC_ESTADO_CONVOCATORIA, 
		SC.CRSSC_ESTADO, 
		SC.CRSSC_FECHA_INSERT, 
		SC.CRSSC_USUARIO_INSERT, 
		SC.CRSSC_FECHA_UPDATE, 
		SC.CRSSC_USUARIO_UPDATE
	FROM SII.CGG_RES_SESION_COMITE SC
	WHERE CRSSC_ESTADO = TRUE AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	COALESCE(CRSSC_FECHA_REUNION, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRSSC_FECHA_FINALIZACION, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRSSC_NUMERO_SESION, '''')||'' ''||
	COALESCE(CRSSC_EXTRACTO, '''')||'' ''||
	COALESCE(CRSSC_OBSERVACION, '''')||'' ''||
	COALESCE(CRSSC_FECHA_CONVOCATORIA, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRSSC_MOTIVO_CONVOCATORIA, '''')||'' ''||
	COALESCE(CRSSC_DESCRIPCION_ADJUNTO, '''')||'' ''||
	COALESCE(CRSSC_NOMBRE_ADJUNTO, '''')||'' ''||
	COALESCE(CRSSC_ESTADO_CONVOCATORIA, 0)||'' ''||
	COALESCE(CRSSC_ESTADO, FALSE)||'' ''||
	COALESCE(CRSSC_FECHA_INSERT, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRSSC_USUARIO_INSERT, '''')||'' ''||
	COALESCE(CRSSC_FECHA_UPDATE, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CRSSC_USUARIO_UPDATE, '''')) = 1
	AND CRSSC_ESTADO_CONVOCATORIA = 5
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_SESION_COMITE_APROBADO_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_RES_SESION_COMITE QUE ESTEN EL ESTADO DE LA CONVOCATORIA DE APROBADO.
* @return INT
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_SESION_COMITE_APROBADO_COUNT(
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_RES_SESION_COMITE
	WHERE CRSSC_ESTADO = TRUE
	AND CRSSC_ESTADO_CONVOCATORIA = 5;
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_SESION_COMITE_APROBADO_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_RES_SESION_COMITE QUE ESTEN EL ESTADO DE LA CONVOCATORIA DE APROBADO.
* QUE CUMPLEN CON EL CRITERIO DE BUSQUEDA.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TOTAL DE REGISTROS.
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_SESION_COMITE_APROBADO_COUNT(
IN IN_FIND_TEXT TEXT
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_RES_SESION_COMITE
	WHERE CRSSC_ESTADO = TRUE AND SII.F_STRING_IN(IN_FIND_TEXT,COALESCE(CRSSC_FECHA_REUNION, CURRENT_TIMESTAMP)||' '||COALESCE(CRSSC_FECHA_FINALIZACION, CURRENT_TIMESTAMP)||' '||COALESCE(CRSSC_NUMERO_SESION, '''')||' '||COALESCE(CRSSC_EXTRACTO, '''')||' '||COALESCE(CRSSC_OBSERVACION, '''')||' '||COALESCE(CRSSC_FECHA_CONVOCATORIA, CURRENT_TIMESTAMP)||' '||COALESCE(CRSSC_MOTIVO_CONVOCATORIA, '''')||' '||COALESCE(CRSSC_DESCRIPCION_ADJUNTO, '''')||' '||COALESCE(CRSSC_NOMBRE_ADJUNTO, '''')||' '||COALESCE(CRSSC_ESTADO_CONVOCATORIA, 0)||' '||COALESCE(CRSSC_ESTADO, FALSE)||' '||COALESCE(CRSSC_FECHA_INSERT, CURRENT_TIMESTAMP)||' '||COALESCE(CRSSC_USUARIO_INSERT, '''')||' '||COALESCE(CRSSC_FECHA_UPDATE, CURRENT_TIMESTAMP)||' '||COALESCE(CRSSC_USUARIO_UPDATE, '''')) = 1
	AND CRSSC_ESTADO_CONVOCATORIA = 5;
	
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;