/**
* FUNCION SII.F_CGG_GENERA_NUM_PROCESO_JUDICIAL
* GERENERA EL NUMERO DE PROCESO JUDICIAL.
* @return CHARACTER VARYING
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_GENERA_NUM_PROCESO_JUDICIAL()
  RETURNS CHARACTER VARYING AS
$BODY$
DECLARE
	TMP_SECUENCIA CHARACTER VARYING;
	TMP_ANIO CHARACTER VARYING;
	TMP_ACRONIMO CHARACTER VARYING;	
BEGIN
	SELECT COUNT(CJPJU_NUMERO )+1 INTO TMP_SECUENCIA  
	FROM SII.cgg_jur_proceso_judicial
	WHERE EXTRACT(YEAR FROM CJPJU_FECHA_INSERT) = EXTRACT(YEAR FROM CURRENT_TIMESTAMP);
	
	SELECT CGCNF_VALOR_CADENA INTO TMP_ACRONIMO
	FROM SII.CGG_CONFIGURACION WHERE CGCNF_CODIGO = 'CONF24';
	
	SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP) INTO TMP_ANIO;
	
	RETURN  TMP_ACRONIMO||'-'||TMP_ANIO||'-'||LPAD(TMP_SECUENCIA,4,'0');
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;
