
/**
* FUNCION f_cgg_dhu_numero_asistente
* CONTABILIZA LOS REGISTRO DE LAS PERSONA DE LA TABLA SII.CGG_DHU_ASISTENTE_CURSO.
* @param IN_CDCUR_CODIGO CRITERIO DE BUSQUEDA
* @return  TMP_ROWS
*/
CREATE OR REPLACE FUNCTION f_cgg_dhu_numero_asistente(IN_CDCUR_CODIGO character varying)
  RETURNS integer AS
$BODY$
DECLARE
	TMP_ROWS INT2;
BEGIN
	
	SELECT COUNT(ACU.CRPER_CODIGO)INTO TMP_ROWS
        FROM SII.CGG_DHU_ASISTENTE_CURSO ACU
		 INNER JOIN SII.CGG_DHU_CURSO CU ON(CU.CDCUR_CODIGO=ACU.CDCUR_CODIGO)
        WHERE ACU.CDASC_ESTADO_INSCRIPCION=1 AND CU.CDCUR_ESTADO_CURSO=1 AND ACU.CDASC_ESTADO = TRUE AND ACU.CDCUR_CODIGO=IN_CDCUR_CODIGO;
	
	RETURN TMP_ROWS;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100;