/**
* FUNCION SII.F_CGG_JUR_RESPONSABLE_PROCESO
* SELECCIONA TODOS LOS REGISTRO DE LA TABLA SII.CGG_JUR_PROCESO_JUDICIAL.
* @param IN_CJPJU_USUARIO NOMBRE DEL USUARIO DE PROCESO JUDICIAL
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_JUR_RESPONSABLE_PROCESO(
IN IN_CJPJU_USUARIO  CHARACTER VARYING
) RETURNS CHARACTER VARYING AS
$$
DECLARE
	TMP_NOMBRES CHARACTER VARYING;
BEGIN	
	SELECT 		
		PR.CRPER_NOMBRES ||' '|| PR.CRPER_APELLIDO_PATERNO INTO TMP_NOMBRES
	FROM SII.CGG_RES_PERSONA PR
	INNER JOIN SII.CGG_USUARIO US ON(US.CRPER_CODIGO= PR.CRPER_CODIGO)	
	INNER JOIN SII.CGG_JUR_ASESOR ASR ON (ASR.CUSU_CODIGO = US.CUSU_CODIGO)
	WHERE CRPER_ESTADO = TRUE 	
	AND CJASE_ESTADO = TRUE
	AND US.CUSU_NOMBRE_USUARIO = IN_CJPJU_USUARIO;
	RETURN TMP_NOMBRES;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;


/**
* FUNCION SII.F_CGG_JUR_RESPONSABLE_JURIDICO
* SELECCIONA TODOS LOS REGISTRO DE LA TABLA SII.CGG_JUR_PROCESO_JUDICIAL.
* @param IN_CJPJU_USUARIO NOMBRE DEL USUARIO DE PROCESO JUDICIAL
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_JUR_RESPONSABLE_JURIDICO(
IN IN_CJPJU_USUARIO  CHARACTER VARYING
) RETURNS CHARACTER VARYING AS
$$
DECLARE
	TMP_NOMBRES CHARACTER VARYING;
BEGIN	
	SELECT 		
		PR.CRPER_NOMBRES ||' '|| PR.CRPER_APELLIDO_PATERNO INTO TMP_NOMBRES
	FROM SII.CGG_RES_PERSONA PR
	INNER JOIN SII.CGG_USUARIO US ON(US.CRPER_CODIGO= PR.CRPER_CODIGO)		
	WHERE CRPER_ESTADO = TRUE 		
	AND US.CUSU_NOMBRE_USUARIO = IN_CJPJU_USUARIO;
	RETURN TMP_NOMBRES;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;
