/**
* FUNCION SII.F_CGG_JUR_ADJUNTO_TEMPORAL_ADJUNTO_ACUERDO
* SELECCIONA TODOS LOS REGISTRO DE LA TABLA SII.CGG_JUR_PROCESO_JUDICIAL.
* @param IN_CRATE_DATA INFORMACION DEL ADJUNTO TEMPORAL
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_JUR_ADJUNTO_TEMPORAL_ADJUNTO_ACUERDO(
IN IN_CRATE_DATA  CHARACTER VARYING
) RETURNS CHARACTER VARYING AS
$$
DECLARE
	TMP_ADJUNTO BYTEA;
BEGIN	
	SELECT 		
		ADT.CRATE_ARCHIVO INTO TMP_ADJUNTO
	FROM SII.CGG_RES_ADJUNTO_TEMPORAL ADT
	WHERE ADT.CRATE_ESTADO = TRUE 		
	AND ADT.CRATE_CODIGO = IN_CRATE_DATA;
	RETURN TMP_ADJUNTO;
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;