/**
* FUNCION SII.F_CGG_RES_MOVILIDAD_INGRESO_RESIDENTES_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_MOVILIDAD.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_MOVILIDAD_INGRESO_RESIDENTES_SELECT(
IN IN_USER_NAME VARCHAR(50),
IN IN_START_INDEX INT,
IN IN_LIMIT INT,
IN IN_SORT_FIELD_NAME VARCHAR,
IN IN_DIRECTION VARCHAR,
IN IN_FIND_TEXT TEXT
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'WITH RECURSIVE RESIDENCIAS(CRTST_CODIGO, CRTST_DESCRIPCION) AS (
	    SELECT CRTST_CODIGO, CAST(CRTST_DESCRIPCION As varchar(1000)) FROM CGG_RES_TIPO_SOLICITUD_TRAMITE
	    WHERE CGG_CRTST_CODIGO IS NULL
	    AND CRTST_CODIGO IN (SELECT CGCNF_VALOR_CADENA
				FROM CGG_CONFIGURACION
				WHERE CGCNF_CODIGO IN(''03'',''04''))
	    UNION ALL
	    SELECT TS.CRTST_CODIGO, cast (R.CRTST_DESCRIPCION || ''-'' || TS.CRTST_DESCRIPCION As varchar(1000))
	    FROM CGG_RES_TIPO_SOLICITUD_TRAMITE AS TS, RESIDENCIAS AS R
	    WHERE TS.CGG_CRTST_CODIGO = R.CRTST_CODIGO 
	)
	SELECT	 DISTINCT	
		MV.CRMOV_CODIGO,				
		PR.CRPER_CODIGO,
		PR.CRDID_CODIGO,
		(SELECT CRDID_DESCRIPCION FROM  CGG_RES_DOCUMENTO_IDENTIFICACIO DI WHERE DI.CRDID_CODIGO = PR.CRDID_CODIGO) DOCUMENTO,
		PR.CRPER_NUM_DOC_IDENTIFIC,
		PR.CRPER_NUMERO_RESIDENCIA,
		PR.CRPER_NOMBRES,
		PR.CRPER_APELLIDO_PATERNO,
		PR.CRPER_APELLIDO_MATERNO,
		COALESCE(PR.CRPER_GENERO,0) CRPER_GENERO,
		PR.CRPER_FECHA_NACIMIENTO,
		PR.CGNCN_CODIGO,		
		(SELECT CGNCN_NACIONALIDAD FROM  CGG_NACIONALIDAD NC WHERE NC.CGNCN_CODIGO = PR.CGNCN_CODIGO) NACIONALIDAD,
		MV.CRALN_CODIGO, 
		(SELECT CRALN_NOMBRE FROM  CGG_RES_AEROLINEA AL WHERE AL.CRALN_CODIGO = MV.CRALN_CODIGO) AEROLINEA,		
		MV.CARPT_CODIGO, 
		(SELECT CARPT_NOMBRE FROM  CGG_RES_AEROPUERTO AR WHERE AR.CARPT_CODIGO = MV.CARPT_CODIGO) AEROPUER_ORIGEN,
		MV.CGG_CARPT_CODIGO, 
		(SELECT CARPT_NOMBRE FROM  CGG_RES_AEROPUERTO AR WHERE AR.CARPT_CODIGO = MV.CGG_CARPT_CODIGO) AEROPUER_DESTINO,						
		MV.CRMOV_FECHA_VIAJE,
		MV.CRMOV_FECHA_INSERT,
		MV.CRMOV_TIPO_OPERACION, 
		MV.CRMOV_NUMERO_VUELO, 
		MV.CRMOV_OBSERVACION, 	
		MV.CRMOV_TIPO_SALIDA,
		TRS.CRTST_DESCRIPCION TIPO_RESIDENCIA 
		--SII.F_TRAMITE_TIPO(RS.CRTST_CODIGO) TIPO_RESIDENCIA 		
	FROM SII.CGG_RES_MOVILIDAD MV			
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = MV.CRPER_CODIGO AND 
		PR.CRPER_NUMERO_RESIDENCIA IS NOT NULL AND 
		PR.CRPER_ESTADO AND 
		NOT PR.CRPER_ESTADO_INTERFECTO)
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON RS.CRRSD_CODIGO = MV.CRRSD_CODIGO 
	INNER JOIN  RESIDENCIAS TRS ON TRS.CRTST_CODIGO = RS.CRTST_CODIGO
	WHERE CRMOV_ESTADO AND (LENGTH('||QUOTE_LITERAL(IN_FIND_TEXT)||') = 0 OR SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	CASE WHEN PR.CRPER_NUM_DOC_IDENTIFIC IS NULL THEN '''' ELSE PR.CRPER_NUM_DOC_IDENTIFIC END ||'' ''||
	CASE WHEN PR.CRPER_NUMERO_RESIDENCIA IS NULL THEN '''' ELSE PR.CRPER_NUMERO_RESIDENCIA END ||'' ''||
	CASE WHEN PR.CRPER_NOMBRES IS NULL THEN '''' ELSE PR.CRPER_NOMBRES END ||'' ''||
	CASE WHEN PR.CRPER_APELLIDO_PATERNO IS NULL THEN '''' ELSE PR.CRPER_APELLIDO_PATERNO END ||'' ''||
	CASE WHEN PR.CRPER_APELLIDO_MATERNO IS NULL THEN '''' ELSE PR.CRPER_APELLIDO_MATERNO END ||'' ''||
	CASE WHEN PR.CRPER_GENERO IS NULL THEN 0 ELSE PR.CRPER_GENERO END ||'' ''||
	CASE WHEN PR.CRPER_FECHA_NACIMIENTO IS NULL THEN CURRENT_TIMESTAMP ELSE PR.CRPER_FECHA_NACIMIENTO END ||'' ''||	
	CASE WHEN MV.CGG_CARPT_CODIGO IS NULL THEN '''' ELSE MV.CGG_CARPT_CODIGO END ||'' ''||	
	CASE WHEN MV.CRMOV_FECHA_VIAJE IS NULL THEN CURRENT_TIMESTAMP ELSE MV.CRMOV_FECHA_VIAJE END ||'' ''||
	CASE WHEN MV.CRMOV_TIPO_OPERACION IS NULL THEN 0 ELSE MV.CRMOV_TIPO_OPERACION END ||'' ''||
	CASE WHEN MV.CRMOV_NUMERO_VUELO IS NULL THEN '''' ELSE MV.CRMOV_NUMERO_VUELO END ||'' ''||
	CASE WHEN MV.CRMOV_OBSERVACION IS NULL THEN '''' ELSE MV.CRMOV_OBSERVACION END ) = 1)
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_MOVILIDAD_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_RES_MOVILIDAD.
* QUE CUMPLEN CON EL CRITERIO DE BUSQUEDA.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TOTAL DE REGISTROS
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_MOVILIDAD_INGRESO_RESIDENTES_COUNT(
IN IN_FIND_TEXT TEXT
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INTEGER;
BEGIN
				
	WITH RECURSIVE RESIDENCIAS(CRTST_CODIGO, CRTST_DESCRIPCION) AS (
	   SELECT CRTST_CODIGO, CAST(CRTST_DESCRIPCION As varchar(1000)) FROM CGG_RES_TIPO_SOLICITUD_TRAMITE
	    WHERE CGG_CRTST_CODIGO IS NULL
	    AND CRTST_CODIGO IN (SELECT CGCNF_VALOR_CADENA
				FROM CGG_CONFIGURACION
				WHERE CGCNF_CODIGO IN('03','04'))
	    UNION ALL
	    SELECT TS.CRTST_CODIGO, cast (R.CRTST_DESCRIPCION || '-' || TS.CRTST_DESCRIPCION As varchar(1000))
	    FROM CGG_RES_TIPO_SOLICITUD_TRAMITE AS TS, RESIDENCIAS AS R
	    WHERE TS.CGG_CRTST_CODIGO = R.CRTST_CODIGO 
	)
	SELECT	 COUNT(*) INTO TMP_ROWS	
	FROM SII.CGG_RES_MOVILIDAD MV			
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = MV.CRPER_CODIGO AND 
		PR.CRPER_NUMERO_RESIDENCIA IS NOT NULL AND 
		PR.CRPER_ESTADO AND 
		NOT PR.CRPER_ESTADO_INTERFECTO)
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON RS.CRRSD_CODIGO = MV.CRRSD_CODIGO 
	INNER JOIN  RESIDENCIAS TRS ON TRS.CRTST_CODIGO = RS.CRTST_CODIGO
	WHERE CRMOV_ESTADO
	
	AND (LENGTH(IN_FIND_TEXT) = 0 OR SII.F_STRING_IN(IN_FIND_TEXT,
	CASE WHEN PR.CRPER_NUM_DOC_IDENTIFIC IS NULL THEN '' ELSE PR.CRPER_NUM_DOC_IDENTIFIC END ||''||
	CASE WHEN PR.CRPER_NOMBRES IS NULL THEN '' ELSE PR.CRPER_NOMBRES END ||''||
	CASE WHEN PR.CRPER_APELLIDO_PATERNO IS NULL THEN '' ELSE PR.CRPER_APELLIDO_PATERNO END ||''||
	CASE WHEN PR.CRPER_GENERO IS NULL THEN 0 ELSE PR.CRPER_GENERO END ||''||
	CASE WHEN PR.CRPER_FECHA_NACIMIENTO IS NULL THEN CURRENT_TIMESTAMP ELSE PR.CRPER_FECHA_NACIMIENTO END ||''||	
	CASE WHEN MV.CRMOV_FECHA_VIAJE IS NULL THEN CURRENT_TIMESTAMP ELSE MV.CRMOV_FECHA_VIAJE END ||''||
	CASE WHEN MV.CRMOV_TIPO_OPERACION IS NULL THEN 0 ELSE MV.CRMOV_TIPO_OPERACION END ||''||
	CASE WHEN MV.CRMOV_NUMERO_VUELO IS NULL THEN '' ELSE MV.CRMOV_NUMERO_VUELO END ||''||
	CASE WHEN MV.CRMOV_OBSERVACION IS NULL THEN '' ELSE MV.CRMOV_OBSERVACION END ||''||
	CASE WHEN PR.CRDID_CODIGO IS NULL THEN '' ELSE PR.CRDID_CODIGO END ) = 1);
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;


/**
* FUNCION SII.F_CGG_RES_MOVILIDAD__SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_MOVILIDAD.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC 
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_MOVILIDAD_SALIDA_RESIDENTE_SELECT(
IN IN_USER_NAME VARCHAR(50),
IN IN_START_INDEX INT,
IN IN_LIMIT INT,
IN IN_SORT_FIELD_NAME VARCHAR,
IN IN_DIRECTION VARCHAR,
IN IN_FIND_TEXT TEXT
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT		
		MV.CRMOV_CODIGO,				
		PR.CRPER_CODIGO,
		PR.CRDID_CODIGO,
		(SELECT CRDID_DESCRIPCION FROM  CGG_RES_DOCUMENTO_IDENTIFICACIO DI WHERE DI.CRDID_CODIGO = PR.CRDID_CODIGO) DOCUMENTO,
		PR.CRPER_NUM_DOC_IDENTIFIC,
		PR.CRPER_NUMERO_RESIDENCIA,
		PR.CRPER_NOMBRES,
		PR.CRPER_APELLIDO_PATERNO,
		PR.CRPER_GENERO,
		PR.CRPER_FECHA_NACIMIENTO,
		PR.CGNCN_CODIGO,		
		(SELECT CGNCN_NACIONALIDAD FROM  CGG_NACIONALIDAD NC WHERE NC.CGNCN_CODIGO = PR.CGNCN_CODIGO) NACIONALIDAD,
		MV.CRALN_CODIGO, 
		(SELECT CRALN_NOMBRE FROM  CGG_RES_AEROLINEA AL WHERE AL.CRALN_CODIGO = MV.CRALN_CODIGO) AEROLINEA,		
		MV.CARPT_CODIGO, 
		(SELECT CARPT_NOMBRE FROM  CGG_RES_AEROPUERTO AR WHERE AR.CARPT_CODIGO = MV.CARPT_CODIGO) AEROPUER_ORIGEN,
		MV.CGG_CARPT_CODIGO, 
		(SELECT CARPT_NOMBRE FROM  CGG_RES_AEROPUERTO AR WHERE AR.CARPT_CODIGO = MV.CGG_CARPT_CODIGO) AEROPUER_DESTINO,						
		MV.CRMOV_FECHA_VIAJE, 
		MV.CRMOV_TIPO_OPERACION, 
		MV.CRMOV_NUMERO_VUELO, 
		MV.CRMOV_OBSERVACION, 	
		MV.CRMOV_TIPO_SALIDA	
		FROM SII.CGG_RES_MOVILIDAD MV			
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = MV.CRPER_CODIGO)	
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON (RS.CRPER_CODIGO = PR.CRPER_CODIGO)	
	WHERE CRMOV_ESTADO = TRUE AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	CASE WHEN MV.CRMOV_CODIGO IS NULL THEN '''' ELSE MV.CRMOV_CODIGO END ||'' ''||	
	CASE WHEN PR.CRPER_CODIGO IS NULL THEN '''' ELSE PR.CRPER_CODIGO END ||'' ''||
	CASE WHEN PR.CRDID_CODIGO IS NULL THEN '''' ELSE PR.CRDID_CODIGO END ||'' ''||
	CASE WHEN PR.CRPER_NUM_DOC_IDENTIFIC IS NULL THEN '''' ELSE PR.CRPER_NUM_DOC_IDENTIFIC END ||'' ''||
	CASE WHEN PR.CRPER_NOMBRES IS NULL THEN '''' ELSE PR.CRPER_NOMBRES END ||'' ''||
	CASE WHEN PR.CRPER_APELLIDO_PATERNO IS NULL THEN '''' ELSE PR.CRPER_APELLIDO_PATERNO END ||'' ''||
	CASE WHEN PR.CRPER_GENERO IS NULL THEN 0 ELSE PR.CRPER_GENERO END ||'' ''||
	CASE WHEN PR.CGNCN_CODIGO IS NULL THEN '''' ELSE PR.CGNCN_CODIGO END ||'' ''||
	CASE WHEN PR.CRPER_FECHA_NACIMIENTO IS NULL THEN CURRENT_TIMESTAMP ELSE PR.CRPER_FECHA_NACIMIENTO END ||'' ''||	
	CASE WHEN MV.CRALN_CODIGO IS NULL THEN '''' ELSE MV.CRALN_CODIGO END ||'' ''||
	CASE WHEN MV.CARPT_CODIGO IS NULL THEN '''' ELSE MV.CARPT_CODIGO END ||'' ''||
	CASE WHEN MV.CGG_CARPT_CODIGO IS NULL THEN '''' ELSE MV.CGG_CARPT_CODIGO END ||'' ''||	
	CASE WHEN MV.CRMOV_FECHA_VIAJE IS NULL THEN CURRENT_TIMESTAMP ELSE MV.CRMOV_FECHA_VIAJE END ||'' ''||
	CASE WHEN MV.CRMOV_TIPO_OPERACION IS NULL THEN 0 ELSE MV.CRMOV_TIPO_OPERACION END ||'' ''||
	CASE WHEN MV.CRMOV_NUMERO_VUELO IS NULL THEN '''' ELSE MV.CRMOV_NUMERO_VUELO END ||'' ''||
	CASE WHEN MV.CRMOV_OBSERVACION IS NULL THEN '''' ELSE MV.CRMOV_OBSERVACION END ||'' ''||
	CASE WHEN PR.CRDID_CODIGO IS NULL THEN '''' ELSE PR.CRDID_CODIGO END 	) = 1
	AND MV.CRMOV_TIPO_OPERACION = 1
	AND RS.CRRSD_VIGENTE = TRUE
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_MOVILIDAD_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_RES_MOVILIDAD.
* @return INT
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_MOVILIDAD_SALIDA_RESIDENTE_COUNT(
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_RES_MOVILIDAD MV			
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = MV.CRPER_CODIGO)	
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON (RS.CRPER_CODIGO = PR.CRPER_CODIGO)	
	WHERE CRMOV_ESTADO = TRUE AND MV.CRMOV_TIPO_OPERACION = 0
	AND RS.CRRSD_VIGENTE = TRUE;
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_MOVILIDAD_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_RES_MOVILIDAD.
* QUE CUMPLEN CON EL CRITERIO DE BUSQUEDA.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TOTAL DE REGISTROS
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_MOVILIDAD_SALIDA_RESIDENTE_COUNT(
IN IN_FIND_TEXT TEXT
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_RES_MOVILIDAD MV			
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO = MV.CRPER_CODIGO)	
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON (RS.CRPER_CODIGO = PR.CRPER_CODIGO)	
	WHERE CRMOV_ESTADO = TRUE AND SII.F_STRING_IN(IN_FIND_TEXT,
	CASE WHEN MV.CRMOV_CODIGO IS NULL THEN '''' ELSE MV.CRMOV_CODIGO END ||''||	
	CASE WHEN PR.CRPER_CODIGO IS NULL THEN '''' ELSE PR.CRPER_CODIGO END ||''||
	CASE WHEN PR.CRDID_CODIGO IS NULL THEN '''' ELSE PR.CRDID_CODIGO END ||''||
	CASE WHEN PR.CRPER_NUM_DOC_IDENTIFIC IS NULL THEN '''' ELSE PR.CRPER_NUM_DOC_IDENTIFIC END ||''||
	CASE WHEN PR.CRPER_NOMBRES IS NULL THEN '''' ELSE PR.CRPER_NOMBRES END ||''||
	CASE WHEN PR.CRPER_APELLIDO_PATERNO IS NULL THEN '''' ELSE PR.CRPER_APELLIDO_PATERNO END ||''||
	CASE WHEN PR.CRPER_GENERO IS NULL THEN 0 ELSE PR.CRPER_GENERO END ||''||
	CASE WHEN PR.CGNCN_CODIGO IS NULL THEN '''' ELSE PR.CGNCN_CODIGO END ||''||
	CASE WHEN PR.CRPER_FECHA_NACIMIENTO IS NULL THEN CURRENT_TIMESTAMP ELSE PR.CRPER_FECHA_NACIMIENTO END ||''||	
	CASE WHEN RG.CRALN_CODIGO IS NULL THEN '''' ELSE RG.CRALN_CODIGO END ||''||
	CASE WHEN RG.CARPT_CODIGO IS NULL THEN '''' ELSE RG.CARPT_CODIGO END ||''||
	CASE WHEN RG.CGG_CARPT_CODIGO IS NULL THEN '''' ELSE RG.CGG_CARPT_CODIGO END ||''||	
	CASE WHEN MV.CRMOV_FECHA_VIAJE IS NULL THEN CURRENT_TIMESTAMP ELSE MV.CRMOV_FECHA_VIAJE END ||''||
	CASE WHEN MV.CRMOV_TIPO_OPERACION IS NULL THEN 0 ELSE MV.CRMOV_TIPO_OPERACION END ||''||
	CASE WHEN MV.CRMOV_NUMERO_VUELO IS NULL THEN '''' ELSE MV.CRMOV_NUMERO_VUELO END ||''||
	CASE WHEN MV.CRMOV_OBSERVACION IS NULL THEN '''' ELSE MV.CRMOV_OBSERVACION END ||''||
	CASE WHEN PR.CRDID_CODIGO IS NULL THEN '''' ELSE PR.CRDID_CODIGO END 	) = 1
	AND MV.CRMOV_TIPO_OPERACION = 0
	AND RS.CRRSD_VIGENTE = TRUE;
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;
