/** FUNCION SII.F_CGG_JUR_HISTORIAL_PROCESO_UPDATE_PROCESO
* ACTUALIZA UN REGISTRO EN LA TABLA SII.CGG_JUR_PROCESO_JUDICIAL.
* @param IN_CJPJU_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE PROCESO JUDICIAL
* @param IN_CJPJU_ESTADO_EJECUCION ESTADO DE LA EJECUCION DEL PROCESO
0 - PLANTEADO
1 - EN PROCESO
2 - FINALIZADO
3 - SUSPENDIDO
* @param IN_CJPJU_USUARIO_UPDATE USUARIO QUE REALIZO LA ACTUALIZACION DE LA INFORMACION
* @return VOID
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_JUR_HISTORIAL_PROCESO_UPDATE_PROCESO(
IN IN_CJPJU_CODIGO SII.CGG_JUR_PROCESO_JUDICIAL.CJPJU_CODIGO%TYPE,
IN IN_CJPJU_ESTADO_EJECUCION SII.CGG_JUR_PROCESO_JUDICIAL.CJPJU_ESTADO_EJECUCION%TYPE,
IN IN_CJPJU_USUARIO_UPDATE SII.CGG_JUR_PROCESO_JUDICIAL.CJPJU_USUARIO_UPDATE%TYPE
)RETURNS VOID AS
$$
BEGIN
	UPDATE SII.CGG_JUR_PROCESO_JUDICIAL SET
		CJPJU_ESTADO_EJECUCION = IN_CJPJU_ESTADO_EJECUCION, 		
		CJPJU_FECHA_UPDATE = CURRENT_TIMESTAMP, 
		CJPJU_USUARIO_UPDATE = IN_CJPJU_USUARIO_UPDATE
	WHERE
		CJPJU_CODIGO = IN_CJPJU_CODIGO;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;


/** FUNCION SII.F_CGG_JUR_HISTORIAL_ACUERDO_UPDATE_ACUERDO
* ACTUALIZA UN REGISTRO EN LA TABLA SII.CGG_JUR_ACUERDO.
* @param IN_CJACU_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE ACUERDO DE CONTRATO O CONVENIO
* @param IN_CJACU_ESTADO_EJECUCION ESTADO DE LA EJECUCION DEL ACUERDO
0 - FIRMADO
1 - EN PROCESO
2 - FINALIZADO
3 - SUSPENDIDO
* @param IN_CJACU_USUARIO_UPDATE USUARIO QUE REALIZO LA ACTUALIZACION DE LA INFORMACION
* @return VOID
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_JUR_HISTORIAL_ACUERDO_UPDATE_ACUERDO(
IN IN_CJACU_CODIGO SII.CGG_JUR_ACUERDO.CJACU_CODIGO%TYPE,
IN IN_CJACU_ESTADO_EJECUCION SII.CGG_JUR_ACUERDO.CJACU_ESTADO_EJECUCION%TYPE,
IN IN_CJACU_USUARIO_UPDATE SII.CGG_JUR_ACUERDO.CJACU_USUARIO_UPDATE%TYPE
)RETURNS VOID AS
$$
BEGIN
	UPDATE SII.CGG_JUR_ACUERDO SET
		CJACU_ESTADO_EJECUCION = IN_CJACU_ESTADO_EJECUCION, 
		CJACU_FECHA_UPDATE = CURRENT_TIMESTAMP, 
		CJACU_USUARIO_UPDATE = IN_CJACU_USUARIO_UPDATE
	WHERE
		CJACU_CODIGO = IN_CJACU_CODIGO;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;