/**
* FUNCION F_CGG_GENERA_NUM_CONVENIO
* GENERA EL NUMERO DE CONVENIO.
* @return CHARACTER VARYING
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_GENERA_NUM_CONVENIO()
  RETURNS CHARACTER VARYING AS
$BODY$
DECLARE
	TMP_SECUENCIA CHARACTER VARYING;
	TMP_ANIO CHARACTER VARYING;
	TMP_ACRONIMO CHARACTER VARYING;	
BEGIN
	SELECT COUNT(CJACU_NUMERO )+1 INTO TMP_SECUENCIA  
	FROM SII.CGG_JUR_ACUERDO
	WHERE CJACU_TIPO=0
	AND EXTRACT(YEAR FROM CJACU_FECHA_INSERT) = EXTRACT(YEAR FROM CURRENT_TIMESTAMP);
	
	SELECT CGCNF_VALOR_CADENA INTO TMP_ACRONIMO
	FROM SII.CGG_CONFIGURACION WHERE CGCNF_CODIGO = 'CONF27';
	
	SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP) INTO TMP_ANIO;
	
	RETURN  TMP_ACRONIMO||'-'||TMP_ANIO||'-'||LPAD(TMP_SECUENCIA,4,'0');
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;

 /** FUNCION F_CGG_GENERA_NUM_CONTRATO
* GENERA EL NUMERO DE CONTRATO.
* @return CHARACTER VARYING
*/
  CREATE OR REPLACE FUNCTION SII.F_CGG_GENERA_NUM_CONTRATO()
  RETURNS CHARACTER VARYING AS
$BODY$
DECLARE
	TMP_SECUENCIA CHARACTER VARYING;
	TMP_ANIO CHARACTER VARYING;
	TMP_ACRONIMO CHARACTER VARYING;	
BEGIN
	SELECT COUNT(CJACU_NUMERO )+1 INTO TMP_SECUENCIA  
	FROM SII.CGG_JUR_ACUERDO
	WHERE CJACU_TIPO=1
	AND EXTRACT(YEAR FROM CJACU_FECHA_INSERT) = EXTRACT(YEAR FROM CURRENT_TIMESTAMP);
	
	SELECT CGCNF_VALOR_CADENA INTO TMP_ACRONIMO
	FROM SII.CGG_CONFIGURACION WHERE CGCNF_CODIGO = 'CONF26';
	
	SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP) INTO TMP_ANIO;
	
	RETURN  TMP_ACRONIMO||'-'||TMP_ANIO||'-'||LPAD(TMP_SECUENCIA,4,'0');
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;
