/**
* FUNCION f_numero_minimo_aprobacion
* SELECCIONA UN REGISTROS DE LA TABLA SII.CGG_CGG_CONFIGURACION.
* @return VARCHAR
*/

CREATE OR REPLACE FUNCTION SII.f_numero_minimo_aprobacion()
  RETURNS character varying AS
$BODY$
DECLARE
	TMP_NUMERO_APROBACION VARCHAR;
BEGIN
	TMP_NUMERO_APROBACION := '';	
	SELECT CGCNF_VALOR_NUMERICO INTO TMP_NUMERO_APROBACION
        FROM CGG_CONFIGURACION 
        WHERE CGCNF_CODIGO='CONF34' ;
	RETURN TMP_NUMERO_APROBACION;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100;
