/**
* F_CGG_ATC_BECA_BENEFICIARIO_COUNT
* OBTIENE EL TOTAL DE REGISTROS DE LOS BENEFICIARIOS DE LAS BECAS
* @param IN_CRCOM_CODIGO CODIGO CORRESPONDIENTE A COMITE
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TOTAL DE REGISTROS
*/
CREATE OR REPLACE FUNCTION F_CGG_ATC_BECA_BENEFICIARIO_COUNT(
	IN IN_FIND_TEXT TEXT
)RETURNS INT AS
$$
DECLARE
	TMP_COUNT INT;
BEGIN
	IF (LENGTH( TRIM(IN_FIND_TEXT)) = 0) THEN
		SELECT 
			COUNT(CDBEC_CODIGO) INTO TMP_COUNT
		FROM SII.CGG_DHU_BECA		
		CDBEC_ESTADO;
	ELSE
		SELECT 
			COUNT(CDBEC_CODIGO) INTO TMP_COUNT
		FROM SII.CGG_DHU_BECA B
		/*INNER JOIN SII.CGG_RES_RESOLUCION R ON (S.CRSSC_CODIGO = R.CRSSC_CODIGO)
		WHERE CDBEC_CODIGO = IN_CRCOM_CODIGO AND CRSSC_ESTADO AND CRRES_ESTADO_RESOLUCION IN (0,1,2)
		AND SII.F_STRING_IN(IN_FIND_TEXT,
			COALESCE(CRRES_NUMERO_RESOLUCION, '')||' '||
			COALESCE(CRRES_EXTRACTO_RESOLUCION, '')
		) = 1*/;
	END IF;
	RETURN TMP_COUNT;
END;
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/**
* F_CGG_ATC_BECA_BENEFICIARIO
* SELECCIONA LOS BENEFICIARIOS DE LAS BECAS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION F_CGG_ATC_BECA_BENEFICIARIO(
	IN IN_START_INDEX INT,
	IN IN_LIMIT INT,
	IN IN_SORT_FIELD_NAME VARCHAR,
	IN IN_DIRECTION VARCHAR,
	IN IN_FIND_TEXT TEXT
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT CDBEC_NUMERO,
		COALESCE(P.CRPER_NOMBRES,'''')||'' ''||
		COALESCE(P.CRPER_APELLIDO_PATERNO,'''')||'' ''||
		COALESCE(P.CRPER_APELLIDO_MATERNO,'''')::VARCHAR NOMBRE_BENEFICIARIO,
		CDBEC_FECHA_INICIO,
		CDBEC_FECHA_FIN,
		CDTBC_NOMBRE
	FROM SII.CGG_DHU_BECA B
	INNER JOIN SII.CGG_RES_PERSONA P ON (B.CRPER_CODIGO = P.CRPER_CODIGO)
	INNER JOIN SII.CGG_DHU_TIPO_BECA T ON (B.CDTBC_CODIGO = T.CDTBC_CODIGO)
	WHERE CDBEC.ESTADO
	AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
		COALESCE(NOMBRE_BENEFICIARIO, '''')||'' ''||
		--COALESCE(CDTBC_NOMBRE, '''')||'' ''||
		COALESCE(CDTBC_NOMBRE, '''')
	) = 1
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END;
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;
