/**
* FUNCION SII.F_CGG_RES_PERSONA_TCT_SELECT
* SELECCIONA UN REGISTRO EN LA TABLA SII.CGG_RES_PERSONA
* @param IN_CRPER_NUM_DOC_IDENTIFIC NUMERO DE DOCUMENTO DEL REGISTRO DE PERSONA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_PERSONA_TCT_SELECT(
IN IN_CRPER_NUM_DOC_IDENTIFIC SII.CGG_RES_PERSONA.CRPER_NUM_DOC_IDENTIFIC%TYPE
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT
		CRPER_CODIGO, 		
		CRDID_CODIGO, 
		CRPER_NUM_DOC_IDENTIFIC, 
		CRPER_NOMBRES, 
		CRPER_APELLIDO_PATERNO, 
		CRPER_GENERO, 
		CGNCN_CODIGO, 
		CRPER_FECHA_NACIMIENTO, 		
		CRPER_ESTADO, 
		CRPER_FECHA_INSERT, 
		CRPER_USUARIO_INSERT, 
		CRPER_FECHA_UPDATE, 
		CRPER_USUARIO_UPDATE
	FROM SII.CGG_RES_PERSONA
	WHERE CRPER_ESTADO = TRUE AND 
		CRPER_NUM_DOC_IDENTIFIC = IN_CRPER_NUM_DOC_IDENTIFIC;
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;