/** FUNCION SII.FUNCION F_CGG_OFICIAL_MATRIMONIO_INFORME
* SELECCIONA EL OFICIAL DE MATRIMONIO. 
* @param IN_CRMTR_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE MATRIMONIO
* @return CHARACTER VARYING 
**/
CREATE OR REPLACE FUNCTION SII.F_CGG_OFICIAL_MATRIMONIO_INFORME(
IN IN_CRMTR_CODIGO CHARACTER VARYING )
  RETURNS CHARACTER VARYING AS
$BODY$
DECLARE
	TMP_OFICIAL CHARACTER VARYING;	
BEGIN
	SELECT CROFM_CODIGO INTO TMP_OFICIAL  
	FROM SII.CGG_RES_OFICIAL_MATRIMONIO OM
	INNER JOIN SII.CGG_USUARIO US ON (US.CUSU_CODIGO = OM.CUSU_CODIGO)
	INNER JOIN SII.CGG_RES_MATRIMONIO MT ON (MT.CRMTR_CODIGO = OM.CRMTR_CODIGO)
	WHERE OM.CROFM_ESTADO= TRUE AND OM.CRMTR_CODIGO= IN_CRMTR_CODIGO;
	
	
	RETURN  TMP_OFICIAL;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;

