/** FUNCTION: F_CGG_RES_PERSONA_EXPEDIENTE_COUNT
* CONTABILIZA N REGISTROS DE LA TABLA SII.CGG_RES_PERSONA,CGG_RES_PRESTAMO_EXPEDIENTE.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TMP_ROWS
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_PERSONA_EXPEDIENTE_COUNT(IN_FIND_TEXT TEXT)
  RETURNS INTEGER AS
$BODY$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*)INTO TMP_ROWS
	FROM SII.CGG_RES_PERSONA PER
	WHERE PER.CRPER_NUMERO_EXPEDIENTE IS NOT NULL AND SII.F_STRING_IN(IN_FIND_TEXT,CASE WHEN PER.CRPER_CODIGO IS NULL THEN '''' ELSE PER.CRPER_CODIGO END ||' '||
	CASE WHEN PER.CRPER_NOMBRES IS NULL THEN '''' ELSE PER.CRPER_NOMBRES END ||' '||
	CASE WHEN PER.CRPER_APELLIDO_PATERNO IS NULL THEN '''' ELSE PER.CRPER_APELLIDO_PATERNO END ||' '||
	CASE WHEN PER.CRPER_APELLIDO_MATERNO IS NULL THEN '''' ELSE PER.CRPER_APELLIDO_MATERNO END ||' '||
	CASE WHEN PER.CRPER_NUM_DOC_IDENTIFIC IS NULL THEN '''' ELSE PER.CRPER_NUM_DOC_IDENTIFIC END ||' '||
	CASE WHEN PER.CRPER_FECHA_ARCHIVO IS NULL THEN CURRENT_TIMESTAMP ELSE PER.CRPER_FECHA_ARCHIVO END ||' '||
	CASE WHEN PER.CRPER_NUMERO_EXPEDIENTE IS NULL THEN '''' ELSE PER.CRPER_NUMERO_EXPEDIENTE END) = 1;
	

	RETURN TMP_ROWS;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;