/**
* FUNCION SII.F_CGG_USUARIO_INTERNO_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_USUARIO.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_USUARIO_INTERNO_SELECT(
IN IN_USER_NAME VARCHAR,
IN IN_START_INDEX INT,
IN IN_LIMIT INT,
IN IN_SORT_FIELD_NAME VARCHAR,
IN IN_DIRECTION VARCHAR,
IN IN_FIND_TEXT TEXT
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT
		U.CUSU_CODIGO, 
		U.CRCRG_CODIGO,
		CRG.CRCRG_NOMBRE,
		U.CRPER_CODIGO,
		P.CRPER_NOMBRES,
		P.CRPER_NUM_DOC_IDENTIFIC,
		(P.CRPER_APELLIDO_PATERNO ||'' ''||P.CRPER_APELLIDO_MATERNO)APELLIDOS,
		U.CRPJR_CODIGO,
		PJ.CRPJR_RAZON_SOCIAL,
		U.CCTN_CODIGO,
		C.CCTN_NOMBRE,
		U.CUSU_NOMBRE_USUARIO, 
		U.CUSU_CLAVE_ACCESO, 
		U.CUSU_USUARIO_INTERNO, 
		U.CUSU_CADUCA_CLAVE, 
		U.CUSU_FECHA_CLAVE_ACT, 
		U.CUSU_ACTIVO, 
		U.CUSU_CAMBIAR_CLAVE,
		U.CUSU_ESTADO, 		
		(SELECT CGCNF_VALOR_NUMERICO FROM SII.CGG_CONFIGURACION WHERE CGCNF_CODIGO = ''CONF7'') VIGENCIA,
		EXTRACT (DAYS FROM CURRENT_DATE - CUSU_FECHA_CLAVE_ACT) TRANSCURRIDO,
		U.CISLA_CODIGO,
		ISLA.CISLA_NOMBRE
	FROM SII.CGG_USUARIO U
	LEFT JOIN SII.CGG_RES_PERSONA P ON P.CRPER_CODIGO = U.CRPER_CODIGO
	LEFT JOIN SII.CGG_CANTON C ON C.CCTN_CODIGO = U.CCTN_CODIGO
	LEFT JOIN SII.CGG_RES_PERSONA_JURIDICA PJ ON PJ.CRPJR_CODIGO = U.CRPJR_CODIGO
	LEFT JOIN SII.CGG_RES_CARGO CRG ON CRG.CRCRG_CODIGO = U.CRCRG_CODIGO
	LEFT JOIN SII.CGG_ISLA ISLA ON U.CISLA_CODIGO = ISLA.CISLA_CODIGO 
	WHERE CUSU_ESTADO = TRUE AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	CASE WHEN P.CRPER_NOMBRES IS NULL THEN '''' ELSE P.CRPER_NOMBRES END ||'' ''||
	CASE WHEN P.CRPER_APELLIDO_PATERNO IS NULL THEN '''' ELSE P.CRPER_APELLIDO_PATERNO END ||'' ''||
	CASE WHEN P.CRPER_APELLIDO_MATERNO IS NULL THEN '''' ELSE P.CRPER_APELLIDO_MATERNO END ||'' ''||
	CASE WHEN P.CRPER_NUM_DOC_IDENTIFIC IS NULL THEN '''' ELSE P.CRPER_NUM_DOC_IDENTIFIC END ||'' ''||
	CASE WHEN PJ.CRPJR_RAZON_SOCIAL IS NULL THEN '''' ELSE PJ.CRPJR_RAZON_SOCIAL END ||'' ''||
	CASE WHEN CUSU_NOMBRE_USUARIO IS NULL THEN '''' ELSE CUSU_NOMBRE_USUARIO END ||'' ''||
	CASE WHEN CUSU_CLAVE_ACCESO IS NULL THEN '''' ELSE CUSU_CLAVE_ACCESO END ||'' ''||
	CASE WHEN CUSU_USUARIO_INTERNO IS NULL THEN FALSE ELSE CUSU_USUARIO_INTERNO END ||'' ''||
	CASE WHEN CUSU_CADUCA_CLAVE IS NULL THEN FALSE ELSE CUSU_CADUCA_CLAVE END ||'' ''|| 
	COALESCE(ISLA.CISLA_NOMBRE,'''') ) = 1
	AND U.CUSU_USUARIO_INTERNO = TRUE
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_USUARIO_INTERNO_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_USUARIO.
* @return INT
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_USUARIO_INTERNO_COUNT(
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_USUARIO U
	WHERE CUSU_ESTADO = TRUE
	AND U.CUSU_USUARIO_INTERNO = TRUE;
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_USUARIO_INTERNO_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_USUARIO.
* QUE CUMPLEN CON EL CRITERIO DE BUSQUEDA.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TOTAL DE REGISTROS.
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_USUARIO_INTERNO_COUNT(
IN IN_FIND_TEXT TEXT
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_USUARIO U
	WHERE CUSU_ESTADO = TRUE AND SII.F_STRING_IN(IN_FIND_TEXT,CASE WHEN CUSU_NOMBRE_USUARIO IS NULL THEN '''' ELSE CUSU_NOMBRE_USUARIO END ||' '||CASE WHEN CUSU_CLAVE_ACCESO IS NULL THEN '''' ELSE CUSU_CLAVE_ACCESO END ||' '||CASE WHEN CUSU_USUARIO_INTERNO IS NULL THEN FALSE ELSE CUSU_USUARIO_INTERNO END ||' '||CASE WHEN CUSU_CADUCA_CLAVE IS NULL THEN FALSE ELSE CUSU_CADUCA_CLAVE END ||' '||CASE WHEN CUSU_ESTADO IS NULL THEN FALSE ELSE CUSU_ESTADO END ||' '||CASE WHEN CUSU_FECHA_INSERT IS NULL THEN CURRENT_TIMESTAMP ELSE CUSU_FECHA_INSERT END ||' '||CASE WHEN CUSU_USUARIO_INSERT IS NULL THEN '''' ELSE CUSU_USUARIO_INSERT END ||' '||CASE WHEN CUSU_FECHA_UPDATE IS NULL THEN CURRENT_TIMESTAMP ELSE CUSU_FECHA_UPDATE END ||' '||CASE WHEN CUSU_USUARIO_UPDATE IS NULL THEN '''' ELSE CUSU_USUARIO_UPDATE END ) = 1
	AND U.CUSU_USUARIO_INTERNO = TRUE;
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;