/** FUNCION F_CGG_GENERA_NUM_NOTIFICACION
* GENERA EL NUMERO SECUENCIAL PARA EL REGISTRO DE NOTIFICACION.
* @return REFCURSOR
*/

CREATE OR REPLACE FUNCTION F_CGG_GENERA_NUM_NOTIFICACION()
  RETURNS CHARACTER VARYING AS
$BODY$
DECLARE
	TMP_SECUENCIA CHARACTER VARYING;
	TMP_ANIO CHARACTER VARYING;
	TMP_ACRONIMO CHARACTER VARYING;	
BEGIN
	SELECT COUNT(CRNOT_NUMERO_NOTIFICACION)+1 INTO TMP_SECUENCIA
	FROM SII.CGG_RES_NOTIFICACION
	WHERE EXTRACT(YEAR FROM CRNOT_FECHA_INSERT) = EXTRACT(YEAR FROM CURRENT_TIMESTAMP);
	
	SELECT CGCNF_VALOR_CADENA INTO TMP_ACRONIMO
	FROM SII.CGG_CONFIGURACION WHERE CGCNF_CODIGO = 'CONF12';
	
	SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP) INTO TMP_ANIO;
	
	RETURN  TMP_ACRONIMO||'-'||TMP_ANIO||'-'||LPAD(TMP_SECUENCIA,4,'0');
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;
ALTER FUNCTION F_CGG_GENERA_NUM_NOTIFICACION() OWNER TO SII;
