
/**
* FUNCTION: F_CGG_RES_PERSONA_CONSULTA_COUNT
* CONTABILIZA UN REGISTROS DE LA TABLA SII.CGG_RES_PERSONA DEACUERDO AL CRITERIO DE BUSQUEDA.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* return TMP_ROWS
*/

CREATE OR REPLACE FUNCTION F_CGG_RES_PERSONA_CONSULTA_COUNT(IN_FIND_TEXT TEXT)
  RETURNS INTEGER AS
$BODY$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(  PER.CRPER_CODIGO,
                       PER.CRECV_CODIGO,
                       PER.CRDID_CODIGO,
                       PER.CGNCN_CODIGO,
                       PER.CPRR_CODIGO,
                       OPER.CCTN_CODIGO,
                       PER.CGG_CCTN_CODIGO,
					   PER.CRPER_NOMBRES,
					   PER.CRPER_APELLIDO_PATERNO,
					   PER.CRPER_APELLIDO_MATERNO,
					   PER.CRPER_NUM_DOC_IDENTIFIC,
					   PER.CRPER_NUMERO_RESIDENCIA,
					   PER.CRPER_FECHA_NACIMIENTO,
					   PER.CRPER_LUGAR_NACIMIENTO,
					   PER.CRPER_GENERO,
					   PER.CRPER_AUTORIZADO,
					   PER.CRPER_TIPO_PERSONA,
					   PER.CRPER_TIPO,
					   PER.CRPER_FOTO
	) INTO TMP_ROWS
	FROM SII.CGG_RES_PERSONA PER
	WHERE PER.CRPER_ESTADO AND (LENGTH(IN_FIND_TEXT) = 0 OR SII.F_STRING_IN(IN_FIND_TEXT,
	CASE WHEN PER.CRPER_CODIGO IS NULL THEN '''' ELSE PER.CRPER_CODIGO END ||' '||
	CASE WHEN PER.CRECV_CODIGO IS NULL THEN '''' ELSE PER.CRECV_CODIGO END ||' '||
	CASE WHEN PER.CRDID_CODIGO IS NULL THEN '''' ELSE PER.CRDID_CODIGO END ||' '||
	CASE WHEN PER.CGNCN_CODIGO IS NULL THEN '''' ELSE PER.CGNCN_CODIGO END ||' '||
	CASE WHEN PER.CPRR_CODIGO IS NULL THEN '''' ELSE PER.CPRR_CODIGO END ||' '||
	CASE WHEN PER.CCTN_CODIGO IS NULL THEN '''' ELSE PER.CCTN_CODIGO END ||' '||
	CASE WHEN PER.CGG_CCTN_CODIGO IS NULL THEN '''' ELSE PER.CGG_CCTN_CODIGO END ||' '||
	CASE WHEN PER.CRPER_NOMBRES IS NULL THEN '''' ELSE PER.CRPER_NOMBRES END ||' '||
	CASE WHEN PER.CRPER_APELLIDO_PATERNO IS NULL THEN '''' ELSE PER.CRPER_APELLIDO_PATERNO END ||' '||
	CASE WHEN PER.CRPER_APELLIDO_MATERNO IS NULL THEN '''' ELSE PER.CRPER_APELLIDO_MATERNO END ||' '||
	CASE WHEN PER.CRPER_NUM_DOC_IDENTIFIC IS NULL THEN '''' ELSE PER.CRPER_NUM_DOC_IDENTIFIC END ||' '||
	CASE WHEN PER.CRPER_FECHA_NACIMIENTO IS NULL THEN CURRENT_TIMESTAMP ELSE PER.CRPER_FECHA_NACIMIENTO END ||' '||
	CASE WHEN PER.CRPER_LUGAR_NACIMIENTO IS NULL THEN '''' ELSE PER.CRPER_LUGAR_NACIMIENTO END ||' '||
	CASE WHEN PER.CRPER_GENERO IS NULL THEN 0 ELSE PER.CRPER_GENERO END ||' '||
	CASE WHEN PER.CRPER_NUMERO_RESIDENCIA IS NULL THEN '''' ELSE PER.CRPER_NUMERO_RESIDENCIA END ||' '||
	CASE WHEN PER.CRPER_AUTORIZADO IS NULL THEN FALSE ELSE PER.CRPER_AUTORIZADO END ||' '||
	CASE WHEN PER.CRPER_TIPO_PERSONA IS NULL THEN 0 ELSE PER.CRPER_TIPO_PERSONA END ||' '||
	CASE WHEN PER.CRPER_TIPO IS NULL THEN 0 ELSE PER.CRPER_TIPO END ||' '||
	CASE WHEN PER.CRPER_ESTADO IS NULL THEN FALSE ELSE PER.CRPER_ESTADO END ||' '||
	CASE WHEN PER.CRPER_FECHA_INSERT IS NULL THEN CURRENT_TIMESTAMP ELSE PER.CRPER_FECHA_INSERT END ||' '||
	CASE WHEN PER.CRPER_USUARIO_INSERT IS NULL THEN '''' ELSE PER.CRPER_USUARIO_INSERT END ||' '||
	CASE WHEN PER.CRPER_FECHA_UPDATE IS NULL THEN CURRENT_TIMESTAMP ELSE PER.CRPER_FECHA_UPDATE END ||' '||
	CASE WHEN PER.CRPER_USUARIO_UPDATE IS NULL THEN '''' ELSE PER.CRPER_USUARIO_UPDATE END ) = 1);
	RETURN TMP_ROWS;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;
ALTER FUNCTION F_CGG_RES_PERSONA_CONSULTA_COUNT(TEXT) OWNER TO SII;