/**
* FUNCION f_cgg_dhu_beca_seguimiento_academico_select
* INGRESA UN REGISTRO EN LA TABLA SII.CGG_DHU_SEGUIMIENTO_ACADEMICO.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC 
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return refcursor
*/
CREATE OR REPLACE FUNCTION f_cgg_dhu_beca_seguimiento_academico_select(in_user_name character varying, in_start_index integer, in_limit integer, in_sort_field_name character varying, in_direction character varying, in_find_text text)
  RETURNS SETOF refcursor AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT
		BEC.CDBEC_CODIGO,
		(SELECT CRPER_NOMBRES FROM SII.CGG_RES_PERSONA WHERE CRPER_CODIGO =BEC.CRPER_CODIGO) AS CRPER_NOMBRES,
		(SELECT CRPER_APELLIDO_PATERNO||'' ''||CRPER_APELLIDO_MATERNO FROM SII.CGG_RES_PERSONA WHERE CRPER_CODIGO = BEC.CRPER_CODIGO) AS CRPER_APELLIDOS_PERSONA,
		(SELECT CRPER_NUM_DOC_IDENTIFIC FROM SII.CGG_RES_PERSONA WHERE CRPER_CODIGO = BEC.CRPER_CODIGO) AS CRPER_NUM_DOC_IDENTIFIC,
		(SELECT CDTBC_CODIGO FROM SII.CGG_DHU_TIPO_BECA TBC WHERE TBC.CDTBC_CODIGO = BEC.CDTBC_CODIGO) AS CDTBC_CODIGO,
		(SELECT CDTBC_NOMBRE FROM SII.CGG_DHU_TIPO_BECA TBC WHERE TBC.CDTBC_CODIGO = BEC.CDTBC_CODIGO) AS CDBEC_TIPO_BECA,
		(SELECT ESP.CGESP_NOMBRE FROM SII.CGG_ESPECIALIDAD ESP WHERE ESP.CGESP_CODIGO =BEC.CGESP_CODIGO) AS CGESP_NOMBRE,
		BEC.CDBEC_NUMERO,
		BEC.CDBEC_FUNCIONARIO,
		BEC.CDBEC_NUMERO_CONVENIO, 
		BEC.CDBEC_TIPO_CICLO,
		BEC.CDBEC_TOTAL_CICLOS
	FROM SII.CGG_DHU_BECA BEC
	INNER JOIN SII.CGG_RES_PERSONA PER ON (PER.CRPER_CODIGO=BEC.CRPER_CODIGO)
	LEFT JOIN SII.CGG_DHU_SEGUIMIENTO_ACADEMICO SAC ON(SAC.CDBEC_CODIGO=BEC.CDBEC_CODIGO)
	WHERE BEC.CDBEC_ESTADO = TRUE AND (CDBEC_ESTADO_APROBACION=1 OR CDBEC_ESTADO_APROBACION=2) AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	COALESCE(CDBEC_FUNCIONARIO, '''')||'' ''||
	COALESCE(CDBEC_TOTAL_CICLOS, 0)||'' ''||
	COALESCE(CDBEC_ESTADO_APROBACION, 0)||'' ''||
	COALESCE(CDBEC_ESTADO, FALSE)||'' ''||
	COALESCE(CDBEC_FECHA_INSERT, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CDBEC_USUARIO_INSERT, '''')||'' ''||
	COALESCE(CDBEC_FECHA_UPDATE, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(CDBEC_USUARIO_UPDATE, '''')) = 1
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100
  ROWS 1000;
ALTER FUNCTION f_cgg_dhu_beca_seguimiento_academico_select(character varying, integer, integer, character varying, character varying, text) OWNER TO sii;
