/** FUNCION SII.F_CGG_GENERA_NUM_DENUNCIA
* GENERA EL NUMERO SECUENCIAL PARA EL REGISTRO DE DENUNCIA.
* @param IN_CRDEN_TIPO CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/

CREATE OR REPLACE FUNCTION SII.F_CGG_GENERA_NUM_DENUNCIA(
IN IN_CRDEN_TIPO INT
)
  RETURNS CHARACTER VARYING AS
$BODY$
DECLARE
	TMP_SECUENCIA CHARACTER VARYING;
	TMP_ANIO CHARACTER VARYING;
	TMP_ACRONIMO CHARACTER VARYING;		
BEGIN
	SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP) INTO TMP_ANIO;
	IF IN_CRDEN_TIPO = 0 THEN
		SELECT CGCNF_VALOR_CADENA INTO TMP_ACRONIMO	FROM SII.CGG_CONFIGURACION WHERE CGCNF_CODIGO = 'CONF13';		
	ELSIF IN_CRDEN_TIPO = 1 THEN
		SELECT CGCNF_VALOR_CADENA INTO TMP_ACRONIMO	FROM SII.CGG_CONFIGURACION WHERE CGCNF_CODIGO = 'CONF20';
	END IF;
	
	
	SELECT MAX ( SUBSTRING(CRDEN_NUMERO,LENGTH(CRDEN_NUMERO)-3,5) :: INTEGER )+1 INTO TMP_SECUENCIA 
	FROM SII.CGG_RES_DENUNCIA 
	WHERE CRDEN_TIPO = IN_CRDEN_TIPO
		AND EXTRACT(YEAR FROM CRDEN_FECHA_INSERT) = EXTRACT(YEAR FROM CURRENT_TIMESTAMP);
	IF TMP_SECUENCIA IS NULL THEN
		TMP_SECUENCIA = 1;
	END IF;
	RETURN TMP_ACRONIMO||'-'||TMP_ANIO||'-'||LPAD(TMP_SECUENCIA,4,'0');	
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;
ALTER FUNCTION F_CGG_GENERA_NUM_DENUNCIA(int) OWNER TO SII;