/**
*FUNCION F_CGG_RES_MATRIMONIO_OFICIAL
*SELECCIONA LA INFORMACION DEL OFICIAL DEL MATRIMONIO.
*@param IN_CRMTR_CODIGO IDENTIFICATIVO UNICO DE MATRIMONIO
*@return REFCURSOR
*/

CREATE OR REPLACE FUNCTION F_CGG_RES_MATRIMONIO_OFICIAL(IN_CRMTR_CODIGO CHARACTER VARYING
)
  RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT		
		U.CUSU_CODIGO,
		PER.CRPER_NOMBRES,
		PER.CRPER_APELLIDO_PATERNO||' '||COALESCE(CRPER_APELLIDO_MATERNO,'')
	FROM SII.CGG_USUARIO U		
	INNER JOIN SII.CGG_RES_PERSONA PER ON PER.CRPER_CODIGO = U.CRPER_CODIGO
	INNER JOIN SII.CGG_RES_OFICIAL_MATRIMONIO OM ON (OM.CUSU_CODIGO = U.CUSU_CODIGO)    
	INNER JOIN SII.CGG_RES_MATRIMONIO MT ON (MT.CRMTR_CODIGO = OM.CRMTR_CODIGO)
	WHERE U.CUSU_ESTADO = TRUE  
	AND MT.CRMTR_CODIGO = IN_CRMTR_CODIGO;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100
  ROWS 1000;


