/**
* FUNCION SII.F_CGG_RES_TRAMITE_COMITE
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_TRAMITE.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC 
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param IN_CRSSC_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE SESION
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_TRAMITE_COMITE_SESION(
IN IN_USER_NAME varchar(50),
IN IN_START_INDEX int,
IN IN_LIMIT int,
IN IN_SORT_FIELD_NAME varchar,
IN IN_DIRECTION varchar,
IN IN_FIND_TEXT text,
IN IN_CRSSC_CODIGO VARCHAR
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT		
		TRM.CRTRA_CODIGO,
		TRM.CRTRA_NUMERO, 
		ST.CRTST_CODIGO,
		ST.CRTST_DESCRIPCION, 	
		ET.CRETT_CODIGO, 
		ET.CRETT_NOMBRE,
		CNT.CCTN_NOMBRE CANTON,
		RST.CRRST_CODIGO CRRST_CODIGO
	FROM SII.CGG_RES_TRAMITE TRM
	INNER JOIN SII.CGG_RES_ESTADO_TRAMITE ET ON (ET.CRETT_CODIGO=TRM.CRETT_CODIGO AND ET.CRETT_ESTADO)
	INNER JOIN SII.CGG_RES_TIPO_SOLICITUD_TRAMITE ST ON (ST.CRTST_CODIGO=TRM.CRTST_CODIGO AND ST.CRTST_ESTADO)
	INNER JOIN SII.CGG_ISLA SL ON SL.CISLA_CODIGO = TRM.CISLA_CODIGO AND SL.CISLA_ESTADO
	INNER JOIN SII.CGG_CANTON CNT ON CNT.CCTN_CODIGO = SL.CCTN_CODIGO AND CNT.CCTN_ESTADO
	LEFT JOIN SII.CGG_RES_RESOL_TRAMITE RST ON RST.CRTRA_CODIGO = TRM.CRTRA_CODIGO AND CRRST_ESTADO
	LEFT JOIN SII.CGG_RES_RESOLUCION RSL ON RSL.CRRES_CODIGO = RST.CRRES_CODIGO AND CRRES_ESTADO
	LEFT JOIN SII.CGG_RES_SESION_COMITE SC ON SC.CRSSC_CODIGO = RSL.CRSSC_CODIGO AND SC.CRSSC_ESTADO
	LEFT JOIN SII.CGG_RES_VOTO VT ON VT.CRRES_CODIGO = RSL.CRRES_CODIGO AND VT.CRVTO_ESTADO
	WHERE TRM.CRTRA_ESTADO AND 
		VT.CRVTO_CODIGO IS NULL AND 
		(LENGTH('||QUOTE_LITERAL(IN_FIND_TEXT)||') = 0 OR SII.F_STRING_IN('''||IN_FIND_TEXT||''',COALESCE(CNT.CCTN_NOMBRE, '''')||'' ''||
		COALESCE(TRM.CRTRA_NUMERO,0)||'' ''||
		COALESCE(ST.CRTST_CODIGO,'''')||'' ''||COALESCE(ST.CRTST_DESCRIPCION,'''')||'' ''||COALESCE(ET.CRETT_NOMBRE,'''')) = 1) AND 
		TRM.CRETT_CODIGO = (SELECT CF.CGCNF_VALOR_CADENA FROM SII.CGG_CONFIGURACION CF WHERE CF.CGCNF_CODIGO = ''01'') AND
		(RSL.CRRES_CODIGO IS NULL OR RSL.CRRES_ESTADO_RESOLUCION = 0) AND
		(SC.CRSSC_CODIGO IS NULL OR SC.CRSSC_ESTADO_CONVOCATORIA = 5) AND
		TRM.CRTST_CODIGO IN (SELECT TC.CRTST_CODIGO FROM SII.CGG_RES_SESION_COMITE SC
			INNER JOIN SII.CGG_RES_COMITE CM ON (CM.CRCOM_CODIGO=SC.CRCOM_CODIGO)
			INNER JOIN SII.CGG_RES_TRAMITE_COMITE TC ON TC.CRCOM_CODIGO=CM.CRCOM_CODIGO
			WHERE SC.CRSSC_CODIGO = '||QUOTE_LITERAL(IN_CRSSC_CODIGO)||'
		)
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_TRAMITE_COMITE_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_RES_TRAMITE.
* QUE CUMPLEN CON EL CRITERIO DE BUSQUEDA.
* @param IN_CRSSC_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE SESION
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TOTAL DE REGISTROS
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_TRAMITE_COMITE_SESION_COUNT(
IN IN_CRSSC_CODIGO VARCHAR,
IN IN_FIND_TEXT TEXT
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT;
BEGIN
	SELECT COUNT(TRM.CRTRA_CODIGO
	) INTO TMP_ROWS
	FROM SII.CGG_RES_TRAMITE TRM
	INNER JOIN SII.CGG_RES_ESTADO_TRAMITE ET ON (ET.CRETT_CODIGO=TRM.CRETT_CODIGO)
	INNER JOIN SII.CGG_RES_TIPO_SOLICITUD_TRAMITE ST ON (ST.CRTST_CODIGO=TRM.CRTST_CODIGO)
	INNER JOIN SII.CGG_ISLA SL ON SL.CISLA_CODIGO = TRM.CISLA_CODIGO
	INNER JOIN SII.CGG_CANTON CNT ON CNT.CCTN_CODIGO = SL.CCTN_CODIGO
	LEFT JOIN SII.CGG_RES_RESOL_TRAMITE RST ON RST.CRTRA_CODIGO = TRM.CRTRA_CODIGO AND CRRST_ESTADO
	LEFT JOIN SII.CGG_RES_RESOLUCION RSL ON RSL.CRRES_CODIGO = RST.CRRES_CODIGO AND CRRES_ESTADO
	LEFT JOIN SII.CGG_RES_SESION_COMITE SC ON SC.CRSSC_CODIGO = RSL.CRSSC_CODIGO AND SC.CRSSC_ESTADO
	LEFT JOIN SII.CGG_RES_VOTO VT ON VT.CRRES_CODIGO = RSL.CRRES_CODIGO AND VT.CRVTO_ESTADO
	WHERE TRM.CRTRA_ESTADO AND 
		VT.CRVTO_CODIGO IS NULL AND 
		(LENGTH(IN_FIND_TEXT) = 0 OR SII.F_STRING_IN(IN_FIND_TEXT,COALESCE(CNT.CCTN_NOMBRE, '')||' '||
		COALESCE(TRM.CRTRA_NUMERO,0)||' '||
		COALESCE(ST.CRTST_CODIGO,'')||' '||COALESCE(ST.CRTST_DESCRIPCION,'')||' '||COALESCE(ET.CRETT_NOMBRE,'')) = 1) AND 
		TRM.CRETT_CODIGO = (SELECT CF.CGCNF_VALOR_CADENA FROM SII.CGG_CONFIGURACION CF WHERE CF.CGCNF_CODIGO = '01') AND
		(RSL.CRRES_CODIGO IS NULL OR RSL.CRRES_ESTADO_RESOLUCION = 0) AND
		(SC.CRSSC_CODIGO IS NULL OR SC.CRSSC_ESTADO_CONVOCATORIA = 5) AND
		TRM.CRTST_CODIGO IN (SELECT TC.CRTST_CODIGO FROM SII.CGG_RES_SESION_COMITE SC
			INNER JOIN SII.CGG_RES_COMITE CM ON (CM.CRCOM_CODIGO=SC.CRCOM_CODIGO)
			INNER JOIN SII.CGG_RES_TRAMITE_COMITE TC ON TC.CRCOM_CODIGO=CM.CRCOM_CODIGO
			WHERE SC.CRSSC_CODIGO = IN_CRSSC_CODIGO
		);
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;


/**
* FUNCION SII.F_CGG_RES_TRAMITE_COMITE_SESION_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_TRAMITE.
* @param IN_CRSSC_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE SESION
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_TRAMITE_COMITE_SESION_SELECT(
IN IN_CRSSC_CODIGO SII.CGG_RES_SESION_COMITE.CRSSC_CODIGO%TYPE
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR 
		SELECT
			TRM.CRTRA_CODIGO,
			TRM.CRTRA_NUMERO, 
			ST.CRTST_CODIGO, 
			ST.CRTST_DESCRIPCION,
			CNT.CCTN_NOMBRE CANTON,
			ETT.CRETT_CODIGO,
			ETT.CRETT_NOMBRE,
			RST.CRRST_CODIGO CRRST_CODIGO
			FROM SII.CGG_RES_TRAMITE TRM
			INNER JOIN SII.CGG_RES_ESTADO_TRAMITE ETT ON ETT.CRETT_CODIGO = TRM.CRETT_CODIGO
			INNER JOIN SII.CGG_RES_TIPO_SOLICITUD_TRAMITE ST ON (ST.CRTST_CODIGO=TRM.CRTST_CODIGO)
			INNER JOIN SII.CGG_RES_RESOL_TRAMITE RST ON RST.CRTRA_CODIGO = TRM.CRTRA_CODIGO AND RST.CRRST_ESTADO
			INNER JOIN SII.CGG_RES_RESOLUCION RS ON RS.CRRES_CODIGO = RST.CRRES_CODIGO AND RS.CRRES_ESTADO AND CRRES_ESTADO_RESOLUCION = 0
			INNER JOIN SII.CGG_RES_SESION_COMITE SC ON SC.CRSSC_CODIGO=RS.CRSSC_CODIGO AND SC.CRSSC_ESTADO
			INNER JOIN SII.CGG_ISLA SL ON SL.CISLA_CODIGO = TRM.CISLA_CODIGO AND CISLA_ESTADO
			INNER JOIN SII.CGG_CANTON CNT ON CNT.CCTN_CODIGO = SL.CCTN_CODIGO
			WHERE TRM.CRTRA_ESTADO AND 
			TRM.CRETT_CODIGO = (SELECT CF.CGCNF_VALOR_CADENA FROM SII.CGG_CONFIGURACION CF WHERE CF.CGCNF_CODIGO = '01') AND
			SC.CRSSC_CODIGO = IN_CRSSC_CODIGO;
		RETURN NEXT TMP_REF;
	END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;