/**
* FUNCION SII.F_CGG_RES_EXPULSION_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_EXPULSION.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC 
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param IN_SW CONDICION
* @returns REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_VOTAR_RESOLUCION(
IN IN_USER_NAME CHARACTER VARYING,
IN IN_START_INDEX INTEGER,
IN IN_LIMIT INTEGER,
IN IN_SORT_FIELD_NAME CHARACTER VARYING, 
IN IN_DIRECTION CHARACTER VARYING,
IN IN_FIND_TEXT TEXT,
IN IN_SW BOOLEAN
)RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN	
	OPEN TMP_REF FOR EXECUTE
	'SELECT
		RS.CRRES_CODIGO, 		
		'||CASE WHEN IN_SW THEN 'TRM.CRTRA_NUMERO NUMERO,
		RST.CRTRA_CODIGO, 
		TST.CRTST_DESCRIPCION,
		SII.F_TRAMITE_TIPO(TST.CRTST_CODIGO) TIPO_TRAMITE,
		(PRS.CRPER_NOMBRES||'' ''||COALESCE(PRS.CRPER_APELLIDO_PATERNO,'''')||'' ''||COALESCE(PRS.CRPER_APELLIDO_MATERNO,'''')) BENEFICIARIO,
		CASE WHEN TRM.CVVEH_CODIGO IS NULL THEN CRG.CGCRG_NOMBRE ELSE SCP.CSCTP_NOMBRE END ACTIVIDAD,
		CTG.CVCTG_NOMBRE,'
		ELSE '' END||'
		SC.CRSSC_CODIGO,
		SM.CRSMB_CODIGO,
		RS.CRRES_NUMERO_RESOLUCION, 
		RS.CRRES_TIPO, 		
		RS.CRRES_EXTRACTO_RESOLUCION, 
		RS.CRRES_VOTOS_APROBACION, 
		RS.CRRES_VOTOS_NEGACION, 
		RS.CRRES_VOTOS_ABSTENCION, 
		RS.CRRES_FECHA_EMISION, 		
		RS.CRRES_NOMBRE_ADJUNTO_RESOL, 		
		RS.CRRES_ESTADO_RESOLUCION,
		(SELECT COUNT(SMB.CRSMB_CODIGO) FROM SII.CGG_RES_SESION_MIEMBRO SMB 
		WHERE SMB.CRSSC_CODIGO = RS.CRSSC_CODIGO) TOTAL, 
		(SELECT COUNT(VOT.CRVTO_CODIGO) FROM SII.CGG_RES_VOTO VOT 
		WHERE VOT.CRRES_CODIGO = RS.CRRES_CODIGO) NUMERO_VOTO,
		RS.CRRES_OBSERVACIONES
	FROM SII.CGG_RES_RESOLUCION RS
	INNER JOIN SII.CGG_RES_SESION_COMITE SC ON SC.CRSSC_CODIGO = RS.CRSSC_CODIGO AND SC.CRSSC_ESTADO
	INNER JOIN SII.CGG_RES_SESION_MIEMBRO SM ON SM.CRSSC_CODIGO = SC.CRSSC_CODIGO AND SM.CRSMB_ESTADO
	INNER JOIN SII.CGG_RES_MIEMBRO_COMITE MC ON (MC.CRMBC_CODIGO=SM.CRMBC_CODIGO AND SM.CGG_CRMBC_CODIGO IS NULL OR MC.CRMBC_CODIGO = SM.CGG_CRMBC_CODIGO) AND MC.CRMBC_ESTADO AND MC.CRMBC_AUTORIZADO
	INNER JOIN SII.CGG_USUARIO US ON US.CUSU_CODIGO = MC.CUSU_CODIGO AND US.CUSU_ESTADO
	'||CASE WHEN IN_SW THEN 'INNER JOIN SII.CGG_RES_RESOL_TRAMITE RST ON RST.CRRES_CODIGO = RS.CRRES_CODIGO
	LEFT JOIN SII.CGG_RES_TRAMITE TRM ON TRM.CRTRA_CODIGO = RST.CRTRA_CODIGO 
	LEFT JOIN SII.CGG_RES_TIPO_SOLICITUD_TRAMITE TST ON TST.CRTST_CODIGO = TRM.CRTST_CODIGO
	LEFT JOIN SII.CGG_RES_TIPO_TRAMITE TPT ON TPT.CRTPT_CODIGO = TST.CRTPT_CODIGO
	LEFT JOIN SII.CGG_RES_PERSONA PRS ON PRS.CRPER_CODIGO = TRM.CGG_CRPER_CODIGO
	LEFT JOIN SII.CGG_VEH_VEHICULO VHC ON VHC.CVVEH_CODIGO = TRM.CVVEH_CODIGO
	LEFT JOIN SII.CGG_SECTOR_PRODUCTIVO SCP ON SCP.CSCTP_CODIGO = VHC.CSCTP_CODIGO
	LEFT JOIN SII.CGG_VEH_CATEGORIA CTG ON CTG.CVCTG_CODIGO = VHC.CVCTG_CODIGO
	LEFT JOIN SII.CGG_GEM_CARGO CRG ON CRG.CGCRG_CODIGO = TRM.CRTRA_ACTIVIDAD_RESIDENCIA' 
	ELSE '' END||'
	WHERE RS.CRRES_ESTADO AND SII.F_STRING_IN('||QUOTE_LITERAL(IN_FIND_TEXT)||',
		COALESCE(CRRES_NUMERO_RESOLUCION,'''')||'' ''||
		COALESCE(CRRES_TIPO,0)||'' ''||	
		COALESCE(CRRES_EXTRACTO_RESOLUCION,'''')||'' ''||
		COALESCE(CRRES_VOTOS_APROBACION,0)||'' ''||
		COALESCE(CRRES_VOTOS_NEGACION,0)||'' ''||
		COALESCE(CRRES_VOTOS_ABSTENCION,0)||'' ''||
		COALESCE(CRRES_FECHA_EMISION,CURRENT_TIMESTAMP)||'' ''||
		COALESCE(CRRES_NOMBRE_ADJUNTO_RESOL,'''')||'' ''||
		COALESCE(CRRES_ESTADO_RESOLUCION,0)) = 1 AND 
		('||IN_SW||' OR RS.CRRES_CODIGO NOT IN (SELECT RRT.CRRES_CODIGO FROM SII.CGG_RES_RESOL_TRAMITE RRT 
			INNER JOIN SII.CGG_RES_RESOLUCION RES ON RES.CRRES_CODIGO = RRT.CRRES_CODIGO AND RES.CRSSC_CODIGO = RS.CRSSC_CODIGO)) AND 
		CRSSC_ESTADO_CONVOCATORIA = 3 AND 
		RS.CRRES_ESTADO_RESOLUCION = 0 AND 
		SII.F_CGG_RES_VOTO_USER_COUNT ('||QUOTE_LITERAL(IN_USER_NAME)||', RS.CRRES_CODIGO) = 0 AND 
		US.CUSU_NOMBRE_USUARIO='''||IN_USER_NAME||'''
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100
  ROWS 1000;
  
/**
* FUNCION II.F_CGG_RES_VOTAR_RESOLUCION_COUNT
* CONTABILIZA TODOS LOS REGISTROS DE LA TABLA CGG_RES_VOTAR_RESOLUCION.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param IN_SW CONDICION
* @returns INTEGER
*/ 
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_VOTAR_RESOLUCION_COUNT(
IN IN_USER_NAME VARCHAR,
IN IN_FIND_TEXT TEXT,
IN IN_SW BOOLEAN
)RETURNS INTEGER AS
$BODY$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(
	    RS.CRRES_CODIGO
	)INTO TMP_ROWS
	FROM SII.CGG_RES_RESOLUCION RS	
	INNER JOIN SII.CGG_RES_SESION_COMITE  SC ON (SC.CRSSC_CODIGO=RS.CRSSC_CODIGO)
	INNER JOIN SII.CGG_RES_SESION_MIEMBRO  SM ON (SM.CRSSC_CODIGO=SC.CRSSC_CODIGO)
	INNER JOIN SII.CGG_RES_MIEMBRO_COMITE  MC ON MC.CRMBC_CODIGO=SM.CRMBC_CODIGO AND MC.CRMBC_AUTORIZADO AND MC.CRMBC_ESTADO
	INNER JOIN SII.CGG_USUARIO US ON (US.CUSU_CODIGO=MC.CUSU_CODIGO)
	WHERE CRRES_ESTADO AND 
		(NOT IN_SW OR RS.CRRES_CODIGO = (SELECT CRRES_CODIGO FROM SII.CGG_RES_RESOL_TRAMITE WHERE CRRES_CODIGO = RS.CRRES_CODIGO)) AND
		(LENGTH(IN_FIND_TEXT) = 0 OR SII.F_STRING_IN(IN_FIND_TEXT,
		CASE WHEN CRRES_CODIGO IS NULL THEN '' ELSE CRRES_CODIGO END ||' '||
		CASE WHEN CRRES_NUMERO_RESOLUCION IS NULL THEN '' ELSE CRRES_NUMERO_RESOLUCION END ||' '||
		CASE WHEN CRRES_TIPO IS NULL THEN 0 ELSE CRRES_TIPO END ||' '||
		CASE WHEN CRRES_EXTRACTO_RESOLUCION IS NULL THEN '' ELSE CRRES_EXTRACTO_RESOLUCION END ||' '||
		CASE WHEN CRRES_VOTOS_APROBACION IS NULL THEN 0 ELSE CRRES_VOTOS_APROBACION END ||' '||
		CASE WHEN CRRES_VOTOS_NEGACION IS NULL THEN 0 ELSE CRRES_VOTOS_NEGACION END ||' '||
		CASE WHEN CRRES_VOTOS_ABSTENCION IS NULL THEN 0 ELSE CRRES_VOTOS_ABSTENCION END ||''||
		CASE WHEN CRRES_FECHA_EMISION IS NULL THEN CURRENT_TIMESTAMP ELSE CRRES_FECHA_EMISION END ||' '||
		CASE WHEN CRRES_NOMBRE_ADJUNTO_RESOL IS NULL THEN '' ELSE CRRES_NOMBRE_ADJUNTO_RESOL END ||' '||
		CASE WHEN CRRES_ESTADO_RESOLUCION IS NULL THEN 0 ELSE CRRES_ESTADO_RESOLUCION END ) = 1) AND 
		CRSSC_ESTADO_CONVOCATORIA = 3 AND
		RS.CRRES_ESTADO_RESOLUCION = 0 AND 
		US.CUSU_NOMBRE_USUARIO=IN_USER_NAME;	
	RETURN TMP_ROWS;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;

/**
* FUNCION SII.F_CGG_RES_VOTO_USER_COUNT
* CONTABILIZA EL NUMERO DE VOTO DE UN MIEMBRO DE COMITE.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APLICACIONES
* @param IN_CRRES_CODIGO CODIGO DE LA RESOLUCION QUE SE SOMETE A VOTACION
* @return NUMERO DE VOTOS
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_VOTO_USER_COUNT(
IN IN_USER_NAME VARCHAR,
IN IN_CRRES_CODIGO VARCHAR
) RETURNS INTEGER AS
$$
DECLARE
	OUT_COUNT INT;
BEGIN
	SELECT COUNT(VOT.CRVTO_CODIGO) INTO OUT_COUNT
	FROM SII.CGG_RES_VOTO VOT
	INNER JOIN SII.CGG_RES_SESION_MIEMBRO SMB ON SMB.CRSMB_CODIGO = VOT.CRSMB_CODIGO
	INNER JOIN SII.CGG_RES_SESION_COMITE SCM ON SCM.CRSSC_CODIGO = SMB.CRSSC_CODIGO	
	INNER JOIN SII.CGG_RES_MIEMBRO_COMITE MC ON MC.CRMBC_CODIGO = SMB.CRMBC_CODIGO 
	INNER JOIN SII.CGG_USUARIO USR ON USR.CUSU_CODIGO = MC.CUSU_CODIGO
	WHERE VOT.CRVTO_ESTADO AND VOT.CRRES_CODIGO = IN_CRRES_CODIGO AND 
		USR.CUSU_NOMBRE_USUARIO = IN_USER_NAME;
	RETURN OUT_COUNT;
END;
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;