
/**
* FUNCION F_CGG_DHU_SEGUIMIENTO_ACADEMICO_BECA
* SELECCIONA LOS REGISTROS DE LA TABLA SII.CGG_DHU_SEGUIMIENTO_ACADEMICO.
* @param IN_CRPER_NUM_DOC_IDENTIFIC CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/

CREATE OR REPLACE FUNCTION F_CGG_DHU_SEGUIMIENTO_ACADEMICO_BECA(IN_CRPER_NUM_DOC_IDENTIFIC CHARACTER VARYING)
  RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT 
	 
		SAC.CDBEC_CODIGO, 
		SAC.CDACD_CODIGO,
		PER.CRPER_NOMBRES, 
		TB.CDTBC_CODIGO, 
		TB.CDTBC_NOMBRE,
		(SELECT PR.CRPER_APELLIDO_PATERNO||' '||PR.CRPER_APELLIDO_MATERNO FROM SII.CGG_RES_PERSONA PR WHERE PR.CRPER_CODIGO = BEC.CRPER_CODIGO) AS CRPER_APELLIDOS_PERSONA,
		PER.CRPER_NUM_DOC_IDENTIFIC, 
		PER.CRPER_NUMERO_RESIDENCIA, 
		BEC.CDBEC_NUMERO_CONVENIO, 
		BEC.CDBEC_FUNCIONARIO,
		(SELECT ESP.CGESP_NOMBRE FROM SII.CGG_ESPECIALIDAD ESP WHERE ESP.CGESP_CODIGO =BEC.CGESP_CODIGO) AS CGESP_NOMBRE,
		BEC.CDBEC_TIPO_CICLO,
		SAC.CDACD_NUMERO_CICLO, 
		SAC.CDACD_FECHA_INICIO, 
		SAC.CDACD_FECHA_FIN, 
		SAC.CDACD_OBSERVACION, 
		SAC.CDACD_ESTADO_APROBACION, 
		SAC.CDACD_ESTADO, 
		SAC.CDACD_FECHA_INSERT, 
		SAC.CDACD_USUARIO_INSERT, 
		SAC.CDACD_FECHA_UPDATE, 
		SAC.CDACD_USUARIO_UPDATE
	FROM SII.CGG_DHU_SEGUIMIENTO_ACADEMICO SAC
	INNER JOIN SII.CGG_DHU_BECA BEC ON(BEC.CDBEC_CODIGO=SAC.CDBEC_CODIGO)
	INNER JOIN SII.CGG_RES_PERSONA PER ON(PER.CRPER_CODIGO=BEC.CRPER_CODIGO)
	INNER JOIN SII.CGG_DHU_TIPO_BECA TB ON (BEC.CDTBC_CODIGO=TB.CDTBC_CODIGO)
	WHERE CDACD_ESTADO = TRUE and PER.CRPER_NUM_DOC_IDENTIFIC=IN_CRPER_NUM_DOC_IDENTIFIC AND SAC.CDACD_ESTADO_APROBACION=3 AND BEC.CDBEC_ESTADO_APROBACION=1;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100
  ROWS 1000;