
/**
* FUNCION F_CGG_RES_PERSONA_PRESTAMO
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_PRESTAMO_EXPEDIENTE Y VIZUALIZAR EL ULTIMO MOVIMIENTO.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/

CREATE OR REPLACE FUNCTION F_CGG_RES_PERSONA_PRESTAMO(IN_USER_NAME CHARACTER VARYING, IN_START_INDEX INTEGER, IN_LIMIT INTEGER, IN_SORT_FIELD_NAME CHARACTER VARYING, IN_DIRECTION CHARACTER VARYING, IN_FIND_TEXT TEXT)
  RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT  PER.CRPER_CODIGO,(PER.CRPER_NOMBRES||'' ''||PER.CRPER_APELLIDO_PATERNO||'' ''||PER.CRPER_APELLIDO_MATERNO)AS CRPEX_NOMBRE,
		PER.CRPER_NUM_DOC_IDENTIFIC,
		PER.CRPER_NUMERO_EXPEDIENTE,
		PER.CRPER_FECHA_ARCHIVO,
		PEX.CGG_CRPER_CODIGO,
		(SELECT PEN.CRPER_NOMBRES||'' ''||COALESCE(PEN.CRPER_APELLIDO_PATERNO,'''')||'' ''||COALESCE(PEN.CRPER_APELLIDO_MATERNO,'''') FROM SII.CGG_RES_PERSONA PEN WHERE PEN.CRPER_CODIGO=PEX.CGG_CRPER_CODIGO)AS CRPER_NOMBRE_REALIZA,
		(SELECT DISTINCT PRES.CRPEX_MOVIMIENTO FROM CGG_RES_PRESTAMO_EXPEDIENTE PRES
		WHERE PRES.CRPER_CODIGO = PER.CRPER_CODIGO
		AND PRES.CRPEX_FECHA_OPERACION = (SELECT  MAX(PRES.CRPEX_FECHA_OPERACION) FROM CGG_RES_PRESTAMO_EXPEDIENTE PRES
		WHERE PRES.CRPER_CODIGO = PER.CRPER_CODIGO) ) AS CRPEX_MOVIMIENTO,
		(SELECT  MAX(PRES.CRPEX_FECHA_OPERACION) FROM CGG_RES_PRESTAMO_EXPEDIENTE PRES
		WHERE PRES.CRPER_CODIGO = PER.CRPER_CODIGO) AS CRPEX_FECHA_OPERACION
		FROM SII.CGG_RES_PERSONA PER
		LEFT JOIN SII.CGG_RES_PRESTAMO_EXPEDIENTE PEX
		ON (PER.CRPER_CODIGO = PEX.CRPER_CODIGO)
		WHERE PER.CRPER_NUMERO_EXPEDIENTE IS NOT NULL AND PER.CRPER_ESTADO=TRUE  AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
        COALESCE(PER.CRPER_NOMBRES,'''')||'' ''||
        COALESCE(PER.CRPER_APELLIDO_PATERNO,'''')||'' ''||
        COALESCE(PER.CRPER_APELLIDO_MATERNO,'''')||'' ''||
        COALESCE(PER.CRPER_NUM_DOC_IDENTIFIC,'''')||'' ''||
        COALESCE(PER.CRPER_NUMERO_EXPEDIENTE,'''')||'' ''||
	COALESCE(PER.CRPER_ESTADO, FALSE)||'' ''||
	COALESCE(PER.CRPER_FECHA_INSERT, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(PER.CRPER_USUARIO_INSERT, '''')||'' ''||
	COALESCE(PER.CRPER_FECHA_UPDATE, CURRENT_TIMESTAMP)||'' ''||
	COALESCE(PER.CRPER_USUARIO_UPDATE, '''')) = 1
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100
  ROWS 1000;
