/**
* FUNCION SII.F_CGG_RES_EXPULSION_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_EXPULSION.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_EXPULSION_PERSONA_SELECT(
IN IN_USER_NAME VARCHAR,
IN IN_START_INDEX INT,
IN IN_LIMIT INT,
IN IN_SORT_FIELD_NAME VARCHAR,
IN IN_DIRECTION VARCHAR,
IN IN_FIND_TEXT TEXT
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
	TMP_SQL TEXT;
BEGIN
	TMP_SQL = '';	

		TMP_SQL ='SELECT
			C1.CRPER_CODIGO, 
				C1.CRDID_CODIGO, 
				C1.DOCUMENTO,
				C1.CPRR_CODIGO, 
				C1.PARROQUIA,		
				C1.CCTN_CODIGO, 
				C1.CANTON,		
				C1.CRPER_NOMBRES,		
				C1.CRPER_NUM_DOC_IDENTIFIC, 
				C1.CRPER_FECHA_NACIMIENTO, 		
				C1.CRPER_GENERO,	
				C1.CRMOV_CODIGO,	
				C1.CGG_CARPT_CODIGO,	
				C1.AEROPUERTO,		
				C1.CRMOV_NUMERO_VUELO,
				C1.CRNOT_CODIGO,
				C1.CRNOT_NUMERO_NOTIFICACION,
				C1.FECHA,
				C1.CRMOV_FECHA_VIAJE				
		FROM (
		WITH PQ AS(
			SELECT CPRR_CODIGO,CPRR_NOMBRE FROM CGG_PARROQUIA
		),
		DI AS (
			SELECT CRDID_CODIGO,CRDID_DESCRIPCION FROM CGG_RES_DOCUMENTO_IDENTIFICACIO
		),
		CN AS(
			SELECT CCTN_CODIGO,CCTN_NOMBRE FROM CGG_CANTON 
		),
		AR AS (
			SELECT CARPT_CODIGO,CARPT_NOMBRE FROM CGG_RES_AEROPUERTO
		)
		SELECT	
				PR.CRPER_CODIGO, 
				PR.CRDID_CODIGO, 
				(SELECT CRDID_DESCRIPCION FROM DI WHERE DI.CRDID_CODIGO= PR.CRDID_CODIGO) DOCUMENTO,
				PR.CPRR_CODIGO, 
				(SELECT CPRR_NOMBRE FROM PQ WHERE PQ.CPRR_CODIGO= PR.CPRR_CODIGO) PARROQUIA,		
				PR.CCTN_CODIGO, 
				(SELECT CCTN_NOMBRE FROM CN WHERE CN.CCTN_CODIGO= PR.CCTN_CODIGO) CANTON,		
				PR.CRPER_NOMBRES||'' ''||COALESCE(PR.CRPER_APELLIDO_PATERNO,'''')||'' ''||COALESCE(PR.CRPER_APELLIDO_PATERNO,'''') CRPER_NOMBRES,
				PR.CRPER_NUM_DOC_IDENTIFIC, 
				PR.CRPER_FECHA_NACIMIENTO, 		
				PR.CRPER_GENERO,	
				MV.CRMOV_CODIGO,	
				MV.CGG_CARPT_CODIGO,	
				(SELECT CARPT_NOMBRE FROM AR WHERE AR.CARPT_CODIGO= MV.CGG_CARPT_CODIGO) AEROPUERTO,		
				MV.CRMOV_NUMERO_VUELO,
				NT.CRNOT_CODIGO,
				NT.CRNOT_NUMERO_NOTIFICACION,
				NT.CRNOT_FECHA_NOTIFICACION FECHA,
				TO_CHAR(MV.CRMOV_FECHA_VIAJE,''YYYY-MM-DD HH24:MI'') CRMOV_FECHA_VIAJE
			FROM SII.CGG_RES_PERSONA PR	
			INNER JOIN SII.CGG_RES_MOVILIDAD MV ON MV.CRPER_CODIGO = PR.CRPER_CODIGO AND MV.CRMOV_TIPO_SALIDA = 1 AND MV.CRMOV_TIPO_OPERACION = 1
			LEFT JOIN SII.CGG_RES_NOTIFICACION NT ON NT.CRPER_CODIGO = PR.CRPER_CODIGO AND NT.CRNOT_ESTADO_NOTIFICACION = 3
			LEFT JOIN SII.CGG_RES_EXPULSION EX ON EX.CRMOV_CODIGO = MV.CRMOV_CODIGO
			WHERE CRPER_ESTADO
			AND EX.CREXP_CODIGO IS NULL 
			AND (NT.CRNOT_CODIGO IS NULL OR NT.CRNOT_FECHA_NOTIFICACION = (SELECT MAX(CRNOT_FECHA_NOTIFICACION) FROM SII.CGG_RES_NOTIFICACION WHERE CRPER_CODIGO = PR.CRPER_CODIGO) )
		) AS C1
		WHERE (LENGTH('||QUOTE_LITERAL(IN_FIND_TEXT)||') = 0 OR SII.F_STRING_IN('''||IN_FIND_TEXT||''',
				COALESCE(C1.CRPER_NOMBRES, '''')||'' ''||			
				COALESCE(C1.CRPER_NUM_DOC_IDENTIFIC, '''')) = 1)     
		ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
		' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
		OPEN TMP_REF FOR EXECUTE TMP_SQL;	
	
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_EXPULSION_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_RES_EXPULSION.
* QUE CUMPLEN CON EL CRITERIO DE BUSQUEDA.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TOTAL DE REGISTROS
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_EXPULSION_PERSONA_COUNT(
IN IN_FIND_TEXT TEXT
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	/*SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_RES_PERSONA PR
	INNER JOIN SII.CGG_RES_MOVILIDAD MV ON MV.CRPER_CODIGO = PR.CRPER_CODIGO AND MV.CRMOV_TIPO_SALIDA = 1 AND MV.CRMOV_TIPO_OPERACION = 1
	LEFT JOIN SII.CGG_RES_NOTIFICACION NT ON NT.CRPER_CODIGO = PR.CRPER_CODIGO AND NT.CRNOT_ESTADO_NOTIFICACION = 3
	WHERE CRPER_ESTADO AND (LENGTH(IN_FIND_TEXT) = 0 OR SII.F_STRING_IN(IN_FIND_TEXT,
	COALESCE(CRPER_NOMBRES, '')||' '||	
	COALESCE(CRPER_NUM_DOC_IDENTIFIC, '')||' '||
	COALESCE(CRPER_FECHA_NACIMIENTO, CURRENT_TIMESTAMP)||' '||
	COALESCE(CRPER_GENERO, 0)) = 1);*/
	
	SELECT
		COUNT(C1.CRPER_CODIGO) INTO TMP_ROWS		
	FROM (
		SELECT	
				PR.CRPER_CODIGO,
				PR.CRPER_NOMBRES||' '||COALESCE(PR.CRPER_APELLIDO_PATERNO,'')||' '||COALESCE(PR.CRPER_APELLIDO_PATERNO,'') CRPER_NOMBRES,	
				PR.CRPER_NUM_DOC_IDENTIFIC				
				FROM SII.CGG_RES_PERSONA PR	
				INNER JOIN SII.CGG_RES_MOVILIDAD MV ON MV.CRPER_CODIGO = PR.CRPER_CODIGO AND MV.CRMOV_TIPO_SALIDA = 1 AND MV.CRMOV_TIPO_OPERACION = 1
				LEFT JOIN SII.CGG_RES_NOTIFICACION NT ON NT.CRPER_CODIGO = PR.CRPER_CODIGO AND NT.CRNOT_ESTADO_NOTIFICACION = 3
				LEFT JOIN SII.CGG_RES_EXPULSION EX ON EX.CRMOV_CODIGO = MV.CRMOV_CODIGO
				WHERE CRPER_ESTADO
				AND EX.CREXP_CODIGO IS NULL 
				AND (NT.CRNOT_CODIGO IS NULL OR NT.CRNOT_FECHA_NOTIFICACION = (SELECT MAX(CRNOT_FECHA_NOTIFICACION) FROM SII.CGG_RES_NOTIFICACION WHERE CRPER_CODIGO = PR.CRPER_CODIGO) )
	) AS C1
	WHERE (LENGTH(IN_FIND_TEXT) = 0 OR SII.F_STRING_IN(IN_FIND_TEXT,
				COALESCE(C1.CRPER_NOMBRES, '')||' '||			
				COALESCE(C1.CRPER_NUM_DOC_IDENTIFIC, '')) = 1) ;   		
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;