/**-- Funcion: f_cgg_res_muelle_select
* SELECCIONA TODA LA INFORMACION DE LA TABLA  CGG_RE_MUELLE.
*@param in_user_name NOMBRE DEL USUARIO DEL SERVIDOR DE APLICACIONES
*@param in_start_index INDICE DE INICIO
*@param in_limit TOTAL DE REGISTROS QUE SON CONSIDERADOS
*@param in_sort_field_name NOMBRE DE LA COLUMNA DEL ORDENAMIENTO
*@param	in_direction DIRECCION DEL ORDENAMIENTO
*@param	in_find_text CRITERIO DE BUSQUEDA
*@return REFCURSOR
*/

-- DROP FUNCTION f_cgg_res_muelle_select(character varying, integer, integer, character varying, character varying, text);

CREATE OR REPLACE FUNCTION f_cgg_res_muelle_select(in_user_name character varying, in_start_index integer, in_limit integer, in_sort_field_name character varying, in_direction character varying, in_find_text text)
  RETURNS SETOF refcursor AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT
		ML.CRMLE_CODIGO, 
		ML.CCTN_CODIGO, 
		CN.CCTN_NOMBRE,
		ML.CRMLE_NOMBRE, 
		ML.CRMLE_ESTADO, 
		ML.CRMLE_FECHA_INSERT, 
		ML.CRMLE_USUARIO_INSERT, 
		ML.CRMLE_FECHA_UPDATE, 
		ML.CRMLE_USUARIO_UPDATE
	FROM SII.CGG_RES_MUELLE ML
	INNER JOIN SII.CGG_CANTON CN ON (CN.CCTN_CODIGO=ML.CCTN_CODIGO)
	WHERE CRMLE_ESTADO = TRUE AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',CASE WHEN ML.CRMLE_CODIGO IS NULL THEN '''' ELSE ML.CRMLE_CODIGO END ||'' ''||
	CASE WHEN ML.CCTN_CODIGO IS NULL THEN '''' ELSE ML.CCTN_CODIGO END ||'' ''||
	CASE WHEN ML.CRMLE_NOMBRE IS NULL THEN '''' ELSE ML.CRMLE_NOMBRE END ||'' ''||
	CASE WHEN ML.CRMLE_ESTADO IS NULL THEN FALSE ELSE ML.CRMLE_ESTADO END ||'' ''||
	CASE WHEN ML.CRMLE_FECHA_INSERT IS NULL THEN CURRENT_TIMESTAMP ELSE ML.CRMLE_FECHA_INSERT END ||'' ''||
	CASE WHEN ML.CRMLE_USUARIO_INSERT IS NULL THEN '''' ELSE ML.CRMLE_USUARIO_INSERT END ||'' ''||
	CASE WHEN ML.CRMLE_FECHA_UPDATE IS NULL THEN CURRENT_TIMESTAMP ELSE ML.CRMLE_FECHA_UPDATE END ||'' ''||
	CASE WHEN ML.CRMLE_USUARIO_UPDATE IS NULL THEN '''' ELSE ML.CRMLE_USUARIO_UPDATE END ) = 1
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100
  ROWS 1000;
ALTER FUNCTION f_cgg_res_muelle_select(character varying, integer, integer, character varying, character varying, text) OWNER TO sii;
