/**
* FUNCION SII.F_CGG_TCT_REGISTRO_GRUPO_ACTIVIDAD
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_TCT_ACTIVIDAD.
* @param IN_CTGTR_CODIGO IDENTIFICACION DEL GRUPO DE TURISTA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_TCT_REGISTRO_GRUPO_ACTIVIDAD(
IN IN_CTGTR_CODIGO  SII.CGG_TCT_GRUPO_TURISTA.CTGTR_CODIGO%TYPE
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT
		AC.CTACT_CODIGO, 
		AC.CTACT_NOMBRE		
	FROM SII.CGG_TCT_ACTIVIDAD AC
	INNER JOIN SII.CGG_TCT_GRUPO_ACTIVIDAD GA ON (GA.CTACT_CODIGO = AC.CTACT_CODIGO)
	INNER JOIN SII.CGG_TCT_GRUPO_TURISTA GT ON (GT.CTGTR_CODIGO = GA.CTGTR_CODIGO)	
	WHERE CTACT_ESTADO = TRUE 	
	AND GT.CTGTR_CODIGO = IN_CTGTR_CODIGO;
	
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_TCT_REGISTRO_GRUPO_HOSPEDAJE
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_TCT_TIPO_HOSPEDAJE.
* @param IN_CTGTR_CODIGO IDENTIFICATIVO UNICO DE GRUPO DE TURISTA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_TCT_REGISTRO_GRUPO_HOSPEDAJE(
IN IN_CTGTR_CODIGO  SII.CGG_TCT_GRUPO_TURISTA.CTGTR_CODIGO%TYPE
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT
		TH.CTTHJ_CODIGO, 
		TH.CTTHJ_NOMBRE		
	FROM SII.CGG_TCT_TIPO_HOSPEDAJE TH
	INNER JOIN SII.CGG_TCT_GRUPO_HOSPEDAJE GH ON (GH.CTTHJ_CODIGO = TH.CTTHJ_CODIGO)
	INNER JOIN SII.CGG_TCT_GRUPO_TURISTA GT ON (GT.CTGTR_CODIGO = GH.CTGTR_CODIGO)	
	WHERE CTTHJ_ESTADO = TRUE 	
	AND GT.CTGTR_CODIGO = IN_CTGTR_CODIGO;
	
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

