/**
* FUNCION SII.F_CGG_DHU_APLICAR_PREGUNTAS_RESPUESTAS_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_DHU_PREGUNTA,SII.CGG_DHU_PREGUNTA_RESPUESTA Y SII.CGG_DHU_RESPUESTA.
* @param IN IN_CDENC_CODIGO IDENTIFICATIVO UNICO DE ENCUESTA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_DHU_APLICAR_PREGUNTAS_RESPUESTAS_CATEGORIA_SELECT(
IN IN_CDENC_CODIGO SII.CGG_DHU_CUESTIONARIO.CDENC_CODIGO%TYPE
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR 
	SELECT DISTINCT
			CG.CDCAT_CODIGO,
			CG.CDCAT_NOMBRE	
			FROM SII.CGG_DHU_CATEGORIA CG
			INNER JOIN SII.CGG_DHU_PREGUNTA PR ON (CG.CDCAT_CODIGO = PR.CDCAT_CODIGO)
			INNER JOIN SII.CGG_DHU_CUESTIONARIO CT ON  (CT.CDPRG_CODIGO = PR.CDPRG_CODIGO)
			INNER JOIN SII.CGG_DHU_ENCUESTA EN ON (EN.CDENC_CODIGO = CT.CDENC_CODIGO)	
			WHERE CG.CDCAT_ESTADO = TRUE 
			AND  EN.CDENC_CODIGO  = IN_CDENC_CODIGO;
		RETURN NEXT TMP_REF;
	
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_DHU_APLICAR_PREGUNTAS_RESPUESTAS_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_DHU_PREGUNTA,SII.CGG_DHU_PREGUNTA_RESPUESTA Y SII.CGG_DHU_RESPUESTA.
* @param IN IN_CDCAT_CODIGO IDENTIFICATIVO UNICO DE CATEGORIA
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_DHU_APLICAR_PREGUNTAS_RESPUESTAS_SELECT(
IN IN_CDCAT_CODIGO SII.CGG_DHU_CATEGORIA.CDCAT_CODIGO%TYPE,
IN IN_CDENC_CODIGO VARCHAR
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR 
	/*SELECT DISTINCT
		PR.CDPRG_CODIGO, 		
		PR.CDPRG_DESCRIPCION, 
		PR.CDPRG_CUANTIFICABLE,
		PR.CDPRG_MULTIPLE
	
	FROM SII.CGG_DHU_PREGUNTA  PR
	INNER JOIN SII.CGG_DHU_CATEGORIA CG ON (CG.CDCAT_CODIGO = PR.CDCAT_CODIGO)
	INNER JOIN SII.CGG_DHU_PREGUNTA_RESPUESTA PRS ON (PRS.CDPRG_CODIGO = PR.CDPRG_CODIGO)	
	
	WHERE CDPRG_ESTADO = TRUE 
	AND  CG.CDCAT_CODIGO = IN_CDCAT_CODIGO;*/
	SELECT DISTINCT
		PR.CDPRG_CODIGO, 		
		PR.CDPRG_DESCRIPCION, 
		PR.CDPRG_CUANTIFICABLE,
		PR.CDPRG_MULTIPLE
	
	FROM SII.CGG_DHU_PREGUNTA  PR
	INNER JOIN SII.CGG_DHU_CATEGORIA CG ON (CG.CDCAT_CODIGO = PR.CDCAT_CODIGO)
	INNER JOIN SII.CGG_DHU_PREGUNTA_RESPUESTA PRS ON (PRS.CDPRG_CODIGO = PR.CDPRG_CODIGO)
	INNER JOIN SII.CGG_DHU_CUESTIONARIO CUE ON(PR.CDPRG_CODIGO = CUE.CDPRG_CODIGO)	
	WHERE CDPRG_ESTADO = TRUE AND CUE.CDENC_CODIGO = IN_CDENC_CODIGO
	AND  CG.CDCAT_CODIGO = IN_CDCAT_CODIGO;
	
	RETURN NEXT TMP_REF;
	
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;


/**
* FUNCION SII.F_CGG_DHU_RESPUESTAS_PREGUNTAS_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_DHU_PREGUNTA,SII.CGG_DHU_PREGUNTA_RESPUESTA. 
* @param IN IN_CDCAT_CODIGO SII.CGG_DHU_CUESTIONARIO.CDENC_CODIGO%TYPE
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_DHU_RESPUESTAS_PREGUNTAS_SELECT(
IN IN_CDCAT_CODIGO SII.CGG_DHU_CATEGORIA.CDCAT_CODIGO%TYPE
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR 
	SELECT DISTINCT
		RS.CDRES_CODIGO, 
		RS.CDRES_DESCRIPCION, 
		PRS.CDPRS_VALORACION,
		PG.CDPRG_CUANTIFICABLE,
		PG.CDPRG_MULTIPLE		
	FROM SII.CGG_DHU_RESPUESTA  RS	
	INNER JOIN SII.CGG_DHU_PREGUNTA_RESPUESTA PRS ON (PRS.CDRES_CODIGO = RS.CDRES_CODIGO)	
	INNER JOIN SII.CGG_DHU_PREGUNTA PG ON (PG.CDPRG_CODIGO = PRS.CDPRG_CODIGO)	
	INNER JOIN SII.CGG_DHU_CATEGORIA CG ON (CG.CDCAT_CODIGO = PG.CDCAT_CODIGO)
	WHERE CDPRG_ESTADO = TRUE 
	AND  CG.CDCAT_CODIGO = IN_CDCAT_CODIGO;
	
	RETURN NEXT TMP_REF;
	
END
$$
LANGUAGE 'PLPGSQL' VOLATILE CALLED ON NULL INPUT;