---FUNCION F_CGG_RES_OFICIAL_SEGUIMIENTO_USURIO_OFFLINE
---SELECCIONA DATOS DE LA TABLA CGG_RES_OFICIAL_SEGUIMIENTO
---@PARAM IN USER NAME
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_OFICIAL_SEGUIMIENTO_USUARIO_OFFLINE(
	IN_USER_NAME VARCHAR
)  RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT
		OS.CROSG_CODIGO,
		PER.CRPER_NOMBRES,
		COALESCE(PER.CRPER_APELLIDO_PATERNO,'')||' '||COALESCE(PER.CRPER_APELLIDO_MATERNO,'') AS APELLIDOS,
		PER.CRPER_NUM_DOC_IDENTIFIC
	FROM SII.CGG_USUARIO U
	INNER JOIN SII.CGG_RES_PERSONA PER ON PER.CRPER_CODIGO = U.CRPER_CODIGO
	INNER JOIN SII.CGG_RES_OFICIAL_SEGUIMIENTO OS ON (U.CUSU_CODIGO= OS.CUSU_CODIGO)
	WHERE U.CUSU_ESTADO = TRUE;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE;
