/** FUNCION: f_cgg_dhu_seguimiento_academico_consulta_count
* CONTABILIZA N REGISTROS DE LA TABLA SII.CGG_DHU_SEGUIMIENTO_ACADEMICO.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TMP_ROWS
*/
CREATE OR REPLACE FUNCTION f_cgg_dhu_seguimiento_academico_consulta_count(in_find_text text)
RETURNS integer AS
$BODY$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_DHU_SEGUIMIENTO_ACADEMICO SAC
	INNER JOIN SII.CGG_DHU_BECA BEC ON(BEC.CDBEC_CODIGO=SAC.CDBEC_CODIGO)
	INNER JOIN SII.CGG_RES_PERSONA PER ON(PER.CRPER_CODIGO=BEC.CRPER_CODIGO)
	INNER JOIN SII.CGG_DHU_TIPO_BECA TB ON (BEC.CDTBC_CODIGO=TB.CDTBC_CODIGO)
	WHERE CDACD_ESTADO = TRUE  AND SII.F_STRING_IN(IN_FIND_TEXT,
	COALESCE (SAC.CDBEC_CODIGO ,'')||' '||
	COALESCE(CDACD_CODIGO,'' ) ||' '||
	COALESCE(CDACD_NUMERO_CICLO ,0) ||' '||
	COALESCE(CDACD_FECHA_INICIO ,CURRENT_TIMESTAMP)||' '||
	COALESCE(CDACD_FECHA_FIN , CURRENT_TIMESTAMP ) ||' '||
	COALESCE(CDACD_OBSERVACION ,'')||' '||
	COALESCE(CDACD_ESTADO_APROBACION ,0 ) ||' '||
	COALESCE(CDACD_ESTADO , FALSE ) ||' '||
	COALESCE(CDACD_FECHA_INSERT , CURRENT_TIMESTAMP) ||' '||
	COALESCE(CDACD_USUARIO_INSERT ,'' ) ||' '||
	COALESCE(CDACD_FECHA_UPDATE , CURRENT_TIMESTAMP )||' '||
	COALESCE(CDACD_USUARIO_UPDATE, '' ))= 1;
	RETURN TMP_ROWS;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100;