/**
* FUNCION SII.F_CGG_RES_MIEMBRO_SESION_VOTO
* SELECCIONA TODOS LOS REGISTRO DE LA TABLA SII.CGG_RES_MIEMBRO_COMITE.
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_MIEMBRO_SESION_VOTO(
IN IN_CRSSC_CODIGO CHARACTER VARYING
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT 
		SM.CRSMB_CODIGO,
		PR.CRPER_NOMBRES, 
		PR.CRPER_APELLIDO_PATERNO		
	FROM SII.CGG_RES_PERSONA PR
	INNER JOIN SII.CGG_USUARIO US ON US.CRPER_CODIGO= PR.CRPER_CODIGO AND US.CUSU_ESTADO
	INNER JOIN SII.CGG_RES_MIEMBRO_COMITE MC ON MC.CUSU_CODIGO = US.CUSU_CODIGO AND MC.CRMBC_AUTORIZADO AND MC.CRMBC_ESTADO
	INNER JOIN SII.CGG_RES_SESION_MIEMBRO SM ON ((SM.CGG_CRMBC_CODIGO IS NULL AND SM.CRMBC_CODIGO = MC.CRMBC_CODIGO) OR (SM.CGG_CRMBC_CODIGO = MC.CRMBC_CODIGO))
	INNER JOIN SII.CGG_RES_SESION_COMITE SC ON SC.CRSSC_CODIGO= SM.CRSSC_CODIGO
	WHERE CRPER_ESTADO AND 
		SC.CRSSC_CODIGO = IN_CRSSC_CODIGO;
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_VOTAR_RESOLUCION_ADMIN
* SELECCIONA TODOS LOS TRAMITES QUE NO RECIBIERON VOTACION REGULAR PARA SER VOTADOS POR.
* COORDINACION DE RESIDENCIA.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APLICACIONES
* @param IN IN_START_INDEX INDICE DE INICIO
* @param IN IN_LIMIT TOTAL DE REGISTROS QUE SON CONSIDERADOS
* @param IN IN_SORT_FIELD_NAME NOMBRE DE LA COLUMNA DEL ORDENAMIENTO
* @param IN IN_DIRECTION DIRECCION DEL ORDENAMIENTO
* @param IN IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param IN IN_CRSSC_CODIGO IDENTIFICATIVO DE SESION DE COMITE
* @return REFCURSOR
*/

CREATE OR REPLACE FUNCTION SII.F_CGG_RES_VOTAR_RESOLUCION_ADMIN(
IN IN_USER_NAME CHARACTER VARYING,
IN IN_START_INDEX INTEGER,
IN IN_LIMIT INTEGER,
IN IN_SORT_FIELD_NAME CHARACTER VARYING, 
IN IN_DIRECTION CHARACTER VARYING,
IN IN_FIND_TEXT TEXT,
IN IN_CRSSC_CODIGO CHARACTER VARYING
)RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
	TMP_CISLA_CODIGO VARCHAR;
BEGIN
	SELECT CISLA_CODIGO INTO TMP_CISLA_CODIGO FROM SII.CGG_USUARIO WHERE CUSU_NOMBRE_USUARIO = IN_USER_NAME;
	IF(TMP_CISLA_CODIGO IS NULL)THEN
		TMP_CISLA_CODIGO := '';
	END IF;
	OPEN TMP_REF FOR EXECUTE
	'SELECT
		RS.CRRES_CODIGO, 		
		RST.CRTRA_CODIGO, 
		CASE WHEN TRM.CRTRA_NUMERO IS NULL THEN RS.CRRES_EXTRACTO_RESOLUCION ELSE TRM.CRTRA_NUMERO::VARCHAR END NUMERO,
		RS.CRSSC_CODIGO,		
		RS.CRRES_NUMERO_RESOLUCION, 
		COALESCE(PRS.CRPER_NOMBRES,'''')||'' ''||COALESCE(PRS.CRPER_APELLIDO_PATERNO,'''')||'' ''||COALESCE(PRS.CRPER_APELLIDO_MATERNO,'''') BENEFICIARIO,
		RS.CRRES_TIPO, 				
		(SELECT COUNT(SMB.CRSMB_CODIGO) FROM SII.CGG_RES_SESION_MIEMBRO SMB 
		WHERE SMB.CRSSC_CODIGO = RS.CRSSC_CODIGO) TOTAL, 
		(SELECT COUNT(VOT.CRVTO_CODIGO) FROM SII.CGG_RES_VOTO VOT 
		WHERE CRVTO_ESTADO AND VOT.CRRES_CODIGO = RS.CRRES_CODIGO) NUMERO_VOTO,
		(SELECT COUNT(VOT.CRVTO_CODIGO)
			FROM SII.CGG_RES_VOTO VOT, SII.CGG_RES_SESION_MIEMBRO SMB, SII.CGG_RES_SESION_COMITE SCM
			WHERE   VOT.CRRES_CODIGO = RS.CRRES_CODIGO
				AND VOT.CRSMB_CODIGO = SMB.CRSMB_CODIGO 
				AND		SMB.CRSSC_CODIGO = SCM.CRSSC_CODIGO) RESOL_VOTO
	FROM SII.CGG_RES_RESOLUCION RS
	INNER JOIN SII.CGG_RES_SESION_COMITE SSC ON SSC.CRSSC_CODIGO = RS.CRSSC_CODIGO AND SSC.CRSSC_ESTADO
	LEFT JOIN SII.CGG_RES_RESOL_TRAMITE RST ON RST.CRRES_CODIGO = RS.CRRES_CODIGO AND RST.CRRST_ESTADO
	LEFT JOIN SII.CGG_RES_TRAMITE TRM ON TRM.CRTRA_CODIGO = RST.CRTRA_CODIGO AND TRM.CRTRA_ESTADO AND TRM.CRTRA_ESTADO
	LEFT JOIN SII.CGG_RES_PERSONA PRS ON PRS.CRPER_CODIGO = TRM.CGG_CRPER_CODIGO AND PRS.CRPER_ESTADO
	LEFT JOIN SII.CGG_RES_VOTO VOT ON VOT.CRRES_CODIGO =  RS.CRRES_CODIGO AND VOT.CRVTO_ESTADO
	WHERE CRRES_ESTADO AND 
		VOT.CRVTO_CODIGO IS NULL AND 
		(LENGTH('||QUOTE_LITERAL(IN_FIND_TEXT)||') = 0 OR SII.F_STRING_IN('''||IN_FIND_TEXT||''',
		CASE WHEN CRRES_NUMERO_RESOLUCION IS NULL THEN '''' ELSE CRRES_NUMERO_RESOLUCION END ||'' ''||
		CASE WHEN CRRES_TIPO IS NULL THEN 0 ELSE CRRES_TIPO END) = 1 ) AND 
		RS.CRRES_ESTADO_RESOLUCION = 0	AND 
	(TRM.CRTRA_CODIGO IS NULL OR TRM.CISLA_CODIGO = '||QUOTE_LITERAL(TMP_CISLA_CODIGO)||') AND 
	RS.CRSSC_CODIGO='''||IN_CRSSC_CODIGO||'''	
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100
  ROWS 1000;
  
 /**
* FUNCION SII.F_CGG_RES_VOTAR_RESOLUCION_COUNT_ADMIN
* CONTABILIZA EL NUMERO DE VOTOS DE UNA RESOLUCION.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APLICACIONES
* @param IN IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param IN IN_CRSSC_CODIGO IDENTIFICATIVO DE SESION DE COMITE
* @return INTEGER
*/
 
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_VOTAR_RESOLUCION_COUNT_ADMIN(
IN IN_USER_NAME VARCHAR,
IN IN_CRSSC_CODIGO CHARACTER VARYING,
IN IN_FIND_TEXT TEXT
)RETURNS INTEGER AS
$BODY$
DECLARE
TMP_ROWS INT2;
TMP_CISLA_CODIGO VARCHAR;
BEGIN
	SELECT CISLA_CODIGO INTO TMP_CISLA_CODIGO FROM SII.CGG_USUARIO WHERE CUSU_NOMBRE_USUARIO = IN_USER_NAME;
	IF(TMP_CISLA_CODIGO IS NULL)THEN
		TMP_CISLA_CODIGO := '';
	END IF;
	SELECT COUNT(*)	INTO TMP_ROWS
	FROM SII.CGG_RES_RESOLUCION RS	
	INNER JOIN SII.CGG_RES_SESION_COMITE SSC ON SSC.CRSSC_CODIGO = RS.CRSSC_CODIGO AND CRSSC_ESTADO
	LEFT JOIN SII.CGG_RES_RESOL_TRAMITE RST ON RST.CRRES_CODIGO = RS.CRRES_CODIGO
	LEFT JOIN SII.CGG_RES_TRAMITE TRM ON TRM.CRTRA_CODIGO = RST.CRTRA_CODIGO AND TRM.CRTRA_ESTADO
	LEFT JOIN SII.CGG_RES_VOTO VOT ON VOT.CRRES_CODIGO =  RS.CRRES_CODIGO AND VOT.CRVTO_ESTADO
	WHERE CRRES_ESTADO AND 
		VOT.CRVTO_CODIGO IS NULL AND 
		(LENGTH(IN_FIND_TEXT) = 0 OR SII.F_STRING_IN(IN_FIND_TEXT,
		CASE WHEN CRRES_NUMERO_RESOLUCION IS NULL THEN '''' ELSE CRRES_NUMERO_RESOLUCION END ||' '||
		CASE WHEN CRRES_TIPO IS NULL THEN 0 ELSE CRRES_TIPO END ||' '||
		CASE WHEN CRRES_EXTRACTO_RESOLUCION IS NULL THEN '''' ELSE CRRES_EXTRACTO_RESOLUCION END ||' '||
		CASE WHEN CRRES_VOTOS_APROBACION IS NULL THEN 0 ELSE CRRES_VOTOS_APROBACION END ||' '||
		CASE WHEN CRRES_VOTOS_NEGACION IS NULL THEN 0 ELSE CRRES_VOTOS_NEGACION END ||' '||
		CASE WHEN CRRES_VOTOS_ABSTENCION IS NULL THEN 0 ELSE CRRES_VOTOS_ABSTENCION END ||''||
		CASE WHEN CRRES_FECHA_EMISION IS NULL THEN CURRENT_TIMESTAMP ELSE CRRES_FECHA_EMISION END ||' '||
		CASE WHEN CRRES_NOMBRE_ADJUNTO_RESOL IS NULL THEN '''' ELSE CRRES_NOMBRE_ADJUNTO_RESOL END ||' '||
		CASE WHEN CRRES_ESTADO_RESOLUCION IS NULL THEN 0 ELSE CRRES_ESTADO_RESOLUCION END ) = 1) AND 
		RS.CRRES_ESTADO_RESOLUCION = 0 AND 
		(TRM.CRTRA_CODIGO IS NULL OR TRM.CISLA_CODIGO = TMP_CISLA_CODIGO) AND 
		RS.CRSSC_CODIGO=IN_CRSSC_CODIGO;	
	RETURN TMP_ROWS;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;
  
/**
* FUNCION SII.F_CGG_RES_VOTAR_RESOLUCION_ADMIN1
* SELECCIONA TODOS LOS REGISTRO DE LA TABLA SII.CGG_RES_MIEMBRO_COMITE.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APLICACIONES
* @param IN IN_CRSSC_CODIGO IDENTIFICATIVO DE SESION DE COMITE
* @return REFCURSOR
*/

CREATE OR REPLACE FUNCTION SII.F_CGG_RES_VOTAR_RESOLUCION_ADMIN1(
IN IN_USER_NAME CHARACTER VARYING,
IN IN_CRSSC_CODIGO CHARACTER VARYING
)RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
	TMP_CISLA_CODIGO VARCHAR;
BEGIN
	SELECT CISLA_CODIGO INTO TMP_CISLA_CODIGO FROM SII.CGG_USUARIO WHERE CUSU_NOMBRE_USUARIO = IN_USER_NAME;
	IF(TMP_CISLA_CODIGO IS NULL)THEN
		TMP_CISLA_CODIGO := '';
	END IF;
	OPEN TMP_REF FOR
	SELECT
		RS.CRRES_CODIGO, 		
		RST.CRTRA_CODIGO, 
		CASE WHEN TRM.CRTRA_NUMERO IS NULL THEN RS.CRRES_EXTRACTO_RESOLUCION ELSE TRM.CRTRA_NUMERO::VARCHAR END NUMERO,
		RS.CRSSC_CODIGO,		
		RS.CRRES_NUMERO_RESOLUCION, 
		COALESCE(PRSB.CRPER_NOMBRES,'')||' '||COALESCE(PRSB.CRPER_APELLIDO_PATERNO,'')||' '||COALESCE(PRSB.CRPER_APELLIDO_MATERNO,'') BENEFICIARIO,
		RS.CRRES_TIPO, 				
		(SELECT COUNT(SMB.CRSMB_CODIGO) FROM SII.CGG_RES_SESION_MIEMBRO SMB WHERE SMB.CRSSC_CODIGO = RS.CRSSC_CODIGO) TOTAL, 
		(SELECT COUNT(VOT.CRVTO_CODIGO) FROM SII.CGG_RES_VOTO VOT WHERE VOT.CRRES_CODIGO = RS.CRRES_CODIGO AND VOT.CRVTO_ESTADO) NUMERO_VOTO,
		(SELECT COUNT(VOT.CRVTO_CODIGO) FROM SII.CGG_RES_VOTO VOT, SII.CGG_RES_SESION_MIEMBRO SMB, SII.CGG_RES_SESION_COMITE SCM
			WHERE   VOT.CRRES_CODIGO = RS.CRRES_CODIGO
			AND VOT.CRSMB_CODIGO = SMB.CRSMB_CODIGO 
			AND		SMB.CRSSC_CODIGO = SCM.CRSSC_CODIGO) RESOL_VOTO
	FROM SII.CGG_RES_RESOLUCION RS
	LEFT JOIN SII.CGG_RES_RESOL_TRAMITE RST ON RST.CRRES_CODIGO = RS.CRRES_CODIGO AND RST.CRRST_ESTADO
	LEFT JOIN SII.CGG_RES_TRAMITE TRM ON TRM.CRTRA_CODIGO = RST.CRTRA_CODIGO AND TRM.CRTRA_ESTADO AND TRM.CRTRA_ESTADO
	LEFT JOIN SII.CGG_RES_PERSONA PRSB ON PRSB.CRPER_CODIGO = TRM.CGG_CRPER_CODIGO AND PRSB.CRPER_ESTADO
	WHERE CRRES_ESTADO AND
		RS.CRRES_ESTADO_RESOLUCION = 0 AND
		(TRM.CRTRA_CODIGO IS NULL OR TRM.CISLA_CODIGO = TMP_CISLA_CODIGO) AND 
		RS.CRSSC_CODIGO = IN_CRSSC_CODIGO;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE;
  
/**
* FUNCION SII.F_CGG_RES_MIEMBRO_SESION_VOTO1
* SELECCIONA TODOS LOS VOTOS QUE LOS MIEMBROS HAN VOTADO EN UNA SESION.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APLICACIONES
* @param IN IN_START_INDEX INDICE DE INICIO
* @param IN IN_LIMIT TOTAL DE REGISTROS QUE SON CONSIDERADOS
* @param IN IN_SORT_FIELD_NAME NOMBRE DE LA COLUMNA DEL ORDENAMIENTO
* @param IN IN_DIRECTION DIRECCION DEL ORDENAMIENTO
* @param IN IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param IN IN_CRSSC_CODIGO IDENTIFICATIVO DE SESION DE COMITE
* @param IN_CRRES_CODIGO IDENTIFICATIVO UNICO DE RESOLUCION
* @return REFCURSOR
*/  
  
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_MIEMBRO_SESION_VOTO1(
IN IN_USER_NAME CHARACTER VARYING,
IN IN_START_INDEX INTEGER,
IN IN_LIMIT INTEGER,
IN IN_SORT_FIELD_NAME CHARACTER VARYING, 
IN IN_DIRECTION CHARACTER VARYING,
IN IN_FIND_TEXT TEXT,
IN IN_CRSSC_CODIGO CHARACTER VARYING,
IN IN_CRRES_CODIGO VARCHAR
)RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT RSL.CRRES_CODIGO,
	VOT.CRVTO_CODIGO,
		SM.CRSMB_CODIGO,
		PR.CRPER_NOMBRES, 
		PR.CRPER_APELLIDO_PATERNO
	FROM SII.CGG_RES_SESION_COMITE SC 
	INNER JOIN SII.CGG_RES_SESION_MIEMBRO SM ON SM.CRSSC_CODIGO = SC.CRSSC_CODIGO AND SM.CRSMB_ESTADO	
	INNER JOIN SII.CGG_RES_MIEMBRO_COMITE MC ON ((SM.CGG_CRMBC_CODIGO IS NULL AND MC.CRMBC_CODIGO = SM.CRMBC_CODIGO) OR (MC.CRMBC_CODIGO = SM.CGG_CRMBC_CODIGO)) AND MC.CRMBC_ESTADO AND MC.CRMBC_AUTORIZADO
	INNER JOIN SII.CGG_USUARIO US ON US.CUSU_CODIGO = MC.CUSU_CODIGO AND US.CUSU_ESTADO
	INNER JOIN SII.CGG_RES_PERSONA PR ON PR.CRPER_CODIGO = US.CRPER_CODIGO AND PR.CRPER_ESTADO
	INNER JOIN SII.CGG_RES_RESOLUCION RSL ON RSL.CRSSC_CODIGO = SC.CRSSC_CODIGO AND RSL.CRRES_ESTADO
	LEFT JOIN SII.CGG_RES_VOTO VOT ON VOT.CRSMB_CODIGO = SM.CRSMB_CODIGO AND VOT.CRRES_CODIGO = RSL.CRRES_CODIGO AND VOT.CRVTO_ESTADO
	WHERE SC.CRSSC_ESTADO AND 
		VOT.CRVTO_CODIGO IS NULL AND 
		RSL.CRRES_CODIGO = '||QUOTE_LITERAL(IN_CRRES_CODIGO)||' AND
		SC.CRSSC_CODIGO= '||QUOTE_LITERAL(IN_CRSSC_CODIGO)||' AND
		(LENGTH('||QUOTE_LITERAL(IN_FIND_TEXT)||') = 0 OR SII.F_STRING_IN('''||IN_FIND_TEXT||''',
		COALESCE(PR.CRPER_NOMBRES,'''')||'' ''||
		COALESCE(PR.CRPER_APELLIDO_PATERNO,'''')) = 1)
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100
  ROWS 1000;  

 
/**
* FUNCION SII.F_CGG_RES_VOTAR_MIEMBRO_COMITE_COUNT
* CONTABILIZA EL NUMERO DE VOTOS QUE HICIERON LOS MIEMBROS DEL COMITE.
* @param IN IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @param IN IN_CRSSC_CODIGO IDENTIFICATIVO DE SESION DE COMITE
* @param IN_CRRES_CODIGO IDENTIFICATIVO UNICO DE RESOLUCION
* @return INTEGER
*/ 

CREATE OR REPLACE FUNCTION SII.F_CGG_RES_VOTAR_MIEMBRO_COMITE_COUNT(
IN IN_FIND_TEXT TEXT,
IN IN_CRSSC_CODIGO CHARACTER VARYING,
IN IN_CRRES_CODIGO VARCHAR
)RETURNS INTEGER AS
$BODY$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*)	INTO TMP_ROWS
	FROM SII.CGG_RES_SESION_COMITE SC 
	INNER JOIN SII.CGG_RES_SESION_MIEMBRO SM ON SM.CRSSC_CODIGO = SC.CRSSC_CODIGO AND SM.CRSMB_ESTADO	
	INNER JOIN SII.CGG_RES_MIEMBRO_COMITE MC ON ((SM.CGG_CRMBC_CODIGO IS NULL AND MC.CRMBC_CODIGO = SM.CRMBC_CODIGO) OR (MC.CRMBC_CODIGO = SM.CGG_CRMBC_CODIGO)) AND MC.CRMBC_ESTADO AND MC.CRMBC_AUTORIZADO
	INNER JOIN SII.CGG_USUARIO US ON US.CUSU_CODIGO = MC.CUSU_CODIGO AND US.CUSU_ESTADO
	INNER JOIN SII.CGG_RES_PERSONA PR ON PR.CRPER_CODIGO = US.CRPER_CODIGO AND PR.CRPER_ESTADO
	INNER JOIN SII.CGG_RES_RESOLUCION RSL ON RSL.CRSSC_CODIGO = SC.CRSSC_CODIGO AND RSL.CRRES_ESTADO	
	LEFT JOIN SII.CGG_RES_VOTO VOT ON VOT.CRSMB_CODIGO = SM.CRSMB_CODIGO AND VOT.CRRES_CODIGO = RSL.CRRES_CODIGO AND VOT.CRVTO_ESTADO
	WHERE SC.CRSSC_ESTADO AND 
		VOT.CRVTO_CODIGO IS NULL AND 
		RSL.CRRES_CODIGO = (IN_CRRES_CODIGO) AND
		SC.CRSSC_CODIGO= (IN_CRSSC_CODIGO) AND
		(LENGTH((IN_FIND_TEXT)) = 0 OR SII.F_STRING_IN(IN_FIND_TEXT,
		COALESCE(PR.CRPER_NOMBRES,'')||' '||
		COALESCE(PR.CRPER_APELLIDO_PATERNO,'')) = 1);		
	RETURN TMP_ROWS;		
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;
  
  /**
* FUNCION SII.F_CGG_RES_VOTAR_MIEMBRO_COMITE_COUNT
* CONTABILIZA EL NUMERO DE VOTOS QUE HICIERON LOS MIEMBROS DEL COMITE.
* @param IN IN_CRSSC_CODIGO IDENTIFICATIVO DE SESION DE COMITE
* @return INTEGER
*/ 

CREATE OR REPLACE FUNCTION SII.F_CGG_RES_VOTAR_MIEMBRO_COMITE_COUNT(
IN IN_CRSSC_CODIGO CHARACTER VARYING)
  RETURNS INTEGER AS
$BODY$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT  COUNT(SM.CRSMB_CODIGO) INTO TMP_ROWS
	FROM SII.CGG_RES_PERSONA PR
	INNER JOIN SII.CGG_USUARIO US ON(US.CRPER_CODIGO= PR.CRPER_CODIGO)	
	INNER JOIN SII.CGG_RES_MIEMBRO_COMITE MC ON(MC.CUSU_CODIGO= US.CUSU_CODIGO)
	INNER JOIN SII.CGG_RES_SESION_MIEMBRO SM ON(SM.CRMBC_CODIGO= MC.CRMBC_CODIGO)
	INNER JOIN SII.CGG_RES_SESION_COMITE SC ON(SC.CRSSC_CODIGO= SM.CRSSC_CODIGO)
	WHERE CRPER_ESTADO = TRUE 
	AND SC.CRSSC_CODIGO= IN_CRSSC_CODIGO;
	
	RETURN TMP_ROWS;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;  