/**
* FUNCION SII.F_CGG_RES_EXPULSION_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_EXPULSION.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO 
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @returns REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_EXPULSION_DESCRIP_SELECT(
IN IN_USER_NAME VARCHAR,
IN IN_START_INDEX INT,
IN IN_LIMIT INT,
IN IN_SORT_FIELD_NAME VARCHAR,
IN IN_DIRECTION VARCHAR,
IN IN_FIND_TEXT TEXT
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT
		EX.CREXP_CODIGO, 
		EX.CRMOV_CODIGO, 
		EX.CRNOT_CODIGO,
		(SELECT CRNOT_NUMERO_NOTIFICACION FROM SII.CGG_RES_NOTIFICACION NT WHERE NT.CRNOT_CODIGO = EX.CRNOT_CODIGO) CRNOT_NUMERO_NOTIFICACION ,
		MV.CRPER_CODIGO, 
		PR.CRDID_CODIGO, 
		(SELECT CRDID_DESCRIPCION FROM SII.CGG_RES_DOCUMENTO_IDENTIFICACIO DI WHERE DI.CRDID_CODIGO= PR.CRDID_CODIGO) DOCUMENTO,
		PR.CPRR_CODIGO, 
		(SELECT CPRR_NOMBRE FROM SII.CGG_PARROQUIA PQ WHERE PQ.CPRR_CODIGO= PR.CPRR_CODIGO) PARROQUIA,		
		PR.CCTN_CODIGO, 
		(SELECT CCTN_NOMBRE FROM SII.CGG_CANTON CT WHERE CT.CCTN_CODIGO= PR.CCTN_CODIGO) CANTON,			
		PR.CRPER_NOMBRES,
		COALESCE(PR.CRPER_APELLIDO_PATERNO,'''')||'' ''||COALESCE(PR.CRPER_APELLIDO_MATERNO,'''') APELLIDOS,
		PR.CRPER_NUM_DOC_IDENTIFIC, 
		PR.CRPER_FECHA_NACIMIENTO, 		
		PR.CRPER_GENERO,	
		(SELECT CARPT_NOMBRE FROM  CGG_RES_AEROPUERTO AR WHERE AR.CARPT_CODIGO = MV.CARPT_CODIGO) AEROPUERTO,
		MV.CRMOV_NUMERO_VUELO,				
		NT.CRNOT_FECHA_NOTIFICACION FECHA,
		EX.CROSG_CODIGO,
		(SELECT COALESCE(PRS.CRPER_NOMBRES,'''')||'' ''||COALESCE(PRS.CRPER_APELLIDO_PATERNO,'''')||'' ''||COALESCE(PRS.CRPER_APELLIDO_MATERNO,'''') FROM SII.CGG_RES_PERSONA PRS
			INNER JOIN SII.CGG_USUARIO U ON (U.CRPER_CODIGO = PRS.CRPER_CODIGO)
			INNER JOIN SII.CGG_RES_OFICIAL_SEGUIMIENTO OF ON OF.CUSU_CODIGO = U.CUSU_CODIGO AND OF.CROSG_CODIGO = EX.CROSG_CODIGO
		) OFICIAL_SEGUIMIENTO,	
		PR.CRPER_CODIGO,
		(SELECT COALESCE(PRS.CRPER_NOMBRES,'''')||'' ''||COALESCE(PRS.CRPER_APELLIDO_PATERNO,'''')||'' ''||COALESCE(PRS.CRPER_APELLIDO_MATERNO,'''') FROM CGG_RES_PERSONA PRS WHERE PRS.CRPER_CODIGO = EX.CRPER_CODIGO) TESTIGO,
		EX.CTFSL_CODIGO, 		
		(SELECT CTFSL_NOMBRE FROM CGG_TCT_FORMA_SALIDA  FS WHERE  FS.CTFSL_CODIGO= EX.CTFSL_CODIGO) FORMA_SALIDA ,		
		EX.CREXP_FECHA_EXPULSION, 
		EX.CREXP_TIPO_PAGO, 
		EX.CREXP_VALOR_VUELO, 
		EX.CREXP_OBSERVACION, 
		EX.CREXP_ESTADO, 
		EX.CREXP_FECHA_INSERT, 
		EX.CREXP_USUARIO_INSERT, 
		EX.CREXP_FECHA_UPDATE, 
		EX.CREXP_USUARIO_UPDATE
	FROM SII.CGG_RES_EXPULSION EX
	INNER JOIN SII.CGG_RES_MOVILIDAD MV ON (MV.CRMOV_CODIGO=EX.CRMOV_CODIGO)
	INNER JOIN SII.CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO=MV.CRPER_CODIGO)	
	LEFT JOIN SII.CGG_RES_NOTIFICACION NT ON (NT.CRPER_CODIGO=PR.CRPER_CODIGO)	
	WHERE CREXP_ESTADO AND (LENGTH('||QUOTE_LITERAL(IN_FIND_TEXT)||') = 0 OR SII.F_STRING_IN('''||IN_FIND_TEXT||''',COALESCE(CREXP_FECHA_EXPULSION, CURRENT_TIMESTAMP)||'' ''||COALESCE(CREXP_TIPO_PAGO, 0)||'' ''||COALESCE(CREXP_VALOR_VUELO, 0)||'' ''||COALESCE(CREXP_OBSERVACION, '''')||'' ''||COALESCE(CREXP_ESTADO, FALSE)||'' ''||COALESCE(CREXP_FECHA_INSERT, CURRENT_TIMESTAMP)||'' ''||COALESCE(CREXP_USUARIO_INSERT, '''')||'' ''||COALESCE(CREXP_FECHA_UPDATE, CURRENT_TIMESTAMP)||'' ''||COALESCE(CREXP_USUARIO_UPDATE, '''')) = 1) AND 
		MV.CRMOV_TIPO_SALIDA = 1 AND
		(NT.CRNOT_CODIGO IS NULL OR NT.CRNOT_FECHA_NOTIFICACION = (SELECT MAX(CRNOT_FECHA_NOTIFICACION) FROM SII.CGG_RES_NOTIFICACION WHERE CRPER_CODIGO = PR.CRPER_CODIGO) )
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_EXPULSION_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_RES_EXPULSION.
* @return INT
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_EXPULSION_DESCRIP_COUNT(
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_RES_EXPULSION EX
	INNER JOIN CGG_RES_MOVILIDAD MV ON (MV.CRMOV_CODIGO=EX.CRMOV_CODIGO)
	INNER JOIN CGG_TCT_REGISTRO RG ON (RG.CTREG_CODIGO=MV.CTREG_CODIGO)
	INNER JOIN CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO=RG.CRPER_CODIGO)	
	WHERE CREXP_ESTADO = TRUE
	AND MV.CRMOV_TIPO_SALIDA =1;
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/**
* FUNCION SII.F_CGG_RES_EXPULSION_COUNT
* CONTABILIZA EL NUMERO DE REGISTROS DE LA TABLA SII.CGG_RES_EXPULSION.
* QUE CUMPLEN CON EL CRITERIO DE BUSQUEDA.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TOTAL DE REGISTROS
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_EXPULSION_DESCRIP_COUNT(
IN IN_FIND_TEXT TEXT
)RETURNS INT AS
$$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_RES_EXPULSION EX
	INNER JOIN CGG_RES_MOVILIDAD MV ON (MV.CRMOV_CODIGO=EX.CRMOV_CODIGO)
	INNER JOIN CGG_TCT_REGISTRO RG ON (RG.CTREG_CODIGO=MV.CTREG_CODIGO)
	INNER JOIN CGG_RES_PERSONA PR ON (PR.CRPER_CODIGO=RG.CRPER_CODIGO)	
	WHERE CREXP_ESTADO = TRUE AND SII.F_STRING_IN(IN_FIND_TEXT,COALESCE(CREXP_FECHA_EXPULSION, CURRENT_TIMESTAMP)||' '||COALESCE(CREXP_TIPO_PAGO, 0)||' '||COALESCE(CREXP_VALOR_VUELO, 0)||' '||COALESCE(CREXP_OBSERVACION, '''')||' '||COALESCE(CREXP_ESTADO, FALSE)||' '||COALESCE(CREXP_FECHA_INSERT, CURRENT_TIMESTAMP)||' '||COALESCE(CREXP_USUARIO_INSERT, '''')||' '||COALESCE(CREXP_FECHA_UPDATE, CURRENT_TIMESTAMP)||' '||COALESCE(CREXP_USUARIO_UPDATE, '''')) = 1
	AND MV.CRMOV_TIPO_SALIDA =1;
	RETURN TMP_ROWS;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;