/**FUNCION: f_cgg_dhu_adjunto
* SELECCIONA UN REGISTROS DE LA TABLA SII.CGG_DHU_ADJUNTO.
* @param IN_CDBEC_CODIGO CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/

CREATE OR REPLACE FUNCTION f_cgg_dhu_adjunto(in_cdbec_codigo character varying)
  RETURNS SETOF refcursor AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT
		CDAD_CODIGO, 
		CDBEC_CODIGO, 
		CDAD_DESCRIPCION, 
		CDAD_OBSERVACION, 
		CDAD_NOMBRE_ADJUNTO, 
		CDAD_ADJUNTO, 
		CDAD_TIPO, 
		CDAD_DESCRIPCION_CONTENIDO, 
		CDAD_ESTADO, 
		CDAD_FECHA_INSERT, 
		CDAD_USUARIO_INSERT, 
		CDAD_FECHA_UPDATE, 
		CDAD_USUARIO_UPDATE
	FROM SII.CGG_DHU_ADJUNTO
	WHERE CDAD_ESTADO = TRUE AND 
		CDBEC_CODIGO = IN_CDBEC_CODIGO;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100
  ROWS 1000;
ALTER FUNCTION f_cgg_dhu_adjunto(character varying) OWNER TO sii;
