/**FUNCION: F_CGG_RES_PERSONA_FUNCIONARIO_COUNT()
FUNCION QUE CONTABILIZA LOS REGISTROS DE FUNCIONARIO.
@return integer
*/
CREATE OR REPLACE FUNCTION F_CGG_RES_PERSONA_FUNCIONARIO_COUNT()
  RETURNS integer AS
$BODY$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_RES_PERSONA PER INNER JOIN SII.CGG_USUARIO U ON(PER.CRPER_CODIGO=U.CRPER_CODIGO)
        WHERE PER.CRPER_ESTADO = TRUE AND U.CUSU_ESTADO = TRUE;	
	RETURN TMP_ROWS;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100;
ALTER FUNCTION F_CGG_RES_PERSONA_FUNCIONARIO_COUNT() OWNER TO sii;
