/**
* FUNCION SII.F_CGG_RES_RESOLUCION_VOTO_RESIDENCIA_SELECT
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_RES_PERSONA.
* @param IN_CRTRA_CODIGO IEDNTIFICATIVO UNICO DE TRAMITE
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION F_CGG_RES_RESOLUCION_VOTO_RESIDENCIA_SELECT(IN_CRTRA_CODIGO CHARACTER VARYING)
  RETURNS CHARACTER VARYING AS
$BODY$
DECLARE
	TMP_CRPER_CODIGO CHARACTER VARYING;
	TMP_CRTST_CODIGO CHARACTER VARYING;
	TMP_CRRSD_MODALIDAD CHARACTER VARYING;
	TMP_CRRSD_FECHA_CADUCIDAD TIMESTAMP;
BEGIN
	
	UPDATE SII.CGG_RES_RESIDENCIA SET	
		CRRSD_VIGENTE= '0',
		CRRSD_FECHA_UPDATE = CURRENT_TIMESTAMP		
	WHERE
		CRPER_CODIGO = (SELECT CRPER_CODIGO FROM CGG_RES_TRAMITE WHERE CRTRA_CODIGO = IN_CRTRA_CODIGO)
		AND CRRSD_VIGENTE= '1';
	
	
	SELECT		
		TR.CGG_CRPER_CODIGO,
		TR.CRTST_CODIGO,
		(SELECT CGCNF_CONFIGURACION 
			FROM CGG_CONFIGURACION
			WHERE CGCNF_VALOR_CADENA IN (WITH RECURSIVE TIPO(CRTST_CODIGO)AS(
			SELECT CRTST_CODIGO FROM CGG_RES_TRAMITE WHERE CRTRA_CODIGO = IN_CRTRA_CODIGO
				UNION SELECT TST.CGG_CRTST_CODIGO FROM CGG_RES_TIPO_SOLICITUD_TRAMITE TST, TIPO TP
				WHERE TST.CRTST_CODIGO  = TP.CRTST_CODIGO 
			) SELECT CRTST_CODIGO  FROM TIPO)),
			
		CURRENT_DATE +TR.CRTRA_DIAS_PERMANENCIA INTO 	TMP_CRPER_CODIGO,TMP_CRTST_CODIGO,TMP_CRRSD_MODALIDAD,TMP_CRRSD_FECHA_CADUCIDAD
	FROM SII.CGG_RES_TRAMITE TR					
	WHERE TR.CRTRA_ESTADO = TRUE
	AND TR.CRTRA_CODIGO = IN_CRTRA_CODIGO;
	
	
	RETURN TMP_CRPER_CODIGO||','||TMP_CRTST_CODIGO||','||COALESCE(TMP_CRRSD_MODALIDAD,'NULL')||','||TMP_CRRSD_FECHA_CADUCIDAD;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;

