/**
* FUNCION SII.F_CGG_TCT_REGISTRO_ESTADO_UPDATE
* ACTUALIZA UN REGISTRO EN LA TABLA sii.CGG_TCT_REGISTRO.
* @param IN_CTREG_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE TCT
* @param IN_CGG_CUSU_CODIGO IDENTIFICATIVO UNICO DE REGISTRO 
* @param IN_CTREG_IMPRESION_ESPECIE FECHA DE IMPRESION DE LA ESPECIE
* @param IN_CTREG_ESTADO_REGISTRO ESTADO DEL PROCESO DE REGISTRO DE TCT
		0 - PREREGISTRADA
		1 - IMPRESA
		2 - ACTIVA
		3 - ANULADA
* @param IN_CTREG_USUARIO_UPDATE USUARIO QUE REALIZO LA ACTUALIZACION DE LA INFORMACION
* @return VOID
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_TCT_REGISTRO_ESTADO_UPDATE(
IN IN_CTREG_CODIGO SII.CGG_TCT_REGISTRO.CTREG_CODIGO%TYPE, 
IN IN_CGG_CUSU_CODIGO SII.CGG_TCT_REGISTRO.CGG_CUSU_CODIGO%TYPE, 
IN IN_CTREG_IMPRESION_ESPECIE SII.CGG_TCT_REGISTRO.CTREG_IMPRESION_ESPECIE%TYPE, 
IN IN_CTREG_ESTADO_REGISTRO SII.CGG_TCT_REGISTRO.CTREG_ESTADO_REGISTRO%TYPE, 
IN IN_CTREG_USUARIO_UPDATE SII.CGG_TCT_REGISTRO.CTREG_USUARIO_UPDATE%TYPE
)RETURNS VOID AS
$$
BEGIN
	UPDATE SII.CGG_TCT_REGISTRO SET
		CGG_CUSU_CODIGO = IN_CGG_CUSU_CODIGO, 
		CTREG_IMPRESION_ESPECIE = IN_CTREG_IMPRESION_ESPECIE, 
		CTREG_ESTADO_REGISTRO = IN_CTREG_ESTADO_REGISTRO, 		
		CTREG_FECHA_UPDATE = CURRENT_TIMESTAMP, 
		CTREG_USUARIO_UPDATE = IN_CTREG_USUARIO_UPDATE
	WHERE
		CTREG_CODIGO = IN_CTREG_CODIGO;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;

/** FUNCION SII.F_CGG_TCT_REGISTRO_ESTADO_ANULADA_UPDATE
* ACTUALIZA UN REGISTRO EN LA TABLA sii.CGG_TCT_REGISTRO.
* @param IN_CTREG_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DE TCT
* @param IN_CGG_CUSU_CODIGO IDENTIFICATIVO UNICO DE REGISTRO 
* @param IN_CTREG_IMPRESION_ESPECIE FECHA DE IMPRESION DE LA ESPECIE
* @param IN_CTREG_ESTADO_REGISTRO ESTADO DEL PROCESO DE REGISTRO DE TCT
0 - PREREGISTRADA
1 - IMPRESA
2 - ACTIVA
3 - ANULADA
* @param IN_CTREG_USUARIO_UPDATE USUARIO QUE REALIZO LA ACTUALIZACION DE LA INFORMACION
* @return VOID
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_TCT_REGISTRO_ESTADO_ANULADA_UPDATE(
IN IN_CTREG_CODIGO SII.CGG_TCT_REGISTRO.CTREG_CODIGO%TYPE, 
IN IN_CGG_CUSU_CODIGO SII.CGG_TCT_REGISTRO.CGG_CUSU_CODIGO%TYPE, 
IN IN_CTREG_ESTADO_REGISTRO SII.CGG_TCT_REGISTRO.CTREG_ESTADO_REGISTRO%TYPE, 
IN IN_CTREG_USUARIO_UPDATE SII.CGG_TCT_REGISTRO.CTREG_USUARIO_UPDATE%TYPE
)RETURNS VOID AS
$$
BEGIN
	UPDATE SII.CGG_TCT_REGISTRO SET
		CGG_CUSU_CODIGO = IN_CGG_CUSU_CODIGO, 		
		CTREG_ESTADO_REGISTRO = IN_CTREG_ESTADO_REGISTRO, 		
		CTREG_FECHA_UPDATE = CURRENT_TIMESTAMP, 
		CTREG_USUARIO_UPDATE = IN_CTREG_USUARIO_UPDATE,
		CTREG_COMPLETO = TRUE
	WHERE
		CTREG_CODIGO = IN_CTREG_CODIGO;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;