/**
* FUNCION SII.F_CGG_TCT_REGISTRO_CODIGO_BARRAS_SELECT
* SELECCIONA N REGISTROS DE LA TABLA DE CGG_TCT_REGISTRO.
* @param IN_CTGTR_NUMERO NUMERO SECUENCIA QUE IDENTIFICA AL GRUPO
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_TCT_REGISTRO_CODIGO_BARRAS_SELECT(
IN IN_CTGTR_NUMERO SII.CGG_TCT_GRUPO_TURISTA.CTGTR_NUMERO%TYPE)
  RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT 
		RS.CTREG_CODIGO, 		
		RS.CARPT_CODIGO, 
		LPAD(GT.CTGTR_NUMERO::VARCHAR,7,'0'::VARCHAR) CTGTR_NUMERO,
		(SELECT CARPT_NOMBRE FROM  CGG_RES_AEROPUERTO AR WHERE AR.CARPT_CODIGO = RS.CARPT_CODIGO) AEROPUER_ORIGEN,
		RS.CGG_CARPT_CODIGO, 
		(SELECT CARPT_NOMBRE FROM  CGG_RES_AEROPUERTO AR WHERE AR.CARPT_CODIGO = RS.CGG_CARPT_CODIGO) AEROPUER_DESTINO,
		RS.CRALN_CODIGO, 
		(SELECT CRALN_NOMBRE FROM  CGG_RES_AEROLINEA AL WHERE AL.CRALN_CODIGO = RS.CRALN_CODIGO) AEROLINEA,		
		RS.CTGTR_CODIGO,
		RS.CRTRA_CODIGO, 
		(SELECT CRTRA_NUMERO FROM  CGG_RES_TRAMITE TA WHERE TA.CRTRA_CODIGO = RS.CRTRA_CODIGO) NUMERO,		
		RS.CTREG_FECHA_INGRESO, 		
		RS.CTREG_FECHA_SALIDA, 	
		RS.CTREG_ESTADO_REGISTRO, 
		RS.CTREG_ESTADO_REGISTRO		
	FROM SII.CGG_TCT_REGISTRO RS
	INNER JOIN SII.CGG_TCT_GRUPO_TURISTA GT ON (GT.CTGTR_CODIGO = RS.CTGTR_CODIGO)				
	WHERE CTREG_ESTADO = TRUE AND 		
		NOT RS.CTREG_COMPLETO AND 
		GT.CTGTR_NUMERO  = IN_CTGTR_NUMERO;
	RETURN NEXT TMP_REF;
END
$BODY$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;




