/**
* FUNCION SII.F_CGG_RES_COMITE_TIPO_SOLICITUD_TRAMITE_SELECT
* SELECCIONA TODOS LOS REGISTRO DE LA TABLA SII.CGG_RES_TIPO_SOLICITUD_TRAMITE QUE ESTAN.
* RELACIONADOS CON LA TABLA SII.CGG_RES_COMITE.
* @param IN_CRCOM_CODIGO IDENTIFICATIVO UNICO DE REGISTRO DEL COMITE
* @return REFCURSOR
*/
CREATE OR REPLACE FUNCTION SII.F_CGG_RES_COMITE_TIPO_SOLICITUD_TRAMITE_SELECT(
IN IN_CRCOM_CODIGO SII.CGG_RES_COMITE.CRCOM_CODIGO%TYPE
)RETURNS SETOF REFCURSOR AS
$$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT
		TST.CRTST_CODIGO, 
		TST.CGG_CRTST_CODIGO, 
		TST.CRTPT_CODIGO,
		TPT.CRTPT_NOMBRE, 
		TSTP.CRTST_DESCRIPCION PADRE,
		TST.CRTST_DESCRIPCION, 
		TST.CRTST_OBSERVACION, 
		TST.CRTST_APLICA_GARANTIA, 
		TST.CRTST_APLICA_TRAMITE, 
		TST.CRTST_APLICA_GRUPO, 
		TST.CRTST_ATENCION_CLIENTE, 
		TST.CRTST_RESTRINGIDO, 
		TST.CRTST_COMUNICADO_RADIAL, 
		TST.CRTST_NUMERO_DIAS, 
		TST.CRTST_ESTADO, 
		TST.CRTST_FECHA_INSERT, 
		TST.CRTST_USUARIO_INSERT, 
		TST.CRTST_FECHA_UPDATE, 
		TST.CRTST_USUARIO_UPDATE
	FROM SII.CGG_RES_TIPO_SOLICITUD_TRAMITE TST	
	INNER JOIN SII.CGG_RES_TIPO_SOLICITUD_TRAMITE TSTP ON TSTP.CRTST_CODIGO = TST.CGG_CRTST_CODIGO
	INNER JOIN SII.CGG_RES_TRAMITE_COMITE TC ON (TC.CRTST_CODIGO=TST.CRTST_CODIGO)
	INNER JOIN SII.CGG_RES_COMITE CM ON (CM.CRCOM_CODIGO = TC.CRCOM_CODIGO )
	INNER JOIN SII.CGG_RES_TIPO_TRAMITE TPT ON TPT.CRTPT_CODIGO = TST.CRTPT_CODIGO
	WHERE TST.CRTST_ESTADO AND 
		CM.CRCOM_CODIGO = IN_CRCOM_CODIGO;
	RETURN NEXT TMP_REF;
END
$$
LANGUAGE 'plpgsql' VOLATILE CALLED ON NULL INPUT;
