/**
* FUNCION SII.F_CGG_TCT_GRUPO_TURISTA_USUARIO
* SELECCIONA EL CODIGO DEL USUARIO PARA EL GRUPO TURISTA.
* @param IN_CUSU_NOMBRE_USUARIO NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @return TMP_CODIGO
*/
CREATE OR REPLACE FUNCTION F_CGG_TCT_GRUPO_TURISTA_USUARIO(
IN IN_CUSU_NOMBRE_USUARIO CHARACTER VARYING
)
  RETURNS CHARACTER VARYING AS
$BODY$
DECLARE
	TMP_CODIGO CHARACTER VARYING;
BEGIN
SELECT
	U.CUSU_CODIGO INTO TMP_CODIGO
	FROM SII.CGG_USUARIO U			
	WHERE U.CUSU_ESTADO = TRUE  
	AND U.CUSU_NOMBRE_USUARIO= IN_CUSU_NOMBRE_USUARIO;			 
	
	RETURN TMP_CODIGO;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;
  
 /**
* FUNCION SII.F_CGG_TCT_REGISTRO_USUARIO
* SELECCIONA EL CODIGO DEL USUARIO PARA EL REGISTRO DE TCT.
* @param IN_CUSU_NOMBRE_USUARIO NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @return TMP_CODIGO
*/ 
CREATE OR REPLACE FUNCTION F_CGG_TCT_REGISTRO_USUARIO(
IN IN_CUSU_NOMBRE_USUARIO CHARACTER VARYING
)
  RETURNS CHARACTER VARYING AS
$BODY$
DECLARE
	TMP_CODIGO CHARACTER VARYING;
BEGIN
SELECT
	U.CUSU_CODIGO INTO TMP_CODIGO
	FROM SII.CGG_USUARIO U			
	WHERE U.CUSU_ESTADO = TRUE  
	AND U.CUSU_NOMBRE_USUARIO= IN_CUSU_NOMBRE_USUARIO;			 
	
	RETURN TMP_CODIGO;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;

/**
* FUNCION SII.F_CGG_TCT_GRUPO_TURISTA_USUARIO
* SELECCIONA EL CODIGO DEL USUARIO PARA EL GRUPO TURISTA.
* @param IN_CUSU_NOMBRE_USUARIO NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @return TMP_CODIGO
*/
CREATE OR REPLACE FUNCTION F_CGG_TCT_NUMERO_GRUPO_TURISTA(
IN IN_CTGTR_CODIGO CHARACTER VARYING
)
  RETURNS CHARACTER VARYING AS
$BODY$
DECLARE
	TMP_NUMERO CHARACTER VARYING;
BEGIN
SELECT
	GT.CTGTR_NUMERO  INTO TMP_NUMERO
	FROM SII.CGG_TCT_GRUPO_TURISTA GT
	WHERE GT.CTGTR_ESTADO = TRUE  
	AND GT.CTGTR_CODIGO= IN_CTGTR_CODIGO;			 
	RETURN  LPAD(TMP_NUMERO,7,'0');	
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100; 