
/**FUNCTION: F_CGG_DHU_CURSO_HISTORIAL_COUNT
* CONTABILIZA N REGISTROS DE LA TABLA SII.CGG_DHU_CURSO.
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return TMP_ROWS
*/
CREATE OR REPLACE FUNCTION F_CGG_DHU_CURSO_HISTORIAL_COUNT(IN_FIND_TEXT TEXT)
  RETURNS INTEGER AS
$BODY$
DECLARE
TMP_ROWS INT2;
BEGIN
	SELECT COUNT(*) INTO TMP_ROWS
	FROM SII.CGG_DHU_CURSO CU
	INNER JOIN SII.CGG_CANTON CN ON (CN.CCTN_CODIGO=CU.CCTN_CODIGO)
	INNER JOIN SII.CGG_DHU_TIPO_CURSO TC ON(TC.CDTCR_CODIGO=CU.CDTCR_CODIGO)
	INNER JOIN SII.CGG_SECTOR_PRODUCTIVO SP ON(SP.CSCTP_CODIGO=CU.CSCTP_CODIGO)
	INNER JOIN SII.CGG_DHU_INSTITUCION_RESPONSABLE ITR ON(ITR.CDITR_CODIGO=CU.CDITR_CODIGO)
	INNER JOIN SII.CGG_RES_PERSONA PER ON(PER.CRPER_CODIGO=CU.CRPER_CODIGO)
	WHERE CDCUR_ESTADO = TRUE AND(CU.CDCUR_ESTADO_CURSO=2 OR CU.CDCUR_ESTADO_CURSO=3 OR CU.CDCUR_ESTADO_CURSO=4) AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',COALESCE(CDCUR_DESCRIPCION, '''')||' '||
	COALESCE(CDCUR_FECHA_PREVISTA_INICIO, CURRENT_TIMESTAMP)||' '||
	COALESCE(CDCUR_FECHA_INICIO, CURRENT_TIMESTAMP)||' '||
	COALESCE(CDCUR_FECHA_CULMINACION, CURRENT_TIMESTAMP)||' '||
	COALESCE(CDCUR_FECHA_PREVISTA_CULMINACION,CURRENT_TIMESTAMP)||' '||
	COALESCE(CDCUR_HORARIO, '')||' '||
	COALESCE(CDCUR_HORARIO1, '')||' '||
	COALESCE(CDCUR_NUMERO_HORAS_PEDAGOGICAS, 0)||' '||
	COALESCE(CDCUR_NUMERO_HORAS, 0)||' '||
	COALESCE(CDCUR_NUMERO_MODULOS, 0)||' '||
	COALESCE(CDCUR_CONTENIDO, '')||' '||
	COALESCE(CDCUR_INSTITUCION, '')||' '||
	COALESCE(CDCUR_ESTABLECIMIENTO, '')||' '||
	COALESCE(CDCUR_COSTO, 0)||' '||
	COALESCE(CDCUR_PORCENTAJE_FINANCIADO, 0)||' '||
	COALESCE(CDCUR_OBSERVACION, '')||' '||
	COALESCE(CDCUR_VALORACION, 0)||' '||
	COALESCE(CDCUR_ESTADO_CURSO, 0)||' '||
	COALESCE(CDCUR_ESTADO, FALSE)||' '||
	COALESCE(CDCUR_FECHA_INSERT, CURRENT_TIMESTAMP)||' '||
	COALESCE(CDCUR_USUARIO_INSERT, '')||' '||
	COALESCE(CDCUR_FECHA_UPDATE, CURRENT_TIMESTAMP)||' '||
	COALESCE(CDCUR_USUARIO_UPDATE, '')) = 1	;
	RETURN TMP_ROWS;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100;