/**
* FUNCION SII.f_cgg_dhu_seguimiento_economico_select_page
* SELECCIONA N REGISTROS DE LA TABLA SII.CGG_DHU_SEGUIMIENTO_ECONOMICO.
* @param IN_USER_NAME NOMBRE DE USUARIO DEL SERVIDOR DE APP. O DE LA BASE DE DATOS
* @param IN_START_INDEX INDICE DE INICIO DE REGISTROS
* @param IN_LIMIT NUMERO DE REGISTRO DISCRIMINADOS
* @param IN_SORT_FIELD_NAME COLUMNA DE ORDENAMIENTO
* @param IN_DIRECTION DIRECCION DEL ORDENAMIENTO ASC/DESC
* @param IN_FIND_TEXT CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/

CREATE OR REPLACE FUNCTION SII.f_cgg_dhu_seguimiento_economico_select_page(in_user_name character varying, in_start_index integer, in_limit integer, in_sort_field_name character varying, in_direction character varying, in_find_text text)
  RETURNS SETOF refcursor AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR EXECUTE
	'SELECT
		SE.CDSEC_CODIGO, 
		SE.CDTCP_CODIGO, 
		SE.CDACD_CODIGO, 
		PER.CRPER_NOMBRES,
		PER.CRPER_APELLIDO_PATERNO,
		PER.CRPER_APELLIDO_MATERNO,
		BC.CDBEC_NUMERO_CONVENIO,
		BC.CDBEC_FUNCIONARIO,
		CA.CDACD_NUMERO_CICLO,
		CA.CDACD_ESTADO_APROBACION,
		SE.CDSEC_CODIGO_TRANSFERENCIA, 
		SE.CDSEC_VALOR, 
		SE.CDSEC_FECHA_TRANSFERENCIA, 
		SE.CDSEC_CODIGO_TRANSF_IECE, 
		SE.CDSEC_VALOR_IECE, 
		SE.CDSEC_FECHA_TRANSF_IECE, 
		SE.CDSEC_OBSERVACION, 
		SE.CDSEC_ESTADO, 
		SE.CDSEC_FECHA_INSERT, 
		SE.CDSEC_USUARIO_INSERT, 
		SE.CDSEC_FECHA_UPDATE, 
		SE.CDSEC_USUARIO_UPDATE
	FROM SII.CGG_DHU_SEGUIMIENTO_ECONOMICO SE
	INNER JOIN SII.CGG_DHU_SEGUIMIENTO_ACADEMICO CA ON (CA.CDACD_CODIGO=SE.CDACD_CODIGO)
	INNER JOIN SII.CGG_DHU_BECA BC ON(BC.CDBEC_CODIGO=CA.CDBEC_CODIGO)
	INNER JOIN SII.CGG_RES_PERSONA PER ON(PER.CRPER_CODIGO=BC.CRPER_CODIGO)
	WHERE CDSEC_ESTADO = TRUE AND SII.F_STRING_IN('''||IN_FIND_TEXT||''',
	CASE WHEN SE.CDSEC_CODIGO IS NULL THEN '''' ELSE SE.CDSEC_CODIGO END ||'' ''||
	CASE WHEN SE.CDTCP_CODIGO IS NULL THEN '''' ELSE SE.CDTCP_CODIGO END ||'' ''||
	CASE WHEN SE.CDACD_CODIGO IS NULL THEN '''' ELSE SE.CDACD_CODIGO END ||'' ''||
	CASE WHEN PER.CRPER_NOMBRES IS NULL THEN '''' ELSE PER.CRPER_NOMBRES END||'' ''||
	CASE WHEN PER.CRPER_APELLIDO_PATERNO IS NULL THEN '''' ELSE PER.CRPER_APELLIDO_PATERNO END ||'' ''||
	CASE WHEN PER.CRPER_APELLIDO_MATERNO IS NULL THEN '''' ELSE PER.CRPER_APELLIDO_MATERNO END ||'' ''||
	CASE WHEN BC.CDBEC_NUMERO_CONVENIO IS NULL THEN '''' ELSE BC.CDBEC_NUMERO_CONVENIO END ||'' ''||
	CASE WHEN BC.CDBEC_FUNCIONARIO IS NULL THEN '''' ELSE BC.CDBEC_FUNCIONARIO END ||'' ''||
	CASE WHEN CA.CDACD_NUMERO_CICLO IS NULL THEN 0 ELSE CA.CDACD_NUMERO_CICLO END ||'' ''||
	CASE WHEN CA.CDACD_ESTADO_APROBACION IS NULL THEN 0 ELSE CA.CDACD_ESTADO_APROBACION END ||'' ''||
	CASE WHEN SE.CDSEC_CODIGO_TRANSFERENCIA IS NULL THEN '''' ELSE SE.CDSEC_CODIGO_TRANSFERENCIA END ||'' ''||
	CASE WHEN SE.CDSEC_VALOR IS NULL THEN 0 ELSE CDSEC_VALOR END ||'' ''||
	CASE WHEN SE.CDSEC_FECHA_TRANSFERENCIA IS NULL THEN CURRENT_TIMESTAMP ELSE SE.CDSEC_FECHA_TRANSFERENCIA END ||'' ''||
	CASE WHEN SE.CDSEC_CODIGO_TRANSF_IECE IS NULL THEN '''' ELSE SE.CDSEC_CODIGO_TRANSF_IECE END ||'' ''||
	CASE WHEN SE.CDSEC_VALOR_IECE IS NULL THEN 0 ELSE SE.CDSEC_VALOR_IECE END ||'' ''||
	CASE WHEN SE.CDSEC_FECHA_TRANSF_IECE IS NULL THEN CURRENT_TIMESTAMP ELSE SE.CDSEC_FECHA_TRANSF_IECE END ||'' ''||
	CASE WHEN SE.CDSEC_OBSERVACION IS NULL THEN '''' ELSE SE.CDSEC_OBSERVACION END ||'' ''||
	CASE WHEN SE.CDSEC_ESTADO IS NULL THEN FALSE ELSE SE.CDSEC_ESTADO END ||'' ''||
	CASE WHEN SE.CDSEC_FECHA_INSERT IS NULL THEN CURRENT_TIMESTAMP ELSE SE.CDSEC_FECHA_INSERT END ||'' ''||
	CASE WHEN SE.CDSEC_USUARIO_INSERT IS NULL THEN '''' ELSE SE.CDSEC_USUARIO_INSERT END ||'' ''||
	CASE WHEN SE.CDSEC_FECHA_UPDATE IS NULL THEN CURRENT_TIMESTAMP ELSE SE.CDSEC_FECHA_UPDATE END ||'' ''||
	CASE WHEN SE.CDSEC_USUARIO_UPDATE IS NULL THEN '''' ELSE SE.CDSEC_USUARIO_UPDATE END ) = 1
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100
  ROWS 1000;