
/**FUNCTION: F_CGG_DHU_BECA_SEGUIMIENTO_ACADEMICO_SELECT_COUNT(TEXT)
* SELECCIONA UN REGISTROS DE LA TABLA SII.CGG_RES_PERSONA PARA EL REGISTRO DE REPRESENTANTE.
* @param IN_CDBEC_CODIGO CRITERIO DE BUSQUEDA
* @return REFCURSOR
*/

CREATE OR REPLACE FUNCTION F_CGG_DHU_BECA_REPRESENTANTE(IN_CDBEC_CODIGO CHARACTER VARYING)
  RETURNS SETOF REFCURSOR AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	OPEN TMP_REF FOR
	SELECT		
		PR.CRPER_CODIGO,
		BEC.CDBEC_CODIGO,
		--PR.CRDID_CODIGO,
		--(SELECT CRDID_DESCRIPCION FROM  CGG_RES_DOCUMENTO_IDENTIFICACIO DI WHERE DI.CRDID_CODIGO = PR.CRDID_CODIGO) DOCUMENTO,
		PR.CRPER_NUM_DOC_IDENTIFIC,
		PR.CRPER_NUMERO_RESIDENCIA,
		PR.CRPER_NOMBRES,
		PR.CRPER_APELLIDO_PATERNO,
		PR.CRPER_APELLIDO_MATERNO,
		PR.CRPER_NUMERO_RESIDENCIA,
		INR.CDINR_CODIGO,
		INR.CDINR_DESCRIPCION,
		INR.CDINR_TIPO_REPRESENTANTE
	FROM SII.CGG_RES_PERSONA PR
	INNER JOIN SII.CGG_DHU_INFORMACION_REPRESENTAN INR ON(INR.CRPER_CODIGO=PR.CRPER_CODIGO)	
	INNER JOIN SII.CGG_DHU_BECA BEC ON(BEC.CDBEC_CODIGO=INR.CDBEC_CODIGO)								
	INNER JOIN SII.CGG_RES_RESIDENCIA RS ON (RS.CRPER_CODIGO = PR.CRPER_CODIGO)
        WHERE  RS.CRRSD_VIGENTE = TRUE
	AND RS.CRTST_CODIGO IN 
(WITH RECURSIVE TIPO(CRTST_CODIGO, CGG_CRTSR_CODIGO, CRTST_DESCRIPCION)AS(
	SELECT CRTST_CODIGO, CGG_CRTST_CODIGO, CRTST_DESCRIPCION FROM CGG_RES_TIPO_SOLICITUD_TRAMITE WHERE (CRTST_CODIGO = (SELECT CGCNF_VALOR_CADENA
FROM CGG_CONFIGURACION
WHERE CGCNF_CODIGO = '03') OR CRTST_CODIGO = (SELECT CGCNF_VALOR_CADENA
FROM CGG_CONFIGURACION
WHERE CGCNF_CODIGO = '04'))  AND CRTPT_CODIGO = 'CRTPT1'
	UNION SELECT TST.CRTST_CODIGO, TST.CGG_CRTST_CODIGO, TP.CRTST_DESCRIPCION FROM CGG_RES_TIPO_SOLICITUD_TRAMITE TST, TIPO TP
	WHERE TST.CGG_CRTST_CODIGO = TP.CRTST_CODIGO
) SELECT CRTST_CODIGO  FROM TIPO)
AND BEC.CDBEC_CODIGO=  IN_CDBEC_CODIGO;			
	
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE 'PLPGSQL' VOLATILE
  COST 100
  ROWS 1000;
ALTER FUNCTION F_CGG_DHU_BECA_REPRESENTANTE(CHARACTER VARYING) OWNER TO SII;
