--ACTUALIZA LA ISLA DONDE SE OBTUVO LA RESIDENCIA

ALTER TABLE SII.CGG_RES_RESIDENCIA ADD COLUMN CISLA_CODIGO VARCHAR(20);
COMMENT ON TABLE SII.CGG_RES_RESIDENCIA.CISLA_CODIGO IS 'IDENTIFICATIVO DE LA ISLA DONDE OBTUVO LA RESIDENCIA.';

ALTER TABLE SII.CGG_RES_RESIDENCIA
  ADD CONSTRAINT FK_ISLA_RESIDENCIA FOREIGN KEY (CISLA_CODIGO)
      REFERENCES CGG_ISLA (CISLA_CODIGO) MATCH SIMPLE
      ON UPDATE RESTRICT ON DELETE RESTRICT;
	  
UPDATE SII.CGG_RES_RESIDENCIA RSD SET CISLA_CODIGO = TRM.CISLA_CODIGO
FROM SII.CGG_RES_TRAMITE TRM
WHERE TRM.CRTRA_CODIGO = RSD.CRTRA_CODIGO;