package com.besixplus.sii.objects;

/**
* CLASE Usuario
* TABLA: USUARIO
* DESCRIPCION: ALMACENA INFORMACION DE LOS USUARIOS DEL SISTEMA
* ABREVIATURA:CUSU
*/
public class Usuario {
	private String myCUSU_CODIGO = null;
	private String myCUSU_NOMBRES = null;
	private String myCUSU_APELLIDOS = null;
	
	/**
	 * OBTIENE IDENTIFICATIVO UNICO DE REGISTRO DE USUARIO
	 * @return String IDENTIFICATIVO UNICO DE REGISTRO DE USUARIO
	 */
	public String getCUSU_CODIGO() {
		return myCUSU_CODIGO;
	}
	/**
	 * ESTABLECE IDENTIFICATIVO UNICO DE REGISTRO DE USUARIO
	 * @param inCUSUCODIGO IDENTIFICATIVO UNICO DE REGISTRO DE USUARIO
	 */
	public void setCUSU_CODIGO(String inCUSUCODIGO) {
		myCUSU_CODIGO = inCUSUCODIGO;
	}
	
	/**
	 * OBTIENE NOMBRE DE USUARIO
	 * @return String NOMBRE DE USUARIO
	 */
	public String getCUSU_NOMBRES() {
		return myCUSU_NOMBRES;
	}
	/**
	 * ESTABLECE NOMBRE DE USUARIO
	 * @param inCUSUNOMBRES NOMBRE DE USUARIO
	 */
	public void setCUSU_NOMBRES(String inCUSUNOMBRES) {
		myCUSU_NOMBRES = inCUSUNOMBRES;
	}
	
	/**
	 * OBTIENE LOS APELLIDOS DEL USUARIO
	 * @return String APELLIDO USUARIO
	 */
	public String getCUSU_APELLIDOS() {
		return myCUSU_APELLIDOS;
	}
	/**
	 * ESTABLECE LOS APELLIDOS DEL USUARIO
	 * @param inCUSUAPELLIDOS APELLIDOS USUARIO
	 */
	public void setCUSU_APELLIDOS(String inCUSUAPELLIDOS) {
		myCUSU_APELLIDOS = inCUSUAPELLIDOS;
	}
}
