CREATE OR REPLACE FUNCTION f_cgg_res_tramite_select1(in_user_name character varying, in_start_index integer, in_limit integer, in_sort_field_name character varying, in_direction character varying, in_find_text text)
  RETURNS SETOF refcursor AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
	TMP_USUARIO_CURSOR REFCURSOR;
	SQL_STMT TEXT;
	SQL_USUARIOS TEXT;
	CUSUCODIGO VARCHAR(20);
	TMP_ROW RECORD;
BEGIN

	SQL_USUARIOS:=' ';
	SQL_STMT:=' ';

	SELECT CUSU_CODIGO INTO CUSUCODIGO FROM SII.CGG_USUARIO WHERE CUSU_NOMBRE_USUARIO = IN_USER_NAME;
	TMP_USUARIO_CURSOR := SII.F_CGG_USUARIO_ACCESO_INFORMACION(CUSUCODIGO);

	LOOP
		FETCH TMP_USUARIO_CURSOR INTO TMP_ROW;
		EXIT WHEN NOT FOUND;
		SQL_USUARIOS := SQL_USUARIOS||'T.CRTRA_USUARIO_INSERT = '||QUOTE_LITERAL(TMP_ROW.CUSU_NOMBRE_USUARIO)||' OR ';
	END LOOP;
	CLOSE TMP_USUARIO_CURSOR;

	SQL_USUARIOS := SUBSTRING(SQL_USUARIOS FROM 1 FOR LENGTH(SQL_USUARIOS)-3);

	SQL_STMT := 'SELECT
		CRTRA_CODIGO,
		CRPER_CODIGO,
		CRPER_TAUSPICIANTE,
		CRPJR_CODIGO,
		CRPJR_NOMBRES,
		CGG_CRPER_CODIGO,
		CRPER_TBENEFICIARIO,
		CRPRO_CODIGO,
		CRTST_CODIGO,
		CRTST_DESCRIPCION,
		CVVEH_CODIGO,
		CRETT_CODIGO,
		CRETT_NOMBRE,
		CISLA_CODIGO,
		CVMTR_CODIGO,
		CGG_CVMTR_CODIGO,
		CGG_CVVEH_CODIGO,
		CRTRA_ANIO,
		CRTRA_NUMERO,
		CRTRA_FECHA_RECEPCION,
		CRTRA_ACTIVIDAD_RESIDENCIA,
		ACTIVIDAD_RESIDENCIA,
		CGCRG_NOMBRE,
		CRTRA_OBSERVACION,
		CRTRA_DIAS_PERMANENCIA,
		CRTRA_PENDIENTE,
		CRTRA_OBSERVACION_PENDIENTE,
		CRTRA_ATENCION_CLIENTE,
		CRTRA_COMUNICADO_RADIAL,
		CRTRA_FECHA_INGRESO,
		CRTRA_FECHA_SALIDA,
		CRTRA_MOTIVO,
		CRTRA_FOLIO,
		CRTRA_ESTADO,
		CRTRA_FECHA_INSERT,
		CRTRA_USUARIO_INSERT,
		CRTRA_FECHA_UPDATE,
		CRTRA_USUARIO_UPDATE,
		CRTRA_GRUPO,
		CRTRA_ORDEN
	FROM (
	    SELECT
	   	T.CRTRA_CODIGO,
		T.CRPER_CODIGO,
		SII.F_CGG_RES_PERSONA_SELECT_NOMBRES(T.CRPER_CODIGO) AS CRPER_TAUSPICIANTE,
		T.CRPJR_CODIGO,
		SII.F_CGG_RES_PERSONA_JURIDICA_SELECT_NOMBRES(T.CRPJR_CODIGO) AS CRPJR_NOMBRES,
		T.CGG_CRPER_CODIGO,
		SII.F_CGG_RES_PERSONA_SELECT_NOMBRES(T.CGG_CRPER_CODIGO) AS CRPER_TBENEFICIARIO,
		T.CRPRO_CODIGO,
		T.CRTST_CODIGO,
		F_CGG_RES_TIPO_SOLICITUD_TRAMITE_SELECT_DESCRIPCION(T.CRTST_CODIGO) AS CRTST_DESCRIPCION,
		T.CVVEH_CODIGO,
		T.CRETT_CODIGO,
		STT.CRETT_NOMBRE,
		T.CISLA_CODIGO,
		T.CVMTR_CODIGO,
		T.CGG_CVMTR_CODIGO,
		T.CGG_CVVEH_CODIGO,
		T.CRTRA_ANIO,
		T.CRTRA_NUMERO,
		T.CRTRA_FECHA_RECEPCION,
		T.CRTRA_ACTIVIDAD_RESIDENCIA,
		GMC.CGCRG_NOMBRE,
		SII.F_NOMBRE_CARGO(T.CRTRA_ACTIVIDAD_RESIDENCIA) AS ACTIVIDAD_RESIDENCIA,
		T.CRTRA_OBSERVACION,
		T.CRTRA_DIAS_PERMANENCIA,
		T.CRTRA_PENDIENTE,
		T.CRTRA_OBSERVACION_PENDIENTE,
		T.CRTRA_ATENCION_CLIENTE,
		T.CRTRA_COMUNICADO_RADIAL,
		T.CRTRA_MOTIVO,
		T.CRTRA_FOLIO,
		T.CRTRA_ESTADO,
		T.CRTRA_FECHA_INGRESO,
		T.CRTRA_FECHA_SALIDA,
		T.CRTRA_FECHA_INSERT,
		T.CRTRA_USUARIO_INSERT,
		T.CRTRA_FECHA_UPDATE,
		T.CRTRA_USUARIO_UPDATE,
		T.CRTRA_GRUPO,
		T.CRTRA_ORDEN
	    FROM SII.CGG_RES_TRAMITE T
		LEFT JOIN SII.CGG_GEM_CARGO GMC ON CGCRG_CODIGO = T.CRTRA_ACTIVIDAD_RESIDENCIA
		LEFT JOIN SII.CGG_RES_ESTADO_TRAMITE STT ON STT.CRETT_CODIGO = T.CRETT_CODIGO
		WHERE T.CRTRA_ESTADO AND (('||SQL_USUARIOS||') OR (CRTRA_ATENCION_CLIENTE AND T.CISLA_CODIGO = (SELECT CISLA_CODIGO FROM SII.CGG_USUARIO WHERE CUSU_NOMBRE_USUARIO='''||in_user_name||''')))
	) AS TRA
	WHERE (LENGTH('||QUOTE_LITERAL(IN_FIND_TEXT)||') = 0 OR SII.F_STRING_IN('||QUOTE_LITERAL(IN_FIND_TEXT)||',
		COALESCE(CRPER_TAUSPICIANTE,'''')||'' ''||
		COALESCE(CRPJR_NOMBRES,'''')||'' ''||
		COALESCE(CRPER_TBENEFICIARIO,'''')||'' ''||
		COALESCE(CRTST_DESCRIPCION,'''')||'' ''||
		COALESCE(TRA.CRTRA_ANIO,0)||'' ''||
		COALESCE(TRA.CRTRA_NUMERO,0)||'' ''||
		COALESCE(TO_CHAR(TRA.CRTRA_FECHA_RECEPCION,''DD/MM/YY''),'' '')||'' ''||
		COALESCE(TRA.ACTIVIDAD_RESIDENCIA,'''')||'' ''||
		COALESCE(TRA.CRTRA_OBSERVACION,'''')||'' ''||
		COALESCE(TRA.CRTRA_DIAS_PERMANENCIA,0)||'' ''||
		COALESCE(TRA.CRTRA_PENDIENTE,0)||'' ''||
		COALESCE(TRA.CRTRA_OBSERVACION_PENDIENTE,'''')||'' ''||
		COALESCE(TRA.CRTRA_ATENCION_CLIENTE,FALSE)||'' ''||
		COALESCE(TRA.CRTRA_COMUNICADO_RADIAL,'''')||'' ''||
		COALESCE(TRA.CRTRA_MOTIVO,'''')||'' ''||
		COALESCE(TRA.CRTRA_FOLIO,0)||'' ''||
		COALESCE(TRA.CRTRA_ESTADO,FALSE)||'' ''||
		COALESCE(TRA.CRTRA_USUARIO_INSERT,'''')) = 1)
	ORDER BY '||IN_SORT_FIELD_NAME||' '||IN_DIRECTION||
	' LIMIT '||IN_LIMIT||' OFFSET '||IN_START_INDEX;

	OPEN TMP_REF FOR EXECUTE SQL_STMT;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100
  ROWS 1000;


CREATE OR REPLACE FUNCTION f_cgg_res_tramite_update_isla(in_crtra_codigo character varying, in_cisla_codigo character varying, in_crtra_usuario_update character varying)
  RETURNS void AS
$BODY$
DECLARE
BEGIN
	UPDATE SII.CGG_RES_TRAMITE SET
		CISLA_CODIGO = IN_CISLA_CODIGO,
		CRTRA_FECHA_UPDATE = CURRENT_TIMESTAMP,
		CRTRA_USUARIO_UPDATE = IN_CRTRA_USUARIO_UPDATE
	WHERE CRTRA_CODIGO =  IN_CRTRA_CODIGO;
END
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;

--> MIGRATION SCRIPT CONTROLLER <--
INSERT INTO sii.cgg_migrationscript (mrgsp_codigo,mrgsp_fecha,mrgsp_usuario_insert,mrgsp_fecha_insert,mrgsp_usuario_update,mrgsp_fecha_update,
	mrgsp_estado,mrgsp_developer,mrgsp_name,mrgsp_description,
	mrgsp_releaseno,mrgsp_filename,mrgsp_isapply)
VALUES(SII.F_KEYGEN('CGG_MIGRATIONSCRIPT','MRGSP_CODIGO','MRGSP'), current_timestamp,'ADMIN', current_timestamp,'ADMIN', current_timestamp,
	true,'acanaveral','TRAMITES USUARIOS FINALES','Modifica la funcion que permite desplegar los tramites realizados por un usuario. Para que además se visualicen los tramites de usuarios finales de esa isla',
	'2.0','2016_06_30_Tramites_de_Usuario_Finales.sql',true);