CREATE OR REPLACE FUNCTION f_select_requisitotiposolicitudtramite(in_crtst_codigo character varying, in_crtra_codigo character varying)
  RETURNS SETOF refcursor AS
$BODY$
DECLARE
	TMP_REF REFCURSOR;
BEGIN
	IF(IN_CRTRA_CODIGO IS NULL)THEN

	OPEN TMP_REF FOR
		SELECT
		  CGG_RES_SOLICITUD_REQUISITO.CRSRQ_CODIGO,
		  CGG_RES_SOLICITUD_REQUISITO.CRTST_CODIGO,
		  CGG_RES_SOLICITUD_REQUISITO.CRSRQ_DESCRIPCION,
		  CGG_RES_SOLICITUD_REQUISITO.CRSRQ_REQUERIDO,
		  CGG_RES_SOLICITUD_REQUISITO.CRSRQ_PARTICIPANTE,
		  CGG_RES_REQUISITO.CRREQ_CODIGO,
		  CGG_RES_REQUISITO.CRREQ_DESCRIPCION,
		  ' ' AS CRTRA_CODIGO,
		  ' ' AS CRRQT_CODIGO,
		  false AS CRRQT_CUMPLE,
		  ' ' AS CRRQT_OBSERVACION
		FROM
		  SII.CGG_RES_SOLICITUD_REQUISITO INNER JOIN SII.CGG_RES_REQUISITO ON (CGG_RES_REQUISITO.CRREQ_CODIGO = CGG_RES_SOLICITUD_REQUISITO.CRREQ_CODIGO)
		  WHERE CGG_RES_SOLICITUD_REQUISITO.CRTST_CODIGO = IN_CRTST_CODIGO
		  ORDER BY CGG_RES_SOLICITUD_REQUISITO.CRSRQ_PARTICIPANTE;

	ELSE
		OPEN TMP_REF FOR
		  SELECT
		  CGG_RES_SOLICITUD_REQUISITO.CRSRQ_CODIGO,
		  CGG_RES_SOLICITUD_REQUISITO.CRTST_CODIGO,
		  CGG_RES_SOLICITUD_REQUISITO.CRSRQ_DESCRIPCION,
		  CGG_RES_REQUISITO_TRAMITE.CRRQT_REQUERIDO,
		  CGG_RES_SOLICITUD_REQUISITO.CRSRQ_PARTICIPANTE,
		  CGG_RES_REQUISITO.CRREQ_CODIGO,
		  CGG_RES_REQUISITO.CRREQ_DESCRIPCION,
		  CGG_RES_REQUISITO_TRAMITE.CRTRA_CODIGO,
		  CGG_RES_REQUISITO_TRAMITE.CRRQT_CODIGO,
		  CGG_RES_REQUISITO_TRAMITE.CRRQT_CUMPLE,
		  CGG_RES_REQUISITO_TRAMITE.CRRQT_OBSERVACION
		FROM
		  SII.CGG_RES_SOLICITUD_REQUISITO
		  INNER JOIN SII.CGG_RES_REQUISITO ON (CGG_RES_REQUISITO.CRREQ_CODIGO = CGG_RES_SOLICITUD_REQUISITO.CRREQ_CODIGO)
		  INNER JOIN SII.CGG_RES_REQUISITO_TRAMITE  ON (CGG_RES_SOLICITUD_REQUISITO.CRSRQ_CODIGO = CGG_RES_REQUISITO_TRAMITE.CRSRQ_CODIGO)
		  WHERE CGG_RES_SOLICITUD_REQUISITO.CRTST_CODIGO = IN_CRTST_CODIGO OR CGG_RES_REQUISITO_TRAMITE.CRTRA_CODIGO = IN_CRTRA_CODIGO
		  GROUP BY CGG_RES_SOLICITUD_REQUISITO.CRSRQ_CODIGO,
		  CGG_RES_SOLICITUD_REQUISITO.CRTST_CODIGO,
		  CGG_RES_SOLICITUD_REQUISITO.CRSRQ_DESCRIPCION,
		  CGG_RES_REQUISITO_TRAMITE.CRRQT_REQUERIDO,
		  CGG_RES_SOLICITUD_REQUISITO.CRSRQ_PARTICIPANTE,
		  CGG_RES_REQUISITO.CRREQ_CODIGO,
		  CGG_RES_REQUISITO.CRREQ_DESCRIPCION,
		  CGG_RES_REQUISITO_TRAMITE.CRTRA_CODIGO,
		  CGG_RES_REQUISITO_TRAMITE.CRRQT_CODIGO,
		  CGG_RES_REQUISITO_TRAMITE.CRRQT_CUMPLE,
		  CGG_RES_REQUISITO_TRAMITE.CRRQT_OBSERVACION
		  HAVING CGG_RES_SOLICITUD_REQUISITO.CRTST_CODIGO = IN_CRTST_CODIGO AND  (CGG_RES_REQUISITO_TRAMITE.CRTRA_CODIGO = IN_CRTRA_CODIGO OR CGG_RES_REQUISITO_TRAMITE.CRTRA_CODIGO IS NULL)
		  ORDER BY CGG_RES_SOLICITUD_REQUISITO.CRSRQ_PARTICIPANTE;
	END IF;
	RETURN NEXT TMP_REF;
END
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100
  ROWS 1000;


  --> MIGRATION SCRIPT CONTROLLER <--
INSERT INTO sii.cgg_migrationscript (mrgsp_codigo,mrgsp_fecha,mrgsp_usuario_insert,mrgsp_fecha_insert,mrgsp_usuario_update,mrgsp_fecha_update,
	mrgsp_estado,mrgsp_developer,mrgsp_name,mrgsp_description,
	mrgsp_releaseno,mrgsp_filename,mrgsp_isapply)
VALUES(SII.F_KEYGEN('CGG_MIGRATIONSCRIPT','MRGSP_CODIGO','MRGSP'), current_timestamp,'ADMIN', current_timestamp,'ADMIN', current_timestamp,
	true,'acanaveral','BUGS FIX','Arregla algunos problemas de orden y visualizacion.',
	'2.0','2016_08_02_BugsFixes.sql',true);